export const enUS = {
  "nav.menu.open": "Open menu",
  "nav.menu.close": "Close menu",
  "nav.menu.label": "Mobile menu",
  "document.title": "K-zip",
  "locale.label": "Choose language",
  "locale.ko-KR": "Korean",
  "locale.en-US": "English",
  "locale.ar": "Arabic",
  "locale.ja-JP": "Japanese",
  "locale.vi-VN": "Vietnamese",
  "locale.th-TH": "Thai",
  "locale.zh-CN": "Chinese (Simplified)",
  "locale.zh-TW": "Chinese (Traditional)",
  brand: "K-zip",
  "nav.label": "Primary",
  "nav.proof": "Proof",
  "nav.pricing": "Pricing",
  "nav.cta": "Get early access",
  "hero.title": "Learn the Korean behind the culture.",
  "hero.description":
    "Catch the jokes in the clips you love, handle real life in Korea, and speak naturally to whoever is in front of you.",
  "hero.cta": "Get early access",
  "hero.highlight.clips": "Replay real clips with dual subtitles",
  "hero.highlight.real-life": "Practice Korean for real-life moments",
  "hero.highlight.register": "Switch your words for every relationship",
  "proof.title": "One language. Every side of your K-life.",
  "proof.clips.value": "2 languages",
  "proof.clips.label": "Side-by-side subtitles in every clip",
  "proof.situations.value": "Real life",
  "proof.situations.label": "Practice for the moments you will actually face",
  "proof.relationships.value": "4 registers",
  "proof.relationships.label": "Boss, friend, elder, or stranger",
  "features.clips.title": "Get the meme, then say it.",
  "features.clips.description":
    "Watch YouTube clips and K-drama scenes with Korean and your language side by side. Tap any subtitle to replay the moment, understand words in context, and save natural Korean phrases for review.",
  "features.real-life.title": "Not textbook Korean — the real thing",
  "features.real-life.description":
    "From the situations you'll actually hit living in Korea—hospitals, city offices, part-time jobs—to fan meets, video calls, and cheering on your bias. Learn the Korean your K-pop life actually needs.",
  "features.register.title": "One Meaning,\nEveryone Different",
  "features.register.description":
    "Pick who you're talking to—your boss, a close friend, an elder, a stranger—and say the same thing to each. Watch the words shift with the person, and drill it until switching feels automatic.",
  "features.earlyAccess": "Get early access",
  "pricing.kicker": "Choose your pace",
  "pricing.title": "Start with the Korean you need now.",
  "pricing.subtitle":
    "Replay real clips, prepare for everyday situations, and practice the right level of Korean for every person.",
  "pricing.unit": "/mo",
  "pricing.billing.monthly": "Monthly",
  "pricing.billing.annual": "Annual",
  "pricing.billing.save": "Save 20%",
  "pricing.badge.popular": "Most popular",
  "pricing.free.name": "Free",
  "pricing.free.description": "Try the essentials with a small set of clips and everyday phrases.",
  "pricing.free.cta": "Start free",
  "pricing.free.feature.clips": "Selected dual-subtitle clips",
  "pricing.free.feature.phrases": "Save up to 20 phrases",
  "pricing.free.feature.register": "Basic speech-level practice",
  "pricing.plus.name": "Plus",
  "pricing.plus.description":
    "Build a daily habit across clips, real-life situations, and relationship-based Korean.",
  "pricing.plus.cta": "Start Plus",
  "pricing.plus.feature.unlimited": "Unlimited clip lessons",
  "pricing.plus.feature.situations": "Full real-life situation library",
  "pricing.plus.feature.drills": "Unlimited register drills",
  "pricing.plus.feature.review": "Personal phrase review",
  "pricing.premium.name": "Premium",
  "pricing.premium.description":
    "Get the complete learning experience with deeper practice and early access to new tools.",
  "pricing.premium.cta": "Go Premium",
  "pricing.premium.feature.everything": "Everything in Plus",
  "pricing.premium.feature.pronunciation": "Pronunciation feedback",
  "pricing.premium.feature.practice": "Personalized practice sets",
  "pricing.premium.feature.early-access": "Early access to new features",
  "pricing.footer": "Subscriptions renew automatically. Cancel anytime.",
  "cta.badge": "Built for your K-life",
  "cta.title": "Understand the moment. Say what fits.",
  "cta.description":
    "Learn from the culture you already love, then practice the Korean that works in clips, daily life, and every relationship.",
  "cta.action": "Get early access",
  "cta.note.clips": "Real clips, replayable line by line",
  "cta.note.practice": "Real-life and relationship-based practice",
  "footer.label": "K-zip footer",
  "footer.policy.label": "Policy links",
  "footer.faq.label": "Frequently asked questions",
  "footer.faq.heading": "Frequently asked questions",
  "footer.faq.clips.question": "What can I learn from a clip?",
  "footer.faq.clips.answer":
    "You can view Korean and your language side by side, replay any subtitle, understand words in context, and save natural phrases for review.",
  "footer.faq.real-life.question": "Is this only for K-drama and K-pop?",
  "footer.faq.real-life.answer":
    "No. You can also practice Korean for everyday situations in Korea, including hospitals, city offices, and part-time jobs.",
  "footer.faq.register.question": "Will it help me speak differently to different people?",
  "footer.faq.register.answer":
    "Yes. You can practice the same meaning for a boss, close friend, elder, or stranger until switching speech levels feels natural.",
  "footer.privacy": "Privacy",
  "footer.terms": "Terms",
  "footer.copyright": "© 2026 K-zip. All rights reserved.",
} as const;

export const koKR: Record<keyof typeof enUS, string> = {
  "nav.menu.open": "메뉴 열기",
  "nav.menu.close": "메뉴 닫기",
  "nav.menu.label": "모바일 메뉴",
  "document.title": "K-zip",
  "locale.label": "언어 선택",
  "locale.ko-KR": "한국어",
  "locale.en-US": "영어",
  "locale.ar": "아랍어",
  "locale.ja-JP": "일본어",
  "locale.vi-VN": "베트남어",
  "locale.th-TH": "태국어",
  "locale.zh-CN": "중국어(간체)",
  "locale.zh-TW": "중국어(번체)",
  brand: "K-zip",
  "nav.label": "주요 메뉴",
  "nav.proof": "학습 효과",
  "nav.pricing": "요금제",
  "nav.cta": "얼리 액세스 신청",
  "hero.title": "문화 속 진짜 한국어를 배우세요.",
  "hero.description":
    "좋아하는 영상 속 농담을 알아듣고, 한국에서의 일상을 해결하며, 누구를 만나든 자연스럽게 말해 보세요.",
  "hero.cta": "얼리 액세스 신청",
  "hero.highlight.clips": "실제 영상을 이중 자막으로 반복 재생",
  "hero.highlight.real-life": "실생활 순간에 필요한 한국어 연습",
  "hero.highlight.register": "관계에 맞게 표현 바꾸기",
  "proof.title": "하나의 언어로, K-라이프의 모든 순간을.",
  "proof.clips.value": "2개 언어",
  "proof.clips.label": "모든 영상에서 나란히 보는 이중 자막",
  "proof.situations.value": "진짜 일상",
  "proof.situations.label": "실제로 마주할 순간을 위한 연습",
  "proof.relationships.value": "4가지 말투",
  "proof.relationships.label": "상사, 친구, 어르신 또는 낯선 사람",
  "features.clips.title": "밈을 이해하고, 직접 말해 보세요.",
  "features.clips.description":
    "유튜브 영상과 K-드라마 장면을 한국어와 내 언어로 나란히 보세요. 자막을 눌러 그 순간을 다시 듣고, 문맥 속 단어를 이해하고, 자연스러운 한국어 표현을 저장해 복습할 수 있어요.",
  "features.real-life.title": "교과서 한국어가 아닌, 진짜 한국어",
  "features.real-life.description":
    "병원, 주민센터, 아르바이트처럼 한국 생활에서 실제로 겪을 상황부터 팬 미팅, 영상 통화, 최애 응원까지. K-pop 라이프에 정말 필요한 한국어를 배우세요.",
  "features.register.title": "같은 뜻,\n모두 다른 표현",
  "features.register.description":
    "상사, 친한 친구, 어르신, 낯선 사람 중 대화 상대를 고르고 같은 뜻을 각각 말해 보세요. 상대에 따라 단어가 어떻게 달라지는지 확인하고, 자연스럽게 바꿀 수 있을 때까지 연습하세요.",
  "features.earlyAccess": "얼리 액세스 신청",
  "pricing.kicker": "내 속도에 맞는 선택",
  "pricing.title": "지금 필요한 한국어부터 시작하세요.",
  "pricing.subtitle":
    "실제 영상을 반복하고, 일상 상황을 준비하며, 상대에 맞는 한국어 말투를 연습하세요.",
  "pricing.unit": "/월",
  "pricing.billing.monthly": "월간",
  "pricing.billing.annual": "연간",
  "pricing.billing.save": "20% 절약",
  "pricing.badge.popular": "가장 인기",
  "pricing.free.name": "무료",
  "pricing.free.description": "소수의 영상과 일상 표현으로 핵심 기능을 체험하세요.",
  "pricing.free.cta": "무료로 시작",
  "pricing.free.feature.clips": "선별된 이중 자막 영상",
  "pricing.free.feature.phrases": "표현 최대 20개 저장",
  "pricing.free.feature.register": "기본 말투 연습",
  "pricing.plus.name": "플러스",
  "pricing.plus.description": "영상, 실생활 상황, 관계별 한국어를 아우르는 매일의 습관을 만드세요.",
  "pricing.plus.cta": "플러스 시작",
  "pricing.plus.feature.unlimited": "무제한 영상 레슨",
  "pricing.plus.feature.situations": "전체 실생활 상황 라이브러리",
  "pricing.plus.feature.drills": "무제한 말투 훈련",
  "pricing.plus.feature.review": "나만의 표현 복습",
  "pricing.premium.name": "프리미엄",
  "pricing.premium.description":
    "더 깊은 연습과 새 도구 얼리 액세스로 완전한 학습 경험을 누리세요.",
  "pricing.premium.cta": "프리미엄 시작",
  "pricing.premium.feature.everything": "플러스의 모든 기능",
  "pricing.premium.feature.pronunciation": "발음 피드백",
  "pricing.premium.feature.practice": "맞춤형 연습 세트",
  "pricing.premium.feature.early-access": "새 기능 얼리 액세스",
  "pricing.footer": "구독은 자동 갱신됩니다. 언제든 취소할 수 있습니다.",
  "cta.badge": "당신의 K-라이프를 위해",
  "cta.title": "순간을 이해하고, 상황에 맞게 말하세요.",
  "cta.description":
    "이미 좋아하는 문화로 배우고, 영상과 일상 그리고 모든 관계에서 통하는 한국어를 연습하세요.",
  "cta.action": "얼리 액세스 신청",
  "cta.note.clips": "한 줄씩 반복 가능한 실제 영상",
  "cta.note.practice": "실생활과 관계 중심 연습",
  "footer.label": "K-zip 푸터",
  "footer.policy.label": "정책 링크",
  "footer.faq.label": "자주 묻는 질문",
  "footer.faq.heading": "자주 묻는 질문",
  "footer.faq.clips.question": "영상으로 무엇을 배울 수 있나요?",
  "footer.faq.clips.answer":
    "한국어와 내 언어를 나란히 보고, 자막을 반복 재생하며, 문맥 속 단어를 이해하고 자연스러운 표현을 저장해 복습할 수 있습니다.",
  "footer.faq.real-life.question": "K-드라마와 K-pop만 다루나요?",
  "footer.faq.real-life.answer":
    "아니요. 병원, 주민센터, 아르바이트 등 한국의 일상 상황에 필요한 한국어도 연습할 수 있습니다.",
  "footer.faq.register.question": "상대에 따라 다르게 말하는 법도 배울 수 있나요?",
  "footer.faq.register.answer":
    "네. 상사, 친한 친구, 어르신, 낯선 사람에게 같은 뜻을 다르게 말하며 자연스럽게 말투를 바꿀 때까지 연습할 수 있습니다.",
  "footer.privacy": "개인정보 처리방침",
  "footer.terms": "이용약관",
  "footer.copyright": "© 2026 K-zip. 모든 권리 보유.",
};

export const ar: Record<keyof typeof enUS, string> = {
  "nav.menu.open": "افتح القائمة",
  "nav.menu.close": "أغلق القائمة",
  "nav.menu.label": "قائمة الجوال",
  "document.title": "K-zip",
  "locale.label": "اختر اللغة",
  "locale.ko-KR": "الكورية",
  "locale.en-US": "الإنجليزية",
  "locale.ar": "العربية",
  "locale.ja-JP": "اليابانية",
  "locale.vi-VN": "الفيتنامية",
  "locale.th-TH": "التايلاندية",
  "locale.zh-CN": "الصينية المبسطة",
  "locale.zh-TW": "الصينية التقليدية",
  brand: "K-zip",
  "nav.label": "التنقل الرئيسي",
  "nav.proof": "النتائج",
  "nav.pricing": "الأسعار",
  "nav.cta": "احصل على وصول مبكر",
  "hero.title": "تعلّم الكورية الكامنة وراء الثقافة.",
  "hero.description":
    "افهم النكات في المقاطع التي تحبها، وتعامل مع الحياة اليومية في كوريا، وتحدث بطبيعية مع كل من أمامك.",
  "hero.cta": "احصل على وصول مبكر",
  "hero.highlight.clips": "أعد تشغيل مقاطع حقيقية بترجمة مزدوجة",
  "hero.highlight.real-life": "تدرّب على الكورية لمواقف الحياة الواقعية",
  "hero.highlight.register": "غيّر كلماتك لتناسب كل علاقة",
  "proof.title": "لغة واحدة، لكل جانب من حياتك الكورية.",
  "proof.clips.value": "لغتان",
  "proof.clips.label": "ترجمتان جنبًا إلى جنب في كل مقطع",
  "proof.situations.value": "حياة واقعية",
  "proof.situations.label": "تدرّب للمواقف التي ستواجهها فعلًا",
  "proof.relationships.value": "4 مستويات",
  "proof.relationships.label": "مدير أو صديق أو كبير سن أو غريب",
  "features.clips.title": "افهم النكتة، ثم قلها.",
  "features.clips.description":
    "شاهد مقاطع يوتيوب ومشاهد الدراما الكورية مع الكورية ولغتك جنبًا إلى جنب. اضغط على أي ترجمة لإعادة اللحظة وفهم الكلمات في سياقها وحفظ العبارات الكورية الطبيعية للمراجعة.",
  "features.real-life.title": "ليست كورية الكتب — بل الحقيقية",
  "features.real-life.description":
    "من المواقف التي ستواجهها فعلًا في كوريا—المستشفيات والمكاتب الحكومية والعمل الجزئي—إلى لقاءات المعجبين ومكالمات الفيديو وتشجيع نجمك المفضل. تعلّم الكورية التي تحتاجها حياتك مع K-pop فعلًا.",
  "features.register.title": "معنى واحد،\nوتعبير مختلف للجميع",
  "features.register.description":
    "اختر من تتحدث إليه—مديرك أو صديقًا مقرّبًا أو كبير سن أو غريبًا—وقل المعنى نفسه لكل منهم. شاهد كيف تتغير الكلمات حسب الشخص وتدرّب حتى يصبح الانتقال تلقائيًا.",
  "features.earlyAccess": "احصل على وصول مبكر",
  "pricing.kicker": "اختر وتيرتك",
  "pricing.title": "ابدأ بالكورية التي تحتاجها الآن.",
  "pricing.subtitle":
    "أعد تشغيل مقاطع حقيقية، واستعد للمواقف اليومية، وتدرّب على المستوى المناسب من الكورية لكل شخص.",
  "pricing.unit": "/شهر",
  "pricing.billing.monthly": "شهري",
  "pricing.billing.annual": "سنوي",
  "pricing.billing.save": "وفّر 20%",
  "pricing.badge.popular": "الأكثر رواجًا",
  "pricing.free.name": "مجاني",
  "pricing.free.description": "جرّب الأساسيات مع مجموعة صغيرة من المقاطع والعبارات اليومية.",
  "pricing.free.cta": "ابدأ مجانًا",
  "pricing.free.feature.clips": "مقاطع مختارة بترجمة مزدوجة",
  "pricing.free.feature.phrases": "احفظ حتى 20 عبارة",
  "pricing.free.feature.register": "تدريب أساسي على مستويات الكلام",
  "pricing.plus.name": "بلس",
  "pricing.plus.description":
    "ابنِ عادة يومية عبر المقاطع ومواقف الحياة الواقعية والكورية المناسبة للعلاقات.",
  "pricing.plus.cta": "ابدأ بلس",
  "pricing.plus.feature.unlimited": "دروس مقاطع غير محدودة",
  "pricing.plus.feature.situations": "مكتبة كاملة لمواقف الحياة",
  "pricing.plus.feature.drills": "تدريبات مستويات غير محدودة",
  "pricing.plus.feature.review": "مراجعة شخصية للعبارات",
  "pricing.premium.name": "بريميوم",
  "pricing.premium.description":
    "احصل على تجربة التعلم الكاملة مع تدريب أعمق ووصول مبكر إلى الأدوات الجديدة.",
  "pricing.premium.cta": "اختر بريميوم",
  "pricing.premium.feature.everything": "كل ما في بلس",
  "pricing.premium.feature.pronunciation": "ملاحظات على النطق",
  "pricing.premium.feature.practice": "مجموعات تدريب مخصصة",
  "pricing.premium.feature.early-access": "وصول مبكر للميزات الجديدة",
  "pricing.footer": "تتجدد الاشتراكات تلقائيًا. يمكنك الإلغاء في أي وقت.",
  "cta.badge": "مصمم لحياتك الكورية",
  "cta.title": "افهم اللحظة، وقل ما يناسبها.",
  "cta.description":
    "تعلّم من الثقافة التي تحبها بالفعل، ثم تدرّب على الكورية المناسبة للمقاطع والحياة اليومية وكل علاقة.",
  "cta.action": "احصل على وصول مبكر",
  "cta.note.clips": "مقاطع حقيقية قابلة للإعادة سطرًا بسطر",
  "cta.note.practice": "تدريب للحياة الواقعية والعلاقات",
  "footer.label": "تذييل K-zip",
  "footer.policy.label": "روابط السياسات",
  "footer.faq.label": "الأسئلة الشائعة",
  "footer.faq.heading": "الأسئلة الشائعة",
  "footer.faq.clips.question": "ماذا يمكنني أن أتعلم من مقطع؟",
  "footer.faq.clips.answer":
    "يمكنك مشاهدة الكورية ولغتك جنبًا إلى جنب، وإعادة أي ترجمة، وفهم الكلمات في سياقها، وحفظ العبارات الطبيعية للمراجعة.",
  "footer.faq.real-life.question": "هل هذا مخصص للدراما الكورية وK-pop فقط؟",
  "footer.faq.real-life.answer":
    "لا. يمكنك أيضًا ممارسة الكورية للمواقف اليومية في كوريا، ومنها المستشفيات والمكاتب الحكومية والعمل الجزئي.",
  "footer.faq.register.question": "هل سيساعدني على التحدث بشكل مختلف مع أشخاص مختلفين؟",
  "footer.faq.register.answer":
    "نعم. يمكنك ممارسة المعنى نفسه مع مدير أو صديق مقرّب أو كبير سن أو غريب حتى يصبح تغيير مستوى الكلام طبيعيًا.",
  "footer.privacy": "الخصوصية",
  "footer.terms": "الشروط",
  "footer.copyright": "© 2026 K-zip. جميع الحقوق محفوظة.",
};

export const jaJP = {
  ...enUS,
  "nav.menu.open": "メニューを開く",
  "nav.menu.close": "メニューを閉じる",
  "nav.menu.label": "モバイルメニュー",
  "document.title": "K-zip",
  "locale.label": "言語を選択",
  "locale.ko-KR": "韓国語",
  "locale.en-US": "英語",
  "locale.ar": "アラビア語",
  "locale.ja-JP": "日本語",
  "locale.vi-VN": "ベトナム語",
  "locale.th-TH": "タイ語",
  "locale.zh-CN": "中国語（簡体字）",
  "locale.zh-TW": "中国語（繁体字）",
  brand: "K-zip",
  "nav.label": "メインナビゲーション",
  "nav.proof": "学習効果",
  "nav.pricing": "料金プラン",
  "nav.cta": "早期アクセスに登録",
  "hero.title": "カルチャーの奥にある、本当の韓国語を学ぼう。",
  "hero.description":
    "好きな動画のジョークを理解し、韓国での日常に対応し、目の前の相手に合わせて自然に話せるようになりましょう。",
  "hero.cta": "早期アクセスに登録",
  "hero.highlight.clips": "実際の動画を2言語字幕でリプレイ",
  "hero.highlight.real-life": "日常の場面で使う韓国語を練習",
  "hero.highlight.register": "相手との関係に合わせて表現を変更",
  "proof.title": "ひとつの言語で、Kライフのすべてを。",
  "proof.clips.value": "2言語",
  "proof.clips.label": "すべての動画で字幕を並べて表示",
  "proof.situations.value": "リアルな日常",
  "proof.situations.label": "実際に出会う場面を練習",
  "proof.relationships.value": "4つの話し方",
  "proof.relationships.label": "上司、友人、年長者、初対面の人",
  "features.clips.title": "ミームを理解して、自分でも言ってみよう。",
  "features.clips.description":
    "YouTube動画やKドラマのシーンを、韓国語と自分の言語で並べて視聴。字幕をタップしてその瞬間を再生し、文脈で単語を理解して、自然な韓国語表現を保存・復習できます。",
  "features.real-life.title": "教科書ではない、本物の韓国語",
  "features.real-life.description":
    "病院、役所、アルバイトなど韓国生活で本当に出会う場面から、ファンミーティング、ビデオ通話、推しの応援まで。K-popライフに本当に必要な韓国語を学べます。",
  "features.register.title": "意味は同じ、\n相手ごとに違う表現",
  "features.register.description":
    "上司、親しい友人、年長者、初対面の人から相手を選び、同じ内容をそれぞれに伝えてみましょう。相手による言葉の変化を見て、自然に切り替えられるまで練習できます。",
  "features.earlyAccess": "早期アクセスに登録",
  "pricing.kicker": "自分のペースを選ぶ",
  "pricing.title": "今必要な韓国語から始めよう。",
  "pricing.subtitle":
    "実際の動画を繰り返し、日常の場面に備え、相手ごとに適切な韓国語を練習しましょう。",
  "pricing.unit": "/月",
  "pricing.billing.monthly": "月払い",
  "pricing.billing.annual": "年払い",
  "pricing.billing.save": "20%お得",
  "pricing.badge.popular": "人気",
  "pricing.free.name": "無料",
  "pricing.free.description": "少数の動画と日常表現で基本機能を試せます。",
  "pricing.free.cta": "無料で始める",
  "pricing.free.feature.clips": "厳選された2言語字幕動画",
  "pricing.free.feature.phrases": "表現を20個まで保存",
  "pricing.free.feature.register": "基本的な話し方の練習",
  "pricing.plus.name": "Plus",
  "pricing.plus.description": "動画、実生活の場面、相手別の韓国語を毎日の習慣に。",
  "pricing.plus.cta": "Plusを始める",
  "pricing.plus.feature.unlimited": "動画レッスン無制限",
  "pricing.plus.feature.situations": "実生活シーンの全ライブラリ",
  "pricing.plus.feature.drills": "話し方ドリル無制限",
  "pricing.plus.feature.review": "自分専用の表現復習",
  "pricing.premium.name": "Premium",
  "pricing.premium.description": "より深い練習と新機能への早期アクセスを含む、完全な学習体験。",
  "pricing.premium.cta": "Premiumを始める",
  "pricing.premium.feature.everything": "Plusの全機能",
  "pricing.premium.feature.pronunciation": "発音フィードバック",
  "pricing.premium.feature.practice": "パーソナライズ練習セット",
  "pricing.premium.feature.early-access": "新機能への早期アクセス",
  "pricing.footer": "プランは自動更新されます。いつでも解約できます。",
  "cta.badge": "あなたのKライフのために",
  "cta.title": "その瞬間を理解して、場面に合う言葉を。",
  "cta.description":
    "すでに好きなカルチャーから学び、動画、日常、あらゆる関係で通じる韓国語を練習しましょう。",
  "cta.action": "早期アクセスに登録",
  "cta.note.clips": "実際の動画を一行ずつリプレイ",
  "cta.note.practice": "実生活と人間関係に基づく練習",
  "footer.label": "K-zipフッター",
  "footer.policy.label": "ポリシーリンク",
  "footer.faq.label": "よくある質問",
  "footer.faq.heading": "よくある質問",
  "footer.faq.clips.question": "動画から何を学べますか？",
  "footer.faq.clips.answer":
    "韓国語と自分の言語を並べて表示し、字幕を再生し、文脈で単語を理解して、自然な表現を保存・復習できます。",
  "footer.faq.real-life.question": "KドラマとK-pop専用ですか？",
  "footer.faq.real-life.answer":
    "いいえ。病院、役所、アルバイトなど、韓国での日常に必要な韓国語も練習できます。",
  "footer.faq.register.question": "相手によって話し方を変える練習もできますか？",
  "footer.faq.register.answer":
    "はい。上司、親しい友人、年長者、初対面の人に同じ意味を伝え、自然に話し方を切り替えられるまで練習できます。",
  "footer.privacy": "プライバシー",
  "footer.terms": "利用規約",
  "footer.copyright": "© 2026 K-zip. All rights reserved.",
} satisfies Record<keyof typeof enUS, string>;

export const viVN = {
  ...enUS,
  "nav.menu.open": "Mở menu",
  "nav.menu.close": "Đóng menu",
  "nav.menu.label": "Menu di động",
  "document.title": "K-zip",
  "locale.label": "Chọn ngôn ngữ",
  "locale.ko-KR": "Tiếng Hàn",
  "locale.en-US": "Tiếng Anh",
  "locale.ar": "Tiếng Ả Rập",
  "locale.ja-JP": "Tiếng Nhật",
  "locale.vi-VN": "Tiếng Việt",
  "locale.th-TH": "Tiếng Thái",
  "locale.zh-CN": "Tiếng Trung (Giản thể)",
  "locale.zh-TW": "Tiếng Trung (Phồn thể)",
  brand: "K-zip",
  "nav.label": "Điều hướng chính",
  "nav.proof": "Hiệu quả",
  "nav.pricing": "Bảng giá",
  "nav.cta": "Đăng ký truy cập sớm",
  "hero.title": "Học tiếng Hàn đằng sau văn hóa.",
  "hero.description":
    "Hiểu những câu đùa trong video bạn yêu thích, xử lý cuộc sống thực tại Hàn Quốc và nói tự nhiên với bất kỳ ai trước mặt.",
  "hero.cta": "Đăng ký truy cập sớm",
  "hero.highlight.clips": "Phát lại video thật với phụ đề song ngữ",
  "hero.highlight.real-life": "Luyện tiếng Hàn cho tình huống đời thực",
  "hero.highlight.register": "Đổi cách nói theo từng mối quan hệ",
  "proof.title": "Một ngôn ngữ. Mọi khía cạnh của K-life.",
  "proof.clips.value": "2 ngôn ngữ",
  "proof.clips.label": "Phụ đề song song trong mọi video",
  "proof.situations.value": "Đời thực",
  "proof.situations.label": "Luyện cho những tình huống bạn thực sự gặp",
  "proof.relationships.value": "4 cách nói",
  "proof.relationships.label": "Sếp, bạn bè, người lớn tuổi hoặc người lạ",
  "features.clips.title": "Hiểu meme, rồi tự mình nói.",
  "features.clips.description":
    "Xem video YouTube và cảnh phim Hàn với tiếng Hàn và ngôn ngữ của bạn cạnh nhau. Chạm vào phụ đề để phát lại, hiểu từ trong ngữ cảnh và lưu những cụm tiếng Hàn tự nhiên để ôn tập.",
  "features.real-life.title": "Không phải tiếng Hàn sách vở — mà là tiếng Hàn thật",
  "features.real-life.description":
    "Từ bệnh viện, văn phòng hành chính, việc làm thêm bạn thực sự gặp khi sống ở Hàn Quốc đến fan meeting, gọi video và cổ vũ bias. Học tiếng Hàn mà K-pop life của bạn thật sự cần.",
  "features.register.title": "Cùng một ý,\nMỗi người một cách nói",
  "features.register.description":
    "Chọn người bạn đang nói chuyện—sếp, bạn thân, người lớn tuổi hoặc người lạ—và nói cùng một điều với từng người. Xem từ ngữ thay đổi theo đối tượng và luyện đến khi chuyển đổi tự nhiên.",
  "features.earlyAccess": "Đăng ký truy cập sớm",
  "pricing.kicker": "Chọn nhịp học của bạn",
  "pricing.title": "Bắt đầu với tiếng Hàn bạn cần ngay lúc này.",
  "pricing.subtitle":
    "Phát lại video thật, chuẩn bị cho tình huống hằng ngày và luyện đúng cách nói với từng người.",
  "pricing.unit": "/tháng",
  "pricing.billing.monthly": "Hàng tháng",
  "pricing.billing.annual": "Hàng năm",
  "pricing.billing.save": "Tiết kiệm 20%",
  "pricing.badge.popular": "Phổ biến nhất",
  "pricing.free.name": "Miễn phí",
  "pricing.free.description": "Thử những tính năng thiết yếu với một số video và cụm từ hằng ngày.",
  "pricing.free.cta": "Bắt đầu miễn phí",
  "pricing.free.feature.clips": "Video phụ đề song ngữ chọn lọc",
  "pricing.free.feature.phrases": "Lưu tối đa 20 cụm từ",
  "pricing.free.feature.register": "Luyện cấp độ nói cơ bản",
  "pricing.plus.name": "Plus",
  "pricing.plus.description":
    "Tạo thói quen hằng ngày với video, tình huống đời thực và tiếng Hàn theo mối quan hệ.",
  "pricing.plus.cta": "Bắt đầu Plus",
  "pricing.plus.feature.unlimited": "Bài học video không giới hạn",
  "pricing.plus.feature.situations": "Toàn bộ thư viện tình huống đời thực",
  "pricing.plus.feature.drills": "Bài luyện cách nói không giới hạn",
  "pricing.plus.feature.review": "Ôn tập cụm từ cá nhân",
  "pricing.premium.name": "Premium",
  "pricing.premium.description":
    "Trải nghiệm học đầy đủ với luyện tập chuyên sâu và quyền truy cập sớm công cụ mới.",
  "pricing.premium.cta": "Chọn Premium",
  "pricing.premium.feature.everything": "Mọi tính năng trong Plus",
  "pricing.premium.feature.pronunciation": "Phản hồi phát âm",
  "pricing.premium.feature.practice": "Bộ bài luyện cá nhân hóa",
  "pricing.premium.feature.early-access": "Truy cập sớm tính năng mới",
  "pricing.footer": "Gói tự động gia hạn. Hủy bất cứ lúc nào.",
  "cta.badge": "Dành cho K-life của bạn",
  "cta.title": "Hiểu khoảnh khắc. Nói điều phù hợp.",
  "cta.description":
    "Học từ văn hóa bạn đã yêu thích, rồi luyện tiếng Hàn phù hợp trong video, đời sống hằng ngày và mọi mối quan hệ.",
  "cta.action": "Đăng ký truy cập sớm",
  "cta.note.clips": "Video thật, phát lại từng dòng",
  "cta.note.practice": "Luyện theo đời thực và mối quan hệ",
  "footer.label": "Chân trang K-zip",
  "footer.policy.label": "Liên kết chính sách",
  "footer.faq.label": "Câu hỏi thường gặp",
  "footer.faq.heading": "Câu hỏi thường gặp",
  "footer.faq.clips.question": "Tôi có thể học gì từ một video?",
  "footer.faq.clips.answer":
    "Bạn có thể xem tiếng Hàn và ngôn ngữ của mình cạnh nhau, phát lại phụ đề, hiểu từ trong ngữ cảnh và lưu cụm từ tự nhiên để ôn tập.",
  "footer.faq.real-life.question": "Ứng dụng chỉ dành cho K-drama và K-pop?",
  "footer.faq.real-life.answer":
    "Không. Bạn cũng có thể luyện tiếng Hàn cho tình huống hằng ngày tại Hàn Quốc như bệnh viện, văn phòng hành chính và việc làm thêm.",
  "footer.faq.register.question": "Ứng dụng có giúp tôi nói khác nhau với từng người không?",
  "footer.faq.register.answer":
    "Có. Bạn có thể luyện cùng một ý với sếp, bạn thân, người lớn tuổi hoặc người lạ cho đến khi chuyển cấp độ nói thật tự nhiên.",
  "footer.privacy": "Quyền riêng tư",
  "footer.terms": "Điều khoản",
  "footer.copyright": "© 2026 K-zip. Bảo lưu mọi quyền.",
} satisfies Record<keyof typeof enUS, string>;

export const thTH = {
  ...enUS,
  "nav.menu.open": "เปิดเมนู",
  "nav.menu.close": "ปิดเมนู",
  "nav.menu.label": "เมนูบนมือถือ",
  "document.title": "K-zip",
  "locale.label": "เลือกภาษา",
  "locale.ko-KR": "เกาหลี",
  "locale.en-US": "อังกฤษ",
  "locale.ar": "อาหรับ",
  "locale.ja-JP": "ญี่ปุ่น",
  "locale.vi-VN": "เวียดนาม",
  "locale.th-TH": "ไทย",
  "locale.zh-CN": "จีนตัวย่อ",
  "locale.zh-TW": "จีนตัวเต็ม",
  brand: "K-zip",
  "nav.label": "เมนูหลัก",
  "nav.proof": "ผลลัพธ์",
  "nav.pricing": "ราคา",
  "nav.cta": "สมัคร Early Access",
  "hero.title": "เรียนภาษาเกาหลีที่อยู่เบื้องหลังวัฒนธรรม",
  "hero.description":
    "เข้าใจมุกในคลิปที่คุณชอบ รับมือชีวิตจริงในเกาหลี และพูดอย่างเป็นธรรมชาติกับทุกคนตรงหน้า",
  "hero.cta": "สมัคร Early Access",
  "hero.highlight.clips": "เล่นคลิปจริงซ้ำพร้อมคำบรรยายสองภาษา",
  "hero.highlight.real-life": "ฝึกภาษาเกาหลีสำหรับชีวิตจริง",
  "hero.highlight.register": "ปรับคำพูดให้เหมาะกับทุกความสัมพันธ์",
  "proof.title": "หนึ่งภาษา ครบทุกด้านของ K-life",
  "proof.clips.value": "2 ภาษา",
  "proof.clips.label": "คำบรรยายสองภาษาในทุกคลิป",
  "proof.situations.value": "ชีวิตจริง",
  "proof.situations.label": "ฝึกสถานการณ์ที่คุณจะเจอจริง",
  "proof.relationships.value": "4 ระดับภาษา",
  "proof.relationships.label": "หัวหน้า เพื่อน ผู้ใหญ่ หรือคนแปลกหน้า",
  "features.clips.title": "เข้าใจมีม แล้วพูดตามได้",
  "features.clips.description":
    "ดูคลิป YouTube และฉาก K-drama โดยวางภาษาเกาหลีคู่กับภาษาของคุณ แตะคำบรรยายเพื่อเล่นช่วงนั้นซ้ำ เข้าใจคำศัพท์ในบริบท และบันทึกวลีเกาหลีธรรมชาติเพื่อทบทวน",
  "features.real-life.title": "ไม่ใช่ภาษาเกาหลีในตำรา — แต่เป็นของจริง",
  "features.real-life.description":
    "ตั้งแต่โรงพยาบาล สำนักงานราชการ งานพาร์ตไทม์ที่เจอจริงเมื่ออยู่เกาหลี ไปจนถึงแฟนมีต วิดีโอคอล และการเชียร์เมนของคุณ เรียนภาษาเกาหลีที่ K-pop life ต้องใช้จริง",
  "features.register.title": "ความหมายเดียวกัน\nแต่แต่ละคนพูดต่างกัน",
  "features.register.description":
    "เลือกว่าคุณกำลังคุยกับใคร—หัวหน้า เพื่อนสนิท ผู้ใหญ่ หรือคนแปลกหน้า—แล้วพูดความหมายเดียวกันกับแต่ละคน ดูคำที่เปลี่ยนตามผู้ฟังและฝึกจนสลับได้อัตโนมัติ",
  "features.earlyAccess": "สมัคร Early Access",
  "pricing.kicker": "เลือกจังหวะของคุณ",
  "pricing.title": "เริ่มจากภาษาเกาหลีที่คุณต้องใช้ตอนนี้",
  "pricing.subtitle":
    "เล่นคลิปจริงซ้ำ เตรียมพร้อมสำหรับสถานการณ์ประจำวัน และฝึกภาษาเกาหลีระดับที่เหมาะกับแต่ละคน",
  "pricing.unit": "/เดือน",
  "pricing.billing.monthly": "รายเดือน",
  "pricing.billing.annual": "รายปี",
  "pricing.billing.save": "ประหยัด 20%",
  "pricing.badge.popular": "ยอดนิยม",
  "pricing.free.name": "ฟรี",
  "pricing.free.description": "ทดลองฟีเจอร์หลักด้วยคลิปและวลีในชีวิตประจำวันจำนวนหนึ่ง",
  "pricing.free.cta": "เริ่มฟรี",
  "pricing.free.feature.clips": "คลิปคำบรรยายสองภาษาที่คัดสรร",
  "pricing.free.feature.phrases": "บันทึกได้สูงสุด 20 วลี",
  "pricing.free.feature.register": "ฝึกระดับภาษาพื้นฐาน",
  "pricing.plus.name": "Plus",
  "pricing.plus.description":
    "สร้างนิสัยประจำวันจากคลิป สถานการณ์จริง และภาษาเกาหลีตามความสัมพันธ์",
  "pricing.plus.cta": "เริ่ม Plus",
  "pricing.plus.feature.unlimited": "บทเรียนจากคลิปไม่จำกัด",
  "pricing.plus.feature.situations": "คลังสถานการณ์ชีวิตจริงทั้งหมด",
  "pricing.plus.feature.drills": "แบบฝึกระดับภาษาไม่จำกัด",
  "pricing.plus.feature.review": "ทบทวนวลีส่วนตัว",
  "pricing.premium.name": "Premium",
  "pricing.premium.description":
    "รับประสบการณ์เรียนเต็มรูปแบบพร้อมการฝึกที่ลึกขึ้นและสิทธิ์ใช้เครื่องมือใหม่ก่อนใคร",
  "pricing.premium.cta": "เลือก Premium",
  "pricing.premium.feature.everything": "ทุกอย่างใน Plus",
  "pricing.premium.feature.pronunciation": "คำแนะนำการออกเสียง",
  "pricing.premium.feature.practice": "ชุดฝึกเฉพาะบุคคล",
  "pricing.premium.feature.early-access": "เข้าถึงฟีเจอร์ใหม่ก่อนใคร",
  "pricing.footer": "แพ็กเกจต่ออายุอัตโนมัติ ยกเลิกได้ทุกเมื่อ",
  "cta.badge": "สร้างมาเพื่อ K-life ของคุณ",
  "cta.title": "เข้าใจช่วงเวลา แล้วพูดให้เหมาะ",
  "cta.description":
    "เรียนจากวัฒนธรรมที่คุณรัก แล้วฝึกภาษาเกาหลีที่ใช้ได้ในคลิป ชีวิตประจำวัน และทุกความสัมพันธ์",
  "cta.action": "สมัคร Early Access",
  "cta.note.clips": "คลิปจริง เล่นซ้ำได้ทีละบรรทัด",
  "cta.note.practice": "ฝึกจากชีวิตจริงและความสัมพันธ์",
  "footer.label": "ส่วนท้าย K-zip",
  "footer.policy.label": "ลิงก์นโยบาย",
  "footer.faq.label": "คำถามที่พบบ่อย",
  "footer.faq.heading": "คำถามที่พบบ่อย",
  "footer.faq.clips.question": "ฉันเรียนอะไรจากคลิปได้บ้าง?",
  "footer.faq.clips.answer":
    "คุณดูภาษาเกาหลีคู่กับภาษาของคุณ เล่นคำบรรยายซ้ำ เข้าใจคำในบริบท และบันทึกวลีธรรมชาติเพื่อทบทวนได้",
  "footer.faq.real-life.question": "ใช้สำหรับ K-drama และ K-pop เท่านั้นหรือ?",
  "footer.faq.real-life.answer":
    "ไม่ใช่ คุณยังฝึกภาษาเกาหลีสำหรับชีวิตประจำวันในเกาหลี เช่น โรงพยาบาล สำนักงานราชการ และงานพาร์ตไทม์ได้",
  "footer.faq.register.question": "ช่วยให้ฉันพูดต่างกันกับแต่ละคนได้ไหม?",
  "footer.faq.register.answer":
    "ได้ คุณฝึกความหมายเดียวกันกับหัวหน้า เพื่อนสนิท ผู้ใหญ่ หรือคนแปลกหน้า จนสลับระดับภาษาได้อย่างเป็นธรรมชาติ",
  "footer.privacy": "ความเป็นส่วนตัว",
  "footer.terms": "ข้อกำหนด",
  "footer.copyright": "© 2026 K-zip สงวนลิขสิทธิ์",
} satisfies Record<keyof typeof enUS, string>;

export const zhCN = {
  ...enUS,
  "nav.menu.open": "打开菜单",
  "nav.menu.close": "关闭菜单",
  "nav.menu.label": "移动菜单",
  "document.title": "K-zip",
  "locale.label": "选择语言",
  "locale.ko-KR": "韩语",
  "locale.en-US": "英语",
  "locale.ar": "阿拉伯语",
  "locale.ja-JP": "日语",
  "locale.vi-VN": "越南语",
  "locale.th-TH": "泰语",
  "locale.zh-CN": "简体中文",
  "locale.zh-TW": "繁体中文",
  brand: "K-zip",
  "nav.label": "主导航",
  "nav.proof": "学习效果",
  "nav.pricing": "价格",
  "nav.cta": "申请抢先体验",
  "hero.title": "学习文化背后的真实韩语。",
  "hero.description": "听懂你喜爱视频里的笑点，应对在韩国的真实生活，并与面前的任何人自然交流。",
  "hero.cta": "申请抢先体验",
  "hero.highlight.clips": "用双语字幕重播真实视频",
  "hero.highlight.real-life": "练习真实生活场景中的韩语",
  "hero.highlight.register": "根据每种关系切换表达",
  "proof.title": "一种语言，覆盖你的 K-life 方方面面。",
  "proof.clips.value": "2 种语言",
  "proof.clips.label": "每段视频都提供并排双语字幕",
  "proof.situations.value": "真实生活",
  "proof.situations.label": "练习你真正会遇到的场景",
  "proof.relationships.value": "4 种语体",
  "proof.relationships.label": "上司、朋友、长辈或陌生人",
  "features.clips.title": "看懂梗，然后说出来。",
  "features.clips.description":
    "观看 YouTube 视频和韩剧片段，并排显示韩语和你的语言。点击任意字幕重播当下，在语境中理解词语，并保存自然的韩语短语以便复习。",
  "features.real-life.title": "不是课本韩语 — 而是真正的韩语",
  "features.real-life.description":
    "从在韩国生活时真正会遇到的医院、政府部门、兼职工作，到粉丝见面会、视频通话和为本命应援。学习你的 K-pop 生活真正需要的韩语。",
  "features.register.title": "意思相同，\n人人表达不同",
  "features.register.description":
    "选择交谈对象—上司、好友、长辈或陌生人—并向每个人表达相同意思。观察措辞如何随对象变化，反复练习直到能自然切换。",
  "features.earlyAccess": "申请抢先体验",
  "pricing.kicker": "选择你的节奏",
  "pricing.title": "从你现在需要的韩语开始。",
  "pricing.subtitle": "重播真实视频，为日常场景做好准备，并练习适合每个人的韩语表达。",
  "pricing.unit": "/月",
  "pricing.billing.monthly": "月付",
  "pricing.billing.annual": "年付",
  "pricing.billing.save": "节省 20%",
  "pricing.badge.popular": "最受欢迎",
  "pricing.free.name": "免费",
  "pricing.free.description": "用少量视频和日常短语体验核心功能。",
  "pricing.free.cta": "免费开始",
  "pricing.free.feature.clips": "精选双语字幕视频",
  "pricing.free.feature.phrases": "最多保存 20 个短语",
  "pricing.free.feature.register": "基础语体练习",
  "pricing.plus.name": "Plus",
  "pricing.plus.description": "通过视频、真实生活场景和关系型韩语养成每日习惯。",
  "pricing.plus.cta": "开始 Plus",
  "pricing.plus.feature.unlimited": "不限量视频课程",
  "pricing.plus.feature.situations": "完整真实生活场景库",
  "pricing.plus.feature.drills": "不限量语体训练",
  "pricing.plus.feature.review": "个人短语复习",
  "pricing.premium.name": "Premium",
  "pricing.premium.description": "通过更深入的练习和新工具抢先体验，获得完整学习体验。",
  "pricing.premium.cta": "选择 Premium",
  "pricing.premium.feature.everything": "Plus 的全部功能",
  "pricing.premium.feature.pronunciation": "发音反馈",
  "pricing.premium.feature.practice": "个性化练习集",
  "pricing.premium.feature.early-access": "抢先体验新功能",
  "pricing.footer": "订阅将自动续订，可随时取消。",
  "cta.badge": "为你的 K-life 打造",
  "cta.title": "理解当下，说出合适的话。",
  "cta.description": "从你已经热爱的文化中学习，再练习适用于视频、日常生活和各种关系的韩语。",
  "cta.action": "申请抢先体验",
  "cta.note.clips": "真实视频，可逐句重播",
  "cta.note.practice": "基于真实生活和关系的练习",
  "footer.label": "K-zip 页脚",
  "footer.policy.label": "政策链接",
  "footer.faq.label": "常见问题",
  "footer.faq.heading": "常见问题",
  "footer.faq.clips.question": "我能从视频中学到什么？",
  "footer.faq.clips.answer":
    "你可以并排查看韩语和自己的语言，重播任意字幕，在语境中理解词语，并保存自然短语以便复习。",
  "footer.faq.real-life.question": "这只适用于韩剧和 K-pop 吗？",
  "footer.faq.real-life.answer":
    "不是。你还可以练习医院、政府部门和兼职工作等韩国日常场景所需的韩语。",
  "footer.faq.register.question": "它能帮我对不同的人使用不同说法吗？",
  "footer.faq.register.answer":
    "可以。你可以向上司、好友、长辈或陌生人练习表达相同意思，直到自然切换语体。",
  "footer.privacy": "隐私",
  "footer.terms": "条款",
  "footer.copyright": "© 2026 K-zip。保留所有权利。",
} satisfies Record<keyof typeof enUS, string>;

export const zhTW = {
  ...enUS,
  "nav.menu.open": "開啟選單",
  "nav.menu.close": "關閉選單",
  "nav.menu.label": "行動版選單",
  "document.title": "K-zip",
  "locale.label": "選擇語言",
  "locale.ko-KR": "韓語",
  "locale.en-US": "英語",
  "locale.ar": "阿拉伯語",
  "locale.ja-JP": "日語",
  "locale.vi-VN": "越南語",
  "locale.th-TH": "泰語",
  "locale.zh-CN": "簡體中文",
  "locale.zh-TW": "繁體中文",
  brand: "K-zip",
  "nav.label": "主導覽",
  "nav.proof": "學習效果",
  "nav.pricing": "價格",
  "nav.cta": "申請搶先體驗",
  "hero.title": "學習文化背後的真實韓語。",
  "hero.description": "聽懂你喜愛影片裡的笑點，應對在韓國的真實生活，並與眼前的任何人自然交流。",
  "hero.cta": "申請搶先體驗",
  "hero.highlight.clips": "用雙語字幕重播真實影片",
  "hero.highlight.real-life": "練習真實生活情境中的韓語",
  "hero.highlight.register": "依照每種關係切換表達",
  "proof.title": "一種語言，涵蓋你的 K-life 每一面。",
  "proof.clips.value": "2 種語言",
  "proof.clips.label": "每段影片都提供並排雙語字幕",
  "proof.situations.value": "真實生活",
  "proof.situations.label": "練習你真正會遇到的情境",
  "proof.relationships.value": "4 種語體",
  "proof.relationships.label": "上司、朋友、長輩或陌生人",
  "features.clips.title": "看懂梗，然後說出來。",
  "features.clips.description":
    "觀看 YouTube 影片和韓劇片段，並排顯示韓語和你的語言。點選任意字幕重播當下，在情境中理解詞語，並儲存自然的韓語短句以便複習。",
  "features.real-life.title": "不是課本韓語 — 而是真正的韓語",
  "features.real-life.description":
    "從在韓國生活時真正會遇到的醫院、政府機關、打工，到粉絲見面會、視訊通話和為本命應援。學習你的 K-pop 生活真正需要的韓語。",
  "features.register.title": "意思相同，\n人人表達不同",
  "features.register.description":
    "選擇交談對象—上司、好友、長輩或陌生人—並向每個人表達相同意思。觀察措辭如何隨對象改變，反覆練習直到能自然切換。",
  "features.earlyAccess": "申請搶先體驗",
  "pricing.kicker": "選擇你的步調",
  "pricing.title": "從你現在需要的韓語開始。",
  "pricing.subtitle": "重播真實影片，為日常情境做好準備，並練習適合每個人的韓語表達。",
  "pricing.unit": "/月",
  "pricing.billing.monthly": "月付",
  "pricing.billing.annual": "年付",
  "pricing.billing.save": "節省 20%",
  "pricing.badge.popular": "最受歡迎",
  "pricing.free.name": "免費",
  "pricing.free.description": "用少量影片和日常短句體驗核心功能。",
  "pricing.free.cta": "免費開始",
  "pricing.free.feature.clips": "精選雙語字幕影片",
  "pricing.free.feature.phrases": "最多儲存 20 個短句",
  "pricing.free.feature.register": "基礎語體練習",
  "pricing.plus.name": "Plus",
  "pricing.plus.description": "透過影片、真實生活情境和關係型韓語養成每日習慣。",
  "pricing.plus.cta": "開始 Plus",
  "pricing.plus.feature.unlimited": "不限量影片課程",
  "pricing.plus.feature.situations": "完整真實生活情境庫",
  "pricing.plus.feature.drills": "不限量語體訓練",
  "pricing.plus.feature.review": "個人短句複習",
  "pricing.premium.name": "Premium",
  "pricing.premium.description": "透過更深入的練習和新工具搶先體驗，獲得完整學習體驗。",
  "pricing.premium.cta": "選擇 Premium",
  "pricing.premium.feature.everything": "Plus 的全部功能",
  "pricing.premium.feature.pronunciation": "發音回饋",
  "pricing.premium.feature.practice": "個人化練習集",
  "pricing.premium.feature.early-access": "搶先體驗新功能",
  "pricing.footer": "訂閱將自動續訂，可隨時取消。",
  "cta.badge": "為你的 K-life 打造",
  "cta.title": "理解當下，說出合適的話。",
  "cta.description": "從你已經熱愛的文化中學習，再練習適用於影片、日常生活和各種關係的韓語。",
  "cta.action": "申請搶先體驗",
  "cta.note.clips": "真實影片，可逐句重播",
  "cta.note.practice": "以真實生活和關係為基礎的練習",
  "footer.label": "K-zip 頁尾",
  "footer.policy.label": "政策連結",
  "footer.faq.label": "常見問題",
  "footer.faq.heading": "常見問題",
  "footer.faq.clips.question": "我能從影片中學到什麼？",
  "footer.faq.clips.answer":
    "你可以並排查看韓語和自己的語言，重播任意字幕，在情境中理解詞語，並儲存自然短句以便複習。",
  "footer.faq.real-life.question": "這只適用於韓劇和 K-pop 嗎？",
  "footer.faq.real-life.answer": "不是。你也可以練習醫院、政府機關和打工等韓國日常情境所需的韓語。",
  "footer.faq.register.question": "它能幫我對不同的人使用不同說法嗎？",
  "footer.faq.register.answer":
    "可以。你可以向上司、好友、長輩或陌生人練習表達相同意思，直到自然切換語體。",
  "footer.privacy": "隱私權",
  "footer.terms": "條款",
  "footer.copyright": "© 2026 K-zip。保留所有權利。",
} satisfies Record<keyof typeof enUS, string>;
