export const koKR = {
  "nav.menu.open": "메뉴 열기",
  "nav.menu.close": "메뉴 닫기",
  "nav.menu.label": "모바일 메뉴",
  "document.title": "Luma K-컬처",
  "locale.label": "언어 선택",
  "locale.ko-KR": "한국어",
  "locale.en-US": "영어",
  "locale.ar": "아랍어",
  brand: "Luma 컬처",
  "nav.label": "주요 메뉴",
  "nav.discover": "발견",
  "nav.impact": "영향력",
  "nav.cta": "지금 탐험하기",
  "hero.eyebrow": "이어지는 K-컬처",
  "hero.title": "지금 문화를 만드는 이야기를 발견하세요",
  "hero.description": "음악, 음식, 스타일과 아이디어를 하나의 친근한 글로벌 경험에서 만나보세요.",
  "hero.explore": "컬렉션 탐험",
  "hero.impact": "영향력 보기",
  "hero.preview": "문화 컬렉션 미리보기",
  "proof.title": "국경을 넘어 움직이는 문화",
  "proof.stories.value": "120+",
  "proof.stories.label": "엄선된 이야기",
  "proof.regions.value": "18",
  "proof.regions.label": "연결된 지역",
  "proof.weekly.value": "매주",
  "proof.weekly.label": "새로운 발견",
  "features.title": "탐험할 문화의 세계",
  "features.music.title": "다음 소리를\n듣다",
  "features.music.description": "국경을 넘어 관객을 만나는\n아티스트와 음악을 만나보세요.",
  "features.taste.title": "문화를 맛보다",
  "features.taste.description": "세계적인 음식 흐름 뒤의 요리와 전통을 발견하세요.",
  "features.style.title": "새로운 관점을 따르다",
  "features.style.description": "창작자들이 지역의 표현을 세계적인 영감으로 바꾸는 방법을 보세요.",
  "cta.title": "다음 문화적 발견을 찾아보세요",
  "cta.description": "어디서나 호기심 많은 사람들을 연결하는 컬렉션을 탐험하세요.",
  "cta.action": "발견 시작",
  "footer.message": "문화는 우리를 잇습니다",
  "footer.top": "맨 위로",
  "footer.label": "Luma 컬처 푸터",
  "footer.links.label": "문화 탐색 링크",
  "footer.policy.label": "정책 링크",
  "footer.faq.label": "자주 묻는 질문",
  "footer.faq.heading": "자주 묻는 질문",
  "footer.faq.collection.question": "컬렉션에는 무엇이 있나요?",
  "footer.faq.collection.answer":
    "음악, 음식, 스타일과 아이디어를 다루는 엄선된 이야기를 만나볼 수 있습니다.",
  "footer.faq.updates.question": "새로운 콘텐츠는 얼마나 자주 추가되나요?",
  "footer.faq.updates.answer": "새로운 문화적 발견을 매주 컬렉션에 추가합니다.",
  "footer.privacy": "개인정보 처리방침",
  "footer.terms": "이용약관",
  "footer.copyright": "© 2026 Luma 컬처. 모든 권리 보유.",
} as const;
export const enUS: Record<keyof typeof koKR, string> = {
  "nav.menu.open": "Open menu",
  "nav.menu.close": "Close menu",
  "nav.menu.label": "Mobile menu",
  "document.title": "Luma K-Culture",
  "locale.label": "Choose language",
  "locale.ko-KR": "Korean",
  "locale.en-US": "English",
  "locale.ar": "Arabic",
  brand: "Luma Culture",
  "nav.label": "Primary",
  "nav.discover": "Discover",
  "nav.impact": "Impact",
  "nav.cta": "Explore now",
  "hero.eyebrow": "K-culture, connected",
  "hero.title": "Discover the stories shaping culture now",
  "hero.description":
    "Explore music, food, style, and ideas through one welcoming global experience.",
  "hero.explore": "Explore the collection",
  "hero.impact": "See the impact",
  "hero.preview": "Culture collection preview",
  "proof.title": "Culture moving across borders",
  "proof.stories.value": "120+",
  "proof.stories.label": "Stories curated",
  "proof.regions.value": "18",
  "proof.regions.label": "Regions connected",
  "proof.weekly.value": "Weekly",
  "proof.weekly.label": "New discoveries",
  "features.title": "A world of culture to explore",
  "features.music.title": "Hear what\nis next",
  "features.music.description": "Meet the artists and sounds\nfinding audiences across borders.",
  "features.taste.title": "Taste the culture",
  "features.taste.description": "Discover the dishes and traditions behind a global food movement.",
  "features.style.title": "Follow new perspectives",
  "features.style.description":
    "See how creators turn local expression into worldwide inspiration.",
  "cta.title": "Find your next cultural discovery",
  "cta.description": "Start exploring a collection made to connect curious people everywhere.",
  "cta.action": "Start discovering",
  "footer.message": "Culture connects us",
  "footer.top": "Back to top",
  "footer.label": "Luma Culture footer",
  "footer.links.label": "Culture discovery links",
  "footer.policy.label": "Policy links",
  "footer.faq.label": "Frequently asked questions",
  "footer.faq.heading": "Frequently asked questions",
  "footer.faq.collection.question": "What is included in the collection?",
  "footer.faq.collection.answer":
    "Discover curated stories spanning music, food, style, and ideas.",
  "footer.faq.updates.question": "How often is new content added?",
  "footer.faq.updates.answer": "New cultural discoveries are added to the collection every week.",
  "footer.privacy": "Privacy",
  "footer.terms": "Terms",
  "footer.copyright": "© 2026 Luma Culture. All rights reserved.",
};
export const ar: Record<keyof typeof koKR, string> = {
  "nav.menu.open": "افتح القائمة",
  "nav.menu.close": "أغلق القائمة",
  "nav.menu.label": "قائمة الجوال",
  "document.title": "لوما للثقافة الكورية",
  "locale.label": "اختر اللغة",
  "locale.ko-KR": "الكورية",
  "locale.en-US": "الإنجليزية",
  "locale.ar": "العربية",
  brand: "ثقافة لوما",
  "nav.label": "التنقل الرئيسي",
  "nav.discover": "اكتشف",
  "nav.impact": "الأثر",
  "nav.cta": "استكشف الآن",
  "hero.eyebrow": "الثقافة الكورية مترابطة",
  "hero.title": "اكتشف القصص التي تشكل الثقافة اليوم",
  "hero.description": "استكشف الموسيقى والطعام والأناقة والأفكار في تجربة عالمية مرحبة.",
  "hero.explore": "استكشف المجموعة",
  "hero.impact": "شاهد الأثر",
  "hero.preview": "معاينة المجموعة الثقافية",
  "proof.title": "ثقافة تعبر الحدود",
  "proof.stories.value": "+١٢٠",
  "proof.stories.label": "قصة منتقاة",
  "proof.regions.value": "١٨",
  "proof.regions.label": "منطقة مترابطة",
  "proof.weekly.value": "أسبوعياً",
  "proof.weekly.label": "اكتشافات جديدة",
  "features.title": "عالم من الثقافة للاستكشاف",
  "features.music.title": "استمع إلى\nالقادم",
  "features.music.description": "تعرّف على الفنانين والأصوات\nالتي تجد جمهوراً عبر الحدود.",
  "features.taste.title": "تذوق الثقافة",
  "features.taste.description": "اكتشف الأطباق والتقاليد وراء حركة الطعام العالمية.",
  "features.style.title": "اتبع رؤى جديدة",
  "features.style.description": "شاهد كيف يحول المبدعون التعبير المحلي إلى إلهام عالمي.",
  "cta.title": "اعثر على اكتشافك الثقافي التالي",
  "cta.description": "ابدأ استكشاف مجموعة تربط الفضوليين في كل مكان.",
  "cta.action": "ابدأ الاكتشاف",
  "footer.message": "الثقافة تجمعنا",
  "footer.top": "العودة إلى الأعلى",
  "footer.label": "تذييل ثقافة لوما",
  "footer.links.label": "روابط اكتشاف الثقافة",
  "footer.policy.label": "روابط السياسات",
  "footer.faq.label": "الأسئلة الشائعة",
  "footer.faq.heading": "الأسئلة الشائعة",
  "footer.faq.collection.question": "ماذا تتضمن المجموعة؟",
  "footer.faq.collection.answer": "اكتشف قصصاً منتقاة تشمل الموسيقى والطعام والأناقة والأفكار.",
  "footer.faq.updates.question": "كم مرة يضاف محتوى جديد؟",
  "footer.faq.updates.answer": "تضاف اكتشافات ثقافية جديدة إلى المجموعة كل أسبوع.",
  "footer.privacy": "الخصوصية",
  "footer.terms": "الشروط",
  "footer.copyright": "© 2026 ثقافة لوما. جميع الحقوق محفوظة.",
};
