export const enUS = {
  "nav.menu.open": "Open menu",
  "nav.menu.close": "Close menu",
  "nav.menu.label": "Mobile menu",
  "document.title": "K-zip — Learn Korean through K-Culture",
  "locale.label": "Choose language",
  "locale.ko-KR": "Korean",
  "locale.en-US": "English",
  "locale.ar": "Arabic",
  "locale.ja-JP": "Japanese",
  "locale.vi-VN": "Vietnamese",
  "locale.th-TH": "Thai",
  "locale.zh-CN": "Chinese (Simplified)",
  "locale.zh-TW": "Chinese (Traditional)",
  brand: "K-zip",
  "nav.label": "Primary",
  "nav.proof": "Proof",
  "nav.pricing": "Pricing",
  "nav.cta": "Get early access",
  "hero.title": "Learn the Korean behind the culture.",
  "hero.description":
    "Catch the jokes in the clips you love, handle real life in Korea, and speak naturally to whoever is in front of you.",
  "hero.cta": "Get early access",
  "hero.highlight.clips": "Replay real clips with dual subtitles",
  "hero.highlight.real-life": "Practice Korean for real-life moments",
  "hero.highlight.register": "Switch your words for every relationship",
  "hero.visual.feed": "A short-form feed replaying a Korean meme clip with its pronunciation.",
  "hero.visual.situations": "A lesson card cycling through everyday Korean situations.",
  "proof.title": "One language. Every side of your K-life.",
  "proof.clips.value": "2 languages",
  "proof.clips.label": "Side-by-side subtitles in every clip",
  "proof.situations.value": "Real life",
  "proof.situations.label": "Practice for the moments you will actually face",
  "proof.relationships.value": "4 registers",
  "proof.relationships.label": "Boss, friend, elder, or stranger",
  "features.clips.title": '"lucky vicky"...? What does that even mean?',
  "features.clips.description":
    "From your bias's catchphrases to iconic K-drama lines — what it means, where it came from, when to use it, all on one card. Found one you love? Play the clip, nail the delivery, and drop it with your friends like a local.",
  "features.real-life.title": "What you actually need — in a pack",
  "features.real-life.description":
    "No textbook chapters. Only the stuff your hobby actually calls for, hand-picked.",
  "features.register.title": "\"Let's eat\" isn't one sentence in Korean",
  "features.register.description":
    "Your friend, your sunbae, your bias, someone older — who you're talking to, what the situation is, how close you are: in Korean, all of it changes what you say. Chat with personas in a KakaoTalk-style sim: nail the tone and the conversation flows, miss it and watch them react. Make all your mistakes here — so when it counts, you sound natural.",
  "features.earlyAccess": "Get early access",
  "visual.one.goodFortune": "good fortune",
  "visual.one.englishName": "Wonyoung’s English name",
  "visual.one.definition": "Reframe a small inconvenience as unexpected good luck.",
  "visual.one.example": "“The café sold out, so I got a fresh batch — totally Lucky Vicky!”",
  "visual.one.confirm": "Got it — lucky me!",
  "visual.one.bannerTitle": "Korea's freshest memes, shipped to your front door.",
  "visual.one.bannerDescription": "Meaning and origin, made simple.",
  "visual.one.likes": "100+ likes",
  "visual.one.instruction": "Tap to shadow the line, save it, or swipe for the next short clip.",
  "visual.one.shadow": "Start Shadowing",
  "visual.two.loading": "Loading lesson",
  "visual.two.food.title": "How to order?",
  "visual.two.food.prompt": "How do you order in Korea?",
  "visual.two.food.action": "Start the lesson",
  "visual.two.fansign.title": "Practice a fansign",
  "visual.two.fansign.prompt": "What will you say to your bias?",
  "visual.two.fansign.action": "Start practicing",
  "visual.two.school.title": "School life basics",
  "visual.two.school.prompt": "Ready for your first day?",
  "visual.two.school.action": "Start the lesson",
  "visual.three.demo": "Thank you so much for today",
  "visual.three.inputLabel": "English meaning to practice",
  "visual.three.placeholder": "Type what you want to say in English",
  "visual.three.submitLabel": "Show Korean expressions by relationship",
  "visual.three.friend.label": "Friend",
  "visual.three.friend.tone": "Casual banmal Korean",
  "visual.three.elder.label": "Elder professor",
  "visual.three.elder.tone": "Formal honorific Korean",
  "visual.three.boss.label": "Workplace boss",
  "visual.three.boss.tone": "Polite and professional",
  "pricing.kicker": "Choose your pace",
  "pricing.title": "Start with the Korean you need now.",
  "pricing.subtitle":
    "Replay real clips, prepare for everyday situations, and practice the right level of Korean for every person.",
  "pricing.unit": "/mo",
  "pricing.billing.monthly": "Monthly",
  "pricing.billing.annual": "Annual",
  "pricing.billing.save": "Save 20%",
  "pricing.badge.popular": "Most popular",
  "pricing.free.name": "Free",
  "pricing.free.description": "Try the essentials with a small set of clips and everyday phrases.",
  "pricing.free.cta": "Start free",
  "pricing.free.feature.clips": "Selected dual-subtitle clips",
  "pricing.free.feature.phrases": "Save up to 20 phrases",
  "pricing.free.feature.register": "Basic speech-level practice",
  "pricing.plus.name": "Plus",
  "pricing.plus.description":
    "Build a daily habit across clips, real-life situations, and relationship-based Korean.",
  "pricing.plus.cta": "Start Plus",
  "pricing.plus.feature.unlimited": "Unlimited clip lessons",
  "pricing.plus.feature.situations": "Full real-life situation library",
  "pricing.plus.feature.drills": "Unlimited register drills",
  "pricing.plus.feature.review": "Personal phrase review",
  "pricing.premium.name": "Premium",
  "pricing.premium.description":
    "Get the complete learning experience with deeper practice and early access to new tools.",
  "pricing.premium.cta": "Go Premium",
  "pricing.premium.feature.everything": "Everything in Plus",
  "pricing.premium.feature.pronunciation": "Pronunciation feedback",
  "pricing.premium.feature.practice": "Personalized practice sets",
  "pricing.premium.feature.early-access": "Early access to new features",
  "pricing.footer": "Subscriptions renew automatically. Cancel anytime.",
  "cta.badge": "Built for your K-life",
  "cta.title": "Understand the moment. Say what fits.",
  "cta.description":
    "Learn from the culture you already love, then practice the Korean that works in clips, daily life, and every relationship.",
  "cta.action": "Get early access",
  "cta.note.clips": "Real clips, replayable line by line",
  "cta.note.practice": "Real-life and relationship-based practice",
  "footer.label": "K-zip footer",
  "footer.policy.label": "Policy links",
  "footer.faq.label": "Frequently asked questions",
  "footer.faq.heading": "Frequently asked questions",
  "footer.faq.clips.question": "What can I learn from a clip?",
  "footer.faq.clips.answer":
    "You can view Korean and your language side by side, replay any subtitle, understand words in context, and save natural phrases for review.",
  "footer.faq.real-life.question": "Is this only for K-drama and K-pop?",
  "footer.faq.real-life.answer":
    "No. You can also practice Korean for everyday situations in Korea, including hospitals, city offices, and part-time jobs.",
  "footer.faq.register.question": "Will it help me speak differently to different people?",
  "footer.faq.register.answer":
    "Yes. You can practice the same meaning for a boss, close friend, elder, or stranger until switching speech levels feels natural.",
  "footer.privacy": "Privacy",
  "footer.terms": "Terms",
  "footer.copyright": "© 2026 K-zip. All rights reserved.",
} as const;

export const koKR: Record<keyof typeof enUS, string> = {
  "nav.menu.open": "메뉴 열기",
  "nav.menu.close": "메뉴 닫기",
  "nav.menu.label": "모바일 메뉴",
  "document.title": "K-zip — Learn Korean through K-Culture",
  "locale.label": "언어 선택",
  "locale.ko-KR": "한국어",
  "locale.en-US": "영어",
  "locale.ar": "아랍어",
  "locale.ja-JP": "일본어",
  "locale.vi-VN": "베트남어",
  "locale.th-TH": "태국어",
  "locale.zh-CN": "중국어(간체)",
  "locale.zh-TW": "중국어(번체)",
  brand: "K-zip",
  "nav.label": "주요 메뉴",
  "nav.proof": "학습 효과",
  "nav.pricing": "요금제",
  "nav.cta": "얼리 액세스 신청",
  "hero.title": "문화 속 진짜 한국어를 배우세요.",
  "hero.description":
    "좋아하는 영상 속 농담을 알아듣고, 한국에서의 일상을 해결하며, 누구를 만나든 자연스럽게 말해 보세요.",
  "hero.cta": "얼리 액세스 신청",
  "hero.highlight.clips": "실제 영상을 이중 자막으로 반복 재생",
  "hero.highlight.real-life": "실생활 순간에 필요한 한국어 연습",
  "hero.highlight.register": "관계에 맞게 표현 바꾸기",
  "hero.visual.feed": "한국어 밈 영상을 발음과 함께 다시 보여주는 숏폼 피드.",
  "hero.visual.situations": "일상 속 한국어 상황을 차례로 보여주는 레슨 카드.",
  "proof.title": "하나의 언어로, K-라이프의 모든 순간을.",
  "proof.clips.value": "2개 언어",
  "proof.clips.label": "모든 영상에서 나란히 보는 이중 자막",
  "proof.situations.value": "진짜 일상",
  "proof.situations.label": "실제로 마주할 순간을 위한 연습",
  "proof.relationships.value": "4가지 말투",
  "proof.relationships.label": "상사, 친구, 어르신 또는 낯선 사람",
  "features.clips.title": '"럭키비키"…? 그게 무슨 뜻이지?',
  "features.clips.description":
    "최애의 유행어부터 K-드라마 명대사까지 — 뜻과 유래, 어떤 상황에서 쓰는지 카드 한 장에 담았어요. 마음에 드는 밈이 있다면? 클립 틀고 억양까지 그대로 따라 해서, 친구들 사이에서 자연스럽게 써보세요.",
  "features.real-life.title": "너에게 진짜 필요한 것만, 팩으로",
  "features.real-life.description":
    "교과서 진도 말고, 지금 당신 취미에 필요한 것만 쏙 골라 담았어요.",
  "features.register.title": '"밥 먹자"는 한국어에서 한 문장으로 끝나지 않아요',
  "features.register.description":
    "친구, 선배, 최애, 나보다 나이 많은 사람 — 누구와 이야기하는지, 어떤 상황인지, 얼마나 가까운지에 따라 한국어로 하는 말은 전부 달라져요. 카카오톡 스타일 시뮬레이션에서 페르소나들과 대화해 보세요. 말투를 제대로 고르면 대화가 술술 이어지고, 어긋나면 상대의 반응이 바로 돌아와요. 실수는 여기서 마음껏 하세요 — 진짜 중요한 순간에는 자연스럽게 말할 수 있도록.",
  "features.earlyAccess": "얼리 액세스 신청",
  "visual.one.goodFortune": "행운",
  "visual.one.englishName": "원영의 영어 이름",
  "visual.one.definition": "작은 불편을 뜻밖의 행운으로 바꿔 생각하는 표현이에요.",
  "visual.one.example": "“카페 메뉴가 품절이라 갓 나온 걸 받았어 — 완전 럭키비키!”",
  "visual.one.confirm": "이해했어요 — 행운이네요!",
  "visual.one.bannerTitle": "한국의 최신 밈을 문 앞까지 배달해 드려요.",
  "visual.one.bannerDescription": "뜻과 유래를 쉽게 알아보세요.",
  "visual.one.likes": "좋아요 100+",
  "visual.one.instruction": "문장을 따라 말하고 저장하거나 넘겨 다음 영상을 보세요.",
  "visual.one.shadow": "따라 말하기 시작",
  "visual.two.loading": "레슨 불러오는 중",
  "visual.two.food.title": "주문은 어떻게 할까요?",
  "visual.two.food.prompt": "한국에서는 어떻게 주문할까요?",
  "visual.two.food.action": "레슨 시작",
  "visual.two.fansign.title": "팬사인회 연습",
  "visual.two.fansign.prompt": "최애에게 무슨 말을 할까요?",
  "visual.two.fansign.action": "연습 시작",
  "visual.two.school.title": "학교생활 기초",
  "visual.two.school.prompt": "첫날 준비됐나요?",
  "visual.two.school.action": "레슨 시작",
  "visual.three.demo": "오늘 정말 감사했어요",
  "visual.three.inputLabel": "연습할 의미",
  "visual.three.placeholder": "하고 싶은 말을 입력하세요",
  "visual.three.submitLabel": "관계별 한국어 표현 보기",
  "visual.three.friend.label": "친구",
  "visual.three.friend.tone": "편하게 반말로",
  "visual.three.elder.label": "연장자 교수님",
  "visual.three.elder.tone": "격식 있는 높임말",
  "visual.three.boss.label": "직장 상사",
  "visual.three.boss.tone": "정중하고 전문적으로",
  "pricing.kicker": "내 속도에 맞는 선택",
  "pricing.title": "지금 필요한 한국어부터 시작하세요.",
  "pricing.subtitle":
    "실제 영상을 반복하고, 일상 상황을 준비하며, 상대에 맞는 한국어 말투를 연습하세요.",
  "pricing.unit": "/월",
  "pricing.billing.monthly": "월간",
  "pricing.billing.annual": "연간",
  "pricing.billing.save": "20% 절약",
  "pricing.badge.popular": "가장 인기",
  "pricing.free.name": "무료",
  "pricing.free.description": "소수의 영상과 일상 표현으로 핵심 기능을 체험하세요.",
  "pricing.free.cta": "무료로 시작",
  "pricing.free.feature.clips": "선별된 이중 자막 영상",
  "pricing.free.feature.phrases": "표현 최대 20개 저장",
  "pricing.free.feature.register": "기본 말투 연습",
  "pricing.plus.name": "플러스",
  "pricing.plus.description": "영상, 실생활 상황, 관계별 한국어를 아우르는 매일의 습관을 만드세요.",
  "pricing.plus.cta": "플러스 시작",
  "pricing.plus.feature.unlimited": "무제한 영상 레슨",
  "pricing.plus.feature.situations": "전체 실생활 상황 라이브러리",
  "pricing.plus.feature.drills": "무제한 말투 훈련",
  "pricing.plus.feature.review": "나만의 표현 복습",
  "pricing.premium.name": "프리미엄",
  "pricing.premium.description":
    "더 깊은 연습과 새 도구 얼리 액세스로 완전한 학습 경험을 누리세요.",
  "pricing.premium.cta": "프리미엄 시작",
  "pricing.premium.feature.everything": "플러스의 모든 기능",
  "pricing.premium.feature.pronunciation": "발음 피드백",
  "pricing.premium.feature.practice": "맞춤형 연습 세트",
  "pricing.premium.feature.early-access": "새 기능 얼리 액세스",
  "pricing.footer": "구독은 자동 갱신됩니다. 언제든 취소할 수 있습니다.",
  "cta.badge": "당신의 K-라이프를 위해",
  "cta.title": "순간을 이해하고, 상황에 맞게 말하세요.",
  "cta.description":
    "이미 좋아하는 문화로 배우고, 영상과 일상 그리고 모든 관계에서 통하는 한국어를 연습하세요.",
  "cta.action": "얼리 액세스 신청",
  "cta.note.clips": "한 줄씩 반복 가능한 실제 영상",
  "cta.note.practice": "실생활과 관계 중심 연습",
  "footer.label": "K-zip 푸터",
  "footer.policy.label": "정책 링크",
  "footer.faq.label": "자주 묻는 질문",
  "footer.faq.heading": "자주 묻는 질문",
  "footer.faq.clips.question": "영상으로 무엇을 배울 수 있나요?",
  "footer.faq.clips.answer":
    "한국어와 내 언어를 나란히 보고, 자막을 반복 재생하며, 문맥 속 단어를 이해하고 자연스러운 표현을 저장해 복습할 수 있습니다.",
  "footer.faq.real-life.question": "K-드라마와 K-pop만 다루나요?",
  "footer.faq.real-life.answer":
    "아니요. 병원, 주민센터, 아르바이트 등 한국의 일상 상황에 필요한 한국어도 연습할 수 있습니다.",
  "footer.faq.register.question": "상대에 따라 다르게 말하는 법도 배울 수 있나요?",
  "footer.faq.register.answer":
    "네. 상사, 친한 친구, 어르신, 낯선 사람에게 같은 뜻을 다르게 말하며 자연스럽게 말투를 바꿀 때까지 연습할 수 있습니다.",
  "footer.privacy": "개인정보 처리방침",
  "footer.terms": "이용약관",
  "footer.copyright": "© 2026 K-zip. 모든 권리 보유.",
};

export const ar: Record<keyof typeof enUS, string> = {
  "nav.menu.open": "افتح القائمة",
  "nav.menu.close": "أغلق القائمة",
  "nav.menu.label": "قائمة الجوال",
  "document.title": "K-zip — Learn Korean through K-Culture",
  "locale.label": "اختر اللغة",
  "locale.ko-KR": "الكورية",
  "locale.en-US": "الإنجليزية",
  "locale.ar": "العربية",
  "locale.ja-JP": "اليابانية",
  "locale.vi-VN": "الفيتنامية",
  "locale.th-TH": "التايلاندية",
  "locale.zh-CN": "الصينية المبسطة",
  "locale.zh-TW": "الصينية التقليدية",
  brand: "K-zip",
  "nav.label": "التنقل الرئيسي",
  "nav.proof": "النتائج",
  "nav.pricing": "الأسعار",
  "nav.cta": "احصل على وصول مبكر",
  "hero.title": "تعلّم الكورية الكامنة وراء الثقافة.",
  "hero.description":
    "افهم النكات في المقاطع التي تحبها، وتعامل مع الحياة اليومية في كوريا، وتحدث بطبيعية مع كل من أمامك.",
  "hero.cta": "احصل على وصول مبكر",
  "hero.highlight.clips": "أعد تشغيل مقاطع حقيقية بترجمة مزدوجة",
  "hero.highlight.real-life": "تدرّب على الكورية لمواقف الحياة الواقعية",
  "hero.highlight.register": "غيّر كلماتك لتناسب كل علاقة",
  "hero.visual.feed": "موجز قصير يعيد تشغيل مقطع ميم كوري مع طريقة نطقه.",
  "hero.visual.situations": "بطاقة درس تتنقل بين مواقف كورية يومية.",
  "proof.title": "لغة واحدة، لكل جانب من حياتك الكورية.",
  "proof.clips.value": "لغتان",
  "proof.clips.label": "ترجمتان جنبًا إلى جنب في كل مقطع",
  "proof.situations.value": "حياة واقعية",
  "proof.situations.label": "تدرّب للمواقف التي ستواجهها فعلًا",
  "proof.relationships.value": "4 مستويات",
  "proof.relationships.label": "مدير أو صديق أو كبير سن أو غريب",
  "features.clips.title": "«لاكي فيكي»...؟ ماذا يعني ذلك أصلًا؟",
  "features.clips.description":
    "من عبارات نجمك المفضل الرائجة إلى أشهر جمل الدراما الكورية — معناها وأصلها ومتى تستخدمها، كلها في بطاقة واحدة. وجدت ميمًا أعجبك؟ شغّل المقطع، أتقن النبرة، واستخدمه مع أصدقائك كأنك من أهل البلد.",
  "features.real-life.title": "ما تحتاجه فعلًا — في حزمة واحدة",
  "features.real-life.description": "لا فصول من الكتب. فقط ما تحتاجه هوايتك فعلًا، مختار بعناية.",
  "features.register.title": "«هيا نأكل» ليست جملة واحدة في الكورية",
  "features.register.description":
    "صديقك، شخص أكبر منك في الدراسة أو العمل، نجمك المفضل، أو شخص أكبر سنًا — من تخاطب، وما الموقف، ومدى قربكما: في الكورية، كل ذلك يغيّر ما تقوله. تحدث مع شخصيات في محاكاة بأسلوب KakaoTalk: اضبط النبرة فتنساب المحادثة، وأخطئ فيها لترى ردود أفعالهم. ارتكب كل أخطائك هنا — كي تبدو طبيعيًا عندما يحين الوقت المهم.",
  "features.earlyAccess": "احصل على وصول مبكر",
  "visual.one.goodFortune": "حظ سعيد",
  "visual.one.englishName": "اسم وونيونغ بالإنجليزية",
  "visual.one.definition": "حوّل الإزعاج الصغير إلى حظ غير متوقع.",
  "visual.one.example": "نفد الطلب، فحصلت على دفعة طازجة — يا له من حظ!",
  "visual.one.confirm": "فهمت — أنا محظوظ!",
  "visual.one.bannerTitle": "أحدث ميمات كوريا، تصل حتى بابك.",
  "visual.one.bannerDescription": "المعنى والأصل ببساطة.",
  "visual.one.likes": "+100 إعجاب",
  "visual.one.instruction": "اضغط لتكرر الجملة أو تحفظها أو انتقل للمقطع التالي.",
  "visual.one.shadow": "ابدأ التكرار",
  "visual.two.loading": "جارٍ تحميل الدرس",
  "visual.two.food.title": "كيف تطلب؟",
  "visual.two.food.prompt": "كيف تطلب في كوريا؟",
  "visual.two.food.action": "ابدأ الدرس",
  "visual.two.fansign.title": "تدرّب على لقاء المعجبين",
  "visual.two.fansign.prompt": "ماذا ستقول لنجمك المفضل؟",
  "visual.two.fansign.action": "ابدأ التدريب",
  "visual.two.school.title": "أساسيات الحياة المدرسية",
  "visual.two.school.prompt": "هل أنت مستعد ليومك الأول؟",
  "visual.two.school.action": "ابدأ الدرس",
  "visual.three.demo": "شكرًا جزيلًا على اليوم",
  "visual.three.inputLabel": "المعنى المراد التدرب عليه",
  "visual.three.placeholder": "اكتب ما تريد قوله",
  "visual.three.submitLabel": "اعرض التعبيرات الكورية حسب العلاقة",
  "visual.three.friend.label": "صديق",
  "visual.three.friend.tone": "كورية غير رسمية (بانمال)",
  "visual.three.elder.label": "أستاذ أكبر سنًا",
  "visual.three.elder.tone": "كورية رسمية تشريفية",
  "visual.three.boss.label": "مدير العمل",
  "visual.three.boss.tone": "مهذب ومهني",
  "pricing.kicker": "اختر وتيرتك",
  "pricing.title": "ابدأ بالكورية التي تحتاجها الآن.",
  "pricing.subtitle":
    "أعد تشغيل مقاطع حقيقية، واستعد للمواقف اليومية، وتدرّب على المستوى المناسب من الكورية لكل شخص.",
  "pricing.unit": "/شهر",
  "pricing.billing.monthly": "شهري",
  "pricing.billing.annual": "سنوي",
  "pricing.billing.save": "وفّر 20%",
  "pricing.badge.popular": "الأكثر رواجًا",
  "pricing.free.name": "مجاني",
  "pricing.free.description": "جرّب الأساسيات مع مجموعة صغيرة من المقاطع والعبارات اليومية.",
  "pricing.free.cta": "ابدأ مجانًا",
  "pricing.free.feature.clips": "مقاطع مختارة بترجمة مزدوجة",
  "pricing.free.feature.phrases": "احفظ حتى 20 عبارة",
  "pricing.free.feature.register": "تدريب أساسي على مستويات الكلام",
  "pricing.plus.name": "بلس",
  "pricing.plus.description":
    "ابنِ عادة يومية عبر المقاطع ومواقف الحياة الواقعية والكورية المناسبة للعلاقات.",
  "pricing.plus.cta": "ابدأ بلس",
  "pricing.plus.feature.unlimited": "دروس مقاطع غير محدودة",
  "pricing.plus.feature.situations": "مكتبة كاملة لمواقف الحياة",
  "pricing.plus.feature.drills": "تدريبات مستويات غير محدودة",
  "pricing.plus.feature.review": "مراجعة شخصية للعبارات",
  "pricing.premium.name": "بريميوم",
  "pricing.premium.description":
    "احصل على تجربة التعلم الكاملة مع تدريب أعمق ووصول مبكر إلى الأدوات الجديدة.",
  "pricing.premium.cta": "اختر بريميوم",
  "pricing.premium.feature.everything": "كل ما في بلس",
  "pricing.premium.feature.pronunciation": "ملاحظات على النطق",
  "pricing.premium.feature.practice": "مجموعات تدريب مخصصة",
  "pricing.premium.feature.early-access": "وصول مبكر للميزات الجديدة",
  "pricing.footer": "تتجدد الاشتراكات تلقائيًا. يمكنك الإلغاء في أي وقت.",
  "cta.badge": "مصمم لحياتك الكورية",
  "cta.title": "افهم اللحظة، وقل ما يناسبها.",
  "cta.description":
    "تعلّم من الثقافة التي تحبها بالفعل، ثم تدرّب على الكورية المناسبة للمقاطع والحياة اليومية وكل علاقة.",
  "cta.action": "احصل على وصول مبكر",
  "cta.note.clips": "مقاطع حقيقية قابلة للإعادة سطرًا بسطر",
  "cta.note.practice": "تدريب للحياة الواقعية والعلاقات",
  "footer.label": "تذييل K-zip",
  "footer.policy.label": "روابط السياسات",
  "footer.faq.label": "الأسئلة الشائعة",
  "footer.faq.heading": "الأسئلة الشائعة",
  "footer.faq.clips.question": "ماذا يمكنني أن أتعلم من مقطع؟",
  "footer.faq.clips.answer":
    "يمكنك مشاهدة الكورية ولغتك جنبًا إلى جنب، وإعادة أي ترجمة، وفهم الكلمات في سياقها، وحفظ العبارات الطبيعية للمراجعة.",
  "footer.faq.real-life.question": "هل هذا مخصص للدراما الكورية وK-pop فقط؟",
  "footer.faq.real-life.answer":
    "لا. يمكنك أيضًا ممارسة الكورية للمواقف اليومية في كوريا، ومنها المستشفيات والمكاتب الحكومية والعمل الجزئي.",
  "footer.faq.register.question": "هل سيساعدني على التحدث بشكل مختلف مع أشخاص مختلفين؟",
  "footer.faq.register.answer":
    "نعم. يمكنك ممارسة المعنى نفسه مع مدير أو صديق مقرّب أو كبير سن أو غريب حتى يصبح تغيير مستوى الكلام طبيعيًا.",
  "footer.privacy": "الخصوصية",
  "footer.terms": "الشروط",
  "footer.copyright": "© 2026 K-zip. جميع الحقوق محفوظة.",
};

export const jaJP = {
  ...enUS,
  "nav.menu.open": "メニューを開く",
  "nav.menu.close": "メニューを閉じる",
  "nav.menu.label": "モバイルメニュー",
  "document.title": "K-zip — Learn Korean through K-Culture",
  "locale.label": "言語を選択",
  "locale.ko-KR": "韓国語",
  "locale.en-US": "英語",
  "locale.ar": "アラビア語",
  "locale.ja-JP": "日本語",
  "locale.vi-VN": "ベトナム語",
  "locale.th-TH": "タイ語",
  "locale.zh-CN": "中国語（簡体字）",
  "locale.zh-TW": "中国語（繁体字）",
  brand: "K-zip",
  "nav.label": "メインナビゲーション",
  "nav.proof": "学習効果",
  "nav.pricing": "料金プラン",
  "nav.cta": "早期アクセスに登録",
  "hero.title": "カルチャーの奥にある、本当の韓国語を学ぼう。",
  "hero.description":
    "好きな動画のジョークを理解し、韓国での日常に対応し、目の前の相手に合わせて自然に話せるようになりましょう。",
  "hero.cta": "早期アクセスに登録",
  "hero.highlight.clips": "実際の動画を2言語字幕でリプレイ",
  "hero.highlight.real-life": "日常の場面で使う韓国語を練習",
  "hero.highlight.register": "相手との関係に合わせて表現を変更",
  "hero.visual.feed": "ショート動画のフィードが韓国語ミームを発音付きで再生する様子。",
  "hero.visual.situations": "日常の韓国語シチュエーションを順に見せるレッスンカード。",
  "proof.title": "ひとつの言語で、Kライフのすべてを。",
  "proof.clips.value": "2言語",
  "proof.clips.label": "すべての動画で字幕を並べて表示",
  "proof.situations.value": "リアルな日常",
  "proof.situations.label": "実際に出会う場面を練習",
  "proof.relationships.value": "4つの話し方",
  "proof.relationships.label": "上司、友人、年長者、初対面の人",
  "features.clips.title": "「ラッキービッキー」…？それってどういう意味？",
  "features.clips.description":
    "推しの決めぜりふからKドラマの名セリフまで——意味や由来、どんなときに使うのかを1枚のカードに。お気に入りのミームを見つけたら、クリップを再生してイントネーションまでまねし、友達との会話でネイティブのように使ってみよう。",
  "features.real-life.title": "本当に必要なものだけ、ひとつのパックに",
  "features.real-life.description":
    "教科書の章立てはなし。今のあなたの「好き」に本当に必要なものだけを厳選しました。",
  "features.register.title": "「ご飯食べよう」は、韓国語では一通りじゃない",
  "features.register.description":
    "友達、先輩、推し、年上の人——誰と話すのか、どんな状況か、どれくらい親しいかによって、韓国語では言い方がすべて変わります。KakaoTalk風シミュレーションでペルソナとチャット。口調が合えば会話はスムーズに進み、外せば相手の反応が返ってきます。失敗はここで全部しておこう——本番では自然に話せるように。",
  "features.earlyAccess": "早期アクセスに登録",
  "visual.one.goodFortune": "幸運",
  "visual.one.englishName": "ウォニョンの英語名",
  "visual.one.definition": "小さな不便を思いがけない幸運として捉え直す表現です。",
  "visual.one.example": "「売り切れだったから出来たてをもらえた。完全にラッキービッキー！」",
  "visual.one.confirm": "わかった — ラッキー！",
  "visual.one.bannerTitle": "韓国の最新ミームを、あなたのもとへ。",
  "visual.one.bannerDescription": "意味と由来をわかりやすく。",
  "visual.one.likes": "いいね100+",
  "visual.one.instruction": "タップして復唱・保存、またはスワイプして次の動画へ。",
  "visual.one.shadow": "シャドーイング開始",
  "visual.two.loading": "レッスンを読み込み中",
  "visual.two.food.title": "注文のしかたは？",
  "visual.two.food.prompt": "韓国ではどう注文する？",
  "visual.two.food.action": "レッスン開始",
  "visual.two.fansign.title": "サイン会を練習",
  "visual.two.fansign.prompt": "推しに何を伝える？",
  "visual.two.fansign.action": "練習開始",
  "visual.two.school.title": "学校生活の基本",
  "visual.two.school.prompt": "初日の準備はできた？",
  "visual.two.school.action": "レッスン開始",
  "visual.three.demo": "今日は本当にありがとうございました",
  "visual.three.inputLabel": "練習する意味",
  "visual.three.placeholder": "言いたいことを入力してください",
  "visual.three.submitLabel": "関係別の韓国語表現を表示",
  "visual.three.friend.label": "友達",
  "visual.three.friend.tone": "タメ口でカジュアルに",
  "visual.three.elder.label": "年長の教授",
  "visual.three.elder.tone": "格式ある敬語",
  "visual.three.boss.label": "職場の上司",
  "visual.three.boss.tone": "丁寧でプロらしく",
  "pricing.kicker": "自分のペースを選ぶ",
  "pricing.title": "今必要な韓国語から始めよう。",
  "pricing.subtitle":
    "実際の動画を繰り返し、日常の場面に備え、相手ごとに適切な韓国語を練習しましょう。",
  "pricing.unit": "/月",
  "pricing.billing.monthly": "月払い",
  "pricing.billing.annual": "年払い",
  "pricing.billing.save": "20%お得",
  "pricing.badge.popular": "人気",
  "pricing.free.name": "無料",
  "pricing.free.description": "少数の動画と日常表現で基本機能を試せます。",
  "pricing.free.cta": "無料で始める",
  "pricing.free.feature.clips": "厳選された2言語字幕動画",
  "pricing.free.feature.phrases": "表現を20個まで保存",
  "pricing.free.feature.register": "基本的な話し方の練習",
  "pricing.plus.name": "Plus",
  "pricing.plus.description": "動画、実生活の場面、相手別の韓国語を毎日の習慣に。",
  "pricing.plus.cta": "Plusを始める",
  "pricing.plus.feature.unlimited": "動画レッスン無制限",
  "pricing.plus.feature.situations": "実生活シーンの全ライブラリ",
  "pricing.plus.feature.drills": "話し方ドリル無制限",
  "pricing.plus.feature.review": "自分専用の表現復習",
  "pricing.premium.name": "Premium",
  "pricing.premium.description": "より深い練習と新機能への早期アクセスを含む、完全な学習体験。",
  "pricing.premium.cta": "Premiumを始める",
  "pricing.premium.feature.everything": "Plusの全機能",
  "pricing.premium.feature.pronunciation": "発音フィードバック",
  "pricing.premium.feature.practice": "パーソナライズ練習セット",
  "pricing.premium.feature.early-access": "新機能への早期アクセス",
  "pricing.footer": "プランは自動更新されます。いつでも解約できます。",
  "cta.badge": "あなたのKライフのために",
  "cta.title": "その瞬間を理解して、場面に合う言葉を。",
  "cta.description":
    "すでに好きなカルチャーから学び、動画、日常、あらゆる関係で通じる韓国語を練習しましょう。",
  "cta.action": "早期アクセスに登録",
  "cta.note.clips": "実際の動画を一行ずつリプレイ",
  "cta.note.practice": "実生活と人間関係に基づく練習",
  "footer.label": "K-zipフッター",
  "footer.policy.label": "ポリシーリンク",
  "footer.faq.label": "よくある質問",
  "footer.faq.heading": "よくある質問",
  "footer.faq.clips.question": "動画から何を学べますか？",
  "footer.faq.clips.answer":
    "韓国語と自分の言語を並べて表示し、字幕を再生し、文脈で単語を理解して、自然な表現を保存・復習できます。",
  "footer.faq.real-life.question": "KドラマとK-pop専用ですか？",
  "footer.faq.real-life.answer":
    "いいえ。病院、役所、アルバイトなど、韓国での日常に必要な韓国語も練習できます。",
  "footer.faq.register.question": "相手によって話し方を変える練習もできますか？",
  "footer.faq.register.answer":
    "はい。上司、親しい友人、年長者、初対面の人に同じ意味を伝え、自然に話し方を切り替えられるまで練習できます。",
  "footer.privacy": "プライバシー",
  "footer.terms": "利用規約",
  "footer.copyright": "© 2026 K-zip. All rights reserved.",
} satisfies Record<keyof typeof enUS, string>;

export const viVN = {
  ...enUS,
  "nav.menu.open": "Mở menu",
  "nav.menu.close": "Đóng menu",
  "nav.menu.label": "Menu di động",
  "document.title": "K-zip — Learn Korean through K-Culture",
  "locale.label": "Chọn ngôn ngữ",
  "locale.ko-KR": "Tiếng Hàn",
  "locale.en-US": "Tiếng Anh",
  "locale.ar": "Tiếng Ả Rập",
  "locale.ja-JP": "Tiếng Nhật",
  "locale.vi-VN": "Tiếng Việt",
  "locale.th-TH": "Tiếng Thái",
  "locale.zh-CN": "Tiếng Trung (Giản thể)",
  "locale.zh-TW": "Tiếng Trung (Phồn thể)",
  brand: "K-zip",
  "nav.label": "Điều hướng chính",
  "nav.proof": "Hiệu quả",
  "nav.pricing": "Bảng giá",
  "nav.cta": "Đăng ký truy cập sớm",
  "hero.title": "Học tiếng Hàn đằng sau văn hóa.",
  "hero.description":
    "Hiểu những câu đùa trong video bạn yêu thích, xử lý cuộc sống thực tại Hàn Quốc và nói tự nhiên với bất kỳ ai trước mặt.",
  "hero.cta": "Đăng ký truy cập sớm",
  "hero.highlight.clips": "Phát lại video thật với phụ đề song ngữ",
  "hero.highlight.real-life": "Luyện tiếng Hàn cho tình huống đời thực",
  "hero.highlight.register": "Đổi cách nói theo từng mối quan hệ",
  "hero.visual.feed": "Nguồn cấp video ngắn phát lại clip meme tiếng Hàn kèm cách phát âm.",
  "hero.visual.situations": "Thẻ bài học lần lượt hiển thị các tình huống tiếng Hàn thường ngày.",
  "proof.title": "Một ngôn ngữ. Mọi khía cạnh của K-life.",
  "proof.clips.value": "2 ngôn ngữ",
  "proof.clips.label": "Phụ đề song song trong mọi video",
  "proof.situations.value": "Đời thực",
  "proof.situations.label": "Luyện cho những tình huống bạn thực sự gặp",
  "proof.relationships.value": "4 cách nói",
  "proof.relationships.label": "Sếp, bạn bè, người lớn tuổi hoặc người lạ",
  "features.clips.title": "“Lucky Vicky”...? Rốt cuộc nghĩa là gì?",
  "features.clips.description":
    "Từ câu cửa miệng của bias đến những câu thoại kinh điển trong K-drama — ý nghĩa, nguồn gốc và dùng khi nào, tất cả gói gọn trong một thẻ. Tìm được meme ưng ý? Mở clip, bắt đúng ngữ điệu rồi dùng với bạn bè thật tự nhiên như người bản xứ.",
  "features.real-life.title": "Đúng thứ bạn thật sự cần — gói gọn trong một bộ",
  "features.real-life.description":
    "Không học theo chương sách giáo khoa. Chỉ những gì sở thích của bạn thực sự cần, được chọn lọc kỹ.",
  "features.register.title": "“Đi ăn thôi” không chỉ có một cách nói trong tiếng Hàn",
  "features.register.description":
    "Bạn bè, tiền bối, bias, người lớn tuổi hơn — bạn đang nói với ai, trong hoàn cảnh nào, thân thiết đến đâu: trong tiếng Hàn, tất cả đều làm thay đổi cách bạn nói. Trò chuyện với các nhân vật trong mô phỏng kiểu KakaoTalk: đúng giọng điệu thì cuộc trò chuyện trôi chảy, sai một nhịp thì xem họ phản ứng. Cứ mắc hết lỗi ở đây — để khi thật sự cần, bạn nói thật tự nhiên.",
  "features.earlyAccess": "Đăng ký truy cập sớm",
  "visual.one.goodFortune": "may mắn",
  "visual.one.englishName": "tên tiếng Anh của Wonyoung",
  "visual.one.definition": "Biến một bất tiện nhỏ thành vận may bất ngờ.",
  "visual.one.example": "“Quán hết món nên mình được mẻ mới — đúng là Lucky Vicky!”",
  "visual.one.confirm": "Hiểu rồi — may quá!",
  "visual.one.bannerTitle": "Meme mới nhất từ Hàn Quốc, giao tận cửa nhà bạn.",
  "visual.one.bannerDescription": "Ý nghĩa và nguồn gốc thật dễ hiểu.",
  "visual.one.likes": "100+ lượt thích",
  "visual.one.instruction": "Nhấn để nói theo, lưu lại hoặc vuốt sang video tiếp theo.",
  "visual.one.shadow": "Bắt đầu nói theo",
  "visual.two.loading": "Đang tải bài học",
  "visual.two.food.title": "Gọi món thế nào?",
  "visual.two.food.prompt": "Bạn gọi món ở Hàn Quốc ra sao?",
  "visual.two.food.action": "Bắt đầu bài học",
  "visual.two.fansign.title": "Luyện tập fansign",
  "visual.two.fansign.prompt": "Bạn sẽ nói gì với thần tượng?",
  "visual.two.fansign.action": "Bắt đầu luyện tập",
  "visual.two.school.title": "Cơ bản về trường học",
  "visual.two.school.prompt": "Sẵn sàng cho ngày đầu chưa?",
  "visual.two.school.action": "Bắt đầu bài học",
  "visual.three.demo": "Cảm ơn bạn rất nhiều vì hôm nay",
  "visual.three.inputLabel": "Ý nghĩa cần luyện tập",
  "visual.three.placeholder": "Nhập điều bạn muốn nói",
  "visual.three.submitLabel": "Xem cách diễn đạt theo từng mối quan hệ",
  "visual.three.friend.label": "Bạn bè",
  "visual.three.friend.tone": "Thân mật, không kính ngữ",
  "visual.three.elder.label": "Giáo sư lớn tuổi",
  "visual.three.elder.tone": "Kính ngữ trang trọng",
  "visual.three.boss.label": "Sếp nơi làm việc",
  "visual.three.boss.tone": "Lịch sự và chuyên nghiệp",
  "pricing.kicker": "Chọn nhịp học của bạn",
  "pricing.title": "Bắt đầu với tiếng Hàn bạn cần ngay lúc này.",
  "pricing.subtitle":
    "Phát lại video thật, chuẩn bị cho tình huống hằng ngày và luyện đúng cách nói với từng người.",
  "pricing.unit": "/tháng",
  "pricing.billing.monthly": "Hàng tháng",
  "pricing.billing.annual": "Hàng năm",
  "pricing.billing.save": "Tiết kiệm 20%",
  "pricing.badge.popular": "Phổ biến nhất",
  "pricing.free.name": "Miễn phí",
  "pricing.free.description": "Thử những tính năng thiết yếu với một số video và cụm từ hằng ngày.",
  "pricing.free.cta": "Bắt đầu miễn phí",
  "pricing.free.feature.clips": "Video phụ đề song ngữ chọn lọc",
  "pricing.free.feature.phrases": "Lưu tối đa 20 cụm từ",
  "pricing.free.feature.register": "Luyện cấp độ nói cơ bản",
  "pricing.plus.name": "Plus",
  "pricing.plus.description":
    "Tạo thói quen hằng ngày với video, tình huống đời thực và tiếng Hàn theo mối quan hệ.",
  "pricing.plus.cta": "Bắt đầu Plus",
  "pricing.plus.feature.unlimited": "Bài học video không giới hạn",
  "pricing.plus.feature.situations": "Toàn bộ thư viện tình huống đời thực",
  "pricing.plus.feature.drills": "Bài luyện cách nói không giới hạn",
  "pricing.plus.feature.review": "Ôn tập cụm từ cá nhân",
  "pricing.premium.name": "Premium",
  "pricing.premium.description":
    "Trải nghiệm học đầy đủ với luyện tập chuyên sâu và quyền truy cập sớm công cụ mới.",
  "pricing.premium.cta": "Chọn Premium",
  "pricing.premium.feature.everything": "Mọi tính năng trong Plus",
  "pricing.premium.feature.pronunciation": "Phản hồi phát âm",
  "pricing.premium.feature.practice": "Bộ bài luyện cá nhân hóa",
  "pricing.premium.feature.early-access": "Truy cập sớm tính năng mới",
  "pricing.footer": "Gói tự động gia hạn. Hủy bất cứ lúc nào.",
  "cta.badge": "Dành cho K-life của bạn",
  "cta.title": "Hiểu khoảnh khắc. Nói điều phù hợp.",
  "cta.description":
    "Học từ văn hóa bạn đã yêu thích, rồi luyện tiếng Hàn phù hợp trong video, đời sống hằng ngày và mọi mối quan hệ.",
  "cta.action": "Đăng ký truy cập sớm",
  "cta.note.clips": "Video thật, phát lại từng dòng",
  "cta.note.practice": "Luyện theo đời thực và mối quan hệ",
  "footer.label": "Chân trang K-zip",
  "footer.policy.label": "Liên kết chính sách",
  "footer.faq.label": "Câu hỏi thường gặp",
  "footer.faq.heading": "Câu hỏi thường gặp",
  "footer.faq.clips.question": "Tôi có thể học gì từ một video?",
  "footer.faq.clips.answer":
    "Bạn có thể xem tiếng Hàn và ngôn ngữ của mình cạnh nhau, phát lại phụ đề, hiểu từ trong ngữ cảnh và lưu cụm từ tự nhiên để ôn tập.",
  "footer.faq.real-life.question": "Ứng dụng chỉ dành cho K-drama và K-pop?",
  "footer.faq.real-life.answer":
    "Không. Bạn cũng có thể luyện tiếng Hàn cho tình huống hằng ngày tại Hàn Quốc như bệnh viện, văn phòng hành chính và việc làm thêm.",
  "footer.faq.register.question": "Ứng dụng có giúp tôi nói khác nhau với từng người không?",
  "footer.faq.register.answer":
    "Có. Bạn có thể luyện cùng một ý với sếp, bạn thân, người lớn tuổi hoặc người lạ cho đến khi chuyển cấp độ nói thật tự nhiên.",
  "footer.privacy": "Quyền riêng tư",
  "footer.terms": "Điều khoản",
  "footer.copyright": "© 2026 K-zip. Bảo lưu mọi quyền.",
} satisfies Record<keyof typeof enUS, string>;

export const thTH = {
  ...enUS,
  "nav.menu.open": "เปิดเมนู",
  "nav.menu.close": "ปิดเมนู",
  "nav.menu.label": "เมนูบนมือถือ",
  "document.title": "K-zip — Learn Korean through K-Culture",
  "locale.label": "เลือกภาษา",
  "locale.ko-KR": "เกาหลี",
  "locale.en-US": "อังกฤษ",
  "locale.ar": "อาหรับ",
  "locale.ja-JP": "ญี่ปุ่น",
  "locale.vi-VN": "เวียดนาม",
  "locale.th-TH": "ไทย",
  "locale.zh-CN": "จีนตัวย่อ",
  "locale.zh-TW": "จีนตัวเต็ม",
  brand: "K-zip",
  "nav.label": "เมนูหลัก",
  "nav.proof": "ผลลัพธ์",
  "nav.pricing": "ราคา",
  "nav.cta": "สมัคร Early Access",
  "hero.title": "เรียนภาษาเกาหลีที่อยู่เบื้องหลังวัฒนธรรม",
  "hero.description":
    "เข้าใจมุกในคลิปที่คุณชอบ รับมือชีวิตจริงในเกาหลี และพูดอย่างเป็นธรรมชาติกับทุกคนตรงหน้า",
  "hero.cta": "สมัคร Early Access",
  "hero.highlight.clips": "เล่นคลิปจริงซ้ำพร้อมคำบรรยายสองภาษา",
  "hero.highlight.real-life": "ฝึกภาษาเกาหลีสำหรับชีวิตจริง",
  "hero.highlight.register": "ปรับคำพูดให้เหมาะกับทุกความสัมพันธ์",
  "hero.visual.feed": "ฟีดวิดีโอสั้นที่เล่นคลิปมีมภาษาเกาหลีพร้อมคำอ่าน。",
  "hero.visual.situations": "การ์ดบทเรียนที่สลับแสดงสถานการณ์ภาษาเกาหลีในชีวิตประจำวัน",
  "proof.title": "หนึ่งภาษา ครบทุกด้านของ K-life",
  "proof.clips.value": "2 ภาษา",
  "proof.clips.label": "คำบรรยายสองภาษาในทุกคลิป",
  "proof.situations.value": "ชีวิตจริง",
  "proof.situations.label": "ฝึกสถานการณ์ที่คุณจะเจอจริง",
  "proof.relationships.value": "4 ระดับภาษา",
  "proof.relationships.label": "หัวหน้า เพื่อน ผู้ใหญ่ หรือคนแปลกหน้า",
  "features.clips.title": "“Lucky Vicky”...? ตกลงหมายความว่าอะไรกันแน่?",
  "features.clips.description":
    "ตั้งแต่วลีติดปากของเมนคุณไปจนถึงประโยคเด็ดจาก K-drama — ทั้งความหมาย ที่มา และใช้ตอนไหน รวมไว้ในการ์ดเดียว เจอมีมที่ชอบแล้วใช่ไหม? เปิดคลิป ฝึกน้ำเสียงให้เป๊ะ แล้วเอาไปใช้กับเพื่อนอย่างเป็นธรรมชาติเหมือนคนเกาหลี",
  "features.real-life.title": "สิ่งที่คุณต้องใช้จริง ๆ — รวมไว้เป็นแพ็ก",
  "features.real-life.description":
    "ไม่ต้องเรียนตามบทในตำรา คัดมาเฉพาะสิ่งที่งานอดิเรกของคุณต้องใช้จริง ๆ",
  "features.register.title": "“ไปกินข้าวกัน” ไม่ได้มีแค่ประโยคเดียวในภาษาเกาหลี",
  "features.register.description":
    "เพื่อน รุ่นพี่ เมนของคุณ หรือคนที่อายุมากกว่า — คุณกำลังคุยกับใคร อยู่ในสถานการณ์ไหน และสนิทกันแค่ไหน ทุกอย่างเปลี่ยนสิ่งที่คุณพูดในภาษาเกาหลี ลองแชตกับตัวละครจำลองสไตล์ KakaoTalk: ใช้น้ำเสียงถูก บทสนทนาก็ไหลลื่น ใช้ผิด แล้วดูว่าพวกเขาจะตอบสนองอย่างไร ลองผิดให้เต็มที่ที่นี่ — เพื่อให้เวลาสำคัญมาถึง คุณจะพูดได้อย่างเป็นธรรมชาติ",
  "features.earlyAccess": "สมัคร Early Access",
  "visual.one.goodFortune": "โชคดี",
  "visual.one.englishName": "ชื่อภาษาอังกฤษของวอนยอง",
  "visual.one.definition": "มองความไม่สะดวกเล็กน้อยให้เป็นโชคดีที่คาดไม่ถึง",
  "visual.one.example": "“ของหมดเลยได้ของทำใหม่ — Lucky Vicky สุด ๆ!”",
  "visual.one.confirm": "เข้าใจแล้ว — โชคดีจัง!",
  "visual.one.bannerTitle": "มีมสดใหม่ล่าสุดจากเกาหลี ส่งตรงถึงหน้าประตูคุณ",
  "visual.one.bannerDescription": "เข้าใจความหมายและที่มาได้ง่าย ๆ",
  "visual.one.likes": "ถูกใจ 100+",
  "visual.one.instruction": "แตะเพื่อพูดตาม บันทึก หรือปัดไปคลิปถัดไป",
  "visual.one.shadow": "เริ่มพูดตาม",
  "visual.two.loading": "กำลังโหลดบทเรียน",
  "visual.two.food.title": "สั่งอาหารอย่างไร?",
  "visual.two.food.prompt": "ที่เกาหลีสั่งอาหารอย่างไร?",
  "visual.two.food.action": "เริ่มบทเรียน",
  "visual.two.fansign.title": "ฝึกงานแฟนไซน์",
  "visual.two.fansign.prompt": "จะพูดอะไรกับเมนของคุณ?",
  "visual.two.fansign.action": "เริ่มฝึก",
  "visual.two.school.title": "พื้นฐานชีวิตในโรงเรียน",
  "visual.two.school.prompt": "พร้อมสำหรับวันแรกหรือยัง?",
  "visual.two.school.action": "เริ่มบทเรียน",
  "visual.three.demo": "ขอบคุณมากสำหรับวันนี้",
  "visual.three.inputLabel": "ความหมายที่ต้องการฝึก",
  "visual.three.placeholder": "พิมพ์สิ่งที่คุณอยากพูด",
  "visual.three.submitLabel": "ดูสำนวนเกาหลีตามความสัมพันธ์",
  "visual.three.friend.label": "เพื่อน",
  "visual.three.friend.tone": "ภาษาลำลอง ไม่ใช้คำยกย่อง",
  "visual.three.elder.label": "อาจารย์อาวุโส",
  "visual.three.elder.tone": "ภาษาเกาหลีแบบยกย่องเป็นทางการ",
  "visual.three.boss.label": "หัวหน้างาน",
  "visual.three.boss.tone": "สุภาพและเป็นมืออาชีพ",
  "pricing.kicker": "เลือกจังหวะของคุณ",
  "pricing.title": "เริ่มจากภาษาเกาหลีที่คุณต้องใช้ตอนนี้",
  "pricing.subtitle":
    "เล่นคลิปจริงซ้ำ เตรียมพร้อมสำหรับสถานการณ์ประจำวัน และฝึกภาษาเกาหลีระดับที่เหมาะกับแต่ละคน",
  "pricing.unit": "/เดือน",
  "pricing.billing.monthly": "รายเดือน",
  "pricing.billing.annual": "รายปี",
  "pricing.billing.save": "ประหยัด 20%",
  "pricing.badge.popular": "ยอดนิยม",
  "pricing.free.name": "ฟรี",
  "pricing.free.description": "ทดลองฟีเจอร์หลักด้วยคลิปและวลีในชีวิตประจำวันจำนวนหนึ่ง",
  "pricing.free.cta": "เริ่มฟรี",
  "pricing.free.feature.clips": "คลิปคำบรรยายสองภาษาที่คัดสรร",
  "pricing.free.feature.phrases": "บันทึกได้สูงสุด 20 วลี",
  "pricing.free.feature.register": "ฝึกระดับภาษาพื้นฐาน",
  "pricing.plus.name": "Plus",
  "pricing.plus.description":
    "สร้างนิสัยประจำวันจากคลิป สถานการณ์จริง และภาษาเกาหลีตามความสัมพันธ์",
  "pricing.plus.cta": "เริ่ม Plus",
  "pricing.plus.feature.unlimited": "บทเรียนจากคลิปไม่จำกัด",
  "pricing.plus.feature.situations": "คลังสถานการณ์ชีวิตจริงทั้งหมด",
  "pricing.plus.feature.drills": "แบบฝึกระดับภาษาไม่จำกัด",
  "pricing.plus.feature.review": "ทบทวนวลีส่วนตัว",
  "pricing.premium.name": "Premium",
  "pricing.premium.description":
    "รับประสบการณ์เรียนเต็มรูปแบบพร้อมการฝึกที่ลึกขึ้นและสิทธิ์ใช้เครื่องมือใหม่ก่อนใคร",
  "pricing.premium.cta": "เลือก Premium",
  "pricing.premium.feature.everything": "ทุกอย่างใน Plus",
  "pricing.premium.feature.pronunciation": "คำแนะนำการออกเสียง",
  "pricing.premium.feature.practice": "ชุดฝึกเฉพาะบุคคล",
  "pricing.premium.feature.early-access": "เข้าถึงฟีเจอร์ใหม่ก่อนใคร",
  "pricing.footer": "แพ็กเกจต่ออายุอัตโนมัติ ยกเลิกได้ทุกเมื่อ",
  "cta.badge": "สร้างมาเพื่อ K-life ของคุณ",
  "cta.title": "เข้าใจช่วงเวลา แล้วพูดให้เหมาะ",
  "cta.description":
    "เรียนจากวัฒนธรรมที่คุณรัก แล้วฝึกภาษาเกาหลีที่ใช้ได้ในคลิป ชีวิตประจำวัน และทุกความสัมพันธ์",
  "cta.action": "สมัคร Early Access",
  "cta.note.clips": "คลิปจริง เล่นซ้ำได้ทีละบรรทัด",
  "cta.note.practice": "ฝึกจากชีวิตจริงและความสัมพันธ์",
  "footer.label": "ส่วนท้าย K-zip",
  "footer.policy.label": "ลิงก์นโยบาย",
  "footer.faq.label": "คำถามที่พบบ่อย",
  "footer.faq.heading": "คำถามที่พบบ่อย",
  "footer.faq.clips.question": "ฉันเรียนอะไรจากคลิปได้บ้าง?",
  "footer.faq.clips.answer":
    "คุณดูภาษาเกาหลีคู่กับภาษาของคุณ เล่นคำบรรยายซ้ำ เข้าใจคำในบริบท และบันทึกวลีธรรมชาติเพื่อทบทวนได้",
  "footer.faq.real-life.question": "ใช้สำหรับ K-drama และ K-pop เท่านั้นหรือ?",
  "footer.faq.real-life.answer":
    "ไม่ใช่ คุณยังฝึกภาษาเกาหลีสำหรับชีวิตประจำวันในเกาหลี เช่น โรงพยาบาล สำนักงานราชการ และงานพาร์ตไทม์ได้",
  "footer.faq.register.question": "ช่วยให้ฉันพูดต่างกันกับแต่ละคนได้ไหม?",
  "footer.faq.register.answer":
    "ได้ คุณฝึกความหมายเดียวกันกับหัวหน้า เพื่อนสนิท ผู้ใหญ่ หรือคนแปลกหน้า จนสลับระดับภาษาได้อย่างเป็นธรรมชาติ",
  "footer.privacy": "ความเป็นส่วนตัว",
  "footer.terms": "ข้อกำหนด",
  "footer.copyright": "© 2026 K-zip สงวนลิขสิทธิ์",
} satisfies Record<keyof typeof enUS, string>;

export const zhCN = {
  ...enUS,
  "nav.menu.open": "打开菜单",
  "nav.menu.close": "关闭菜单",
  "nav.menu.label": "移动菜单",
  "document.title": "K-zip — Learn Korean through K-Culture",
  "locale.label": "选择语言",
  "locale.ko-KR": "韩语",
  "locale.en-US": "英语",
  "locale.ar": "阿拉伯语",
  "locale.ja-JP": "日语",
  "locale.vi-VN": "越南语",
  "locale.th-TH": "泰语",
  "locale.zh-CN": "简体中文",
  "locale.zh-TW": "繁体中文",
  brand: "K-zip",
  "nav.label": "主导航",
  "nav.proof": "学习效果",
  "nav.pricing": "价格",
  "nav.cta": "申请抢先体验",
  "hero.title": "学习文化背后的真实韩语。",
  "hero.description": "听懂你喜爱视频里的笑点，应对在韩国的真实生活，并与面前的任何人自然交流。",
  "hero.cta": "申请抢先体验",
  "hero.highlight.clips": "用双语字幕重播真实视频",
  "hero.highlight.real-life": "练习真实生活场景中的韩语",
  "hero.highlight.register": "根据每种关系切换表达",
  "hero.visual.feed": "短视频信息流正在重播韩语梗片段并附上读音。",
  "hero.visual.situations": "依次展示日常韩语场景的课程卡片。",
  "proof.title": "一种语言，覆盖你的 K-life 方方面面。",
  "proof.clips.value": "2 种语言",
  "proof.clips.label": "每段视频都提供并排双语字幕",
  "proof.situations.value": "真实生活",
  "proof.situations.label": "练习你真正会遇到的场景",
  "proof.relationships.value": "4 种语体",
  "proof.relationships.label": "上司、朋友、长辈或陌生人",
  "features.clips.title": "“Lucky Vicky”……？到底是什么意思？",
  "features.clips.description":
    "从本命的口头禅到韩剧经典台词——含义、出处、适用场景，一张卡片全讲清。发现喜欢的梗？播放片段，连语气都练到位，再像本地人一样自然地和朋友用起来。",
  "features.real-life.title": "真正需要的，打包给你",
  "features.real-life.description": "不按课本章节来。只精挑细选你当下的兴趣真正需要的内容。",
  "features.register.title": "“去吃饭吧”在韩语里不只有一种说法",
  "features.register.description":
    "朋友、前辈、本命、年长的人——你在和谁说、处于什么情境、彼此有多亲近：在韩语里，这些都会改变你的表达。进入 KakaoTalk 风格的模拟聊天，与不同角色对话：语气用对了，对话自然顺畅；用错了，就看看他们如何反应。尽管在这里犯错——这样到了关键时刻，你就能说得自然。",
  "features.earlyAccess": "申请抢先体验",
  "visual.one.goodFortune": "好运",
  "visual.one.englishName": "元英的英文名",
  "visual.one.definition": "把小小的不便重新看作意外的好运。",
  "visual.one.example": "“店里卖完了，所以我拿到了新鲜出炉的 — 完全是 Lucky Vicky！”",
  "visual.one.confirm": "明白了 — 我真幸运！",
  "visual.one.bannerTitle": "韩国最新鲜的梗，直送到你家门口。",
  "visual.one.bannerDescription": "轻松了解含义和来源。",
  "visual.one.likes": "100+ 赞",
  "visual.one.instruction": "点击跟读、保存，或滑动查看下一个短视频。",
  "visual.one.shadow": "开始跟读",
  "visual.two.loading": "正在加载课程",
  "visual.two.food.title": "怎么点餐？",
  "visual.two.food.prompt": "在韩国怎么点餐？",
  "visual.two.food.action": "开始课程",
  "visual.two.fansign.title": "练习签售会对话",
  "visual.two.fansign.prompt": "你想对偶像说什么？",
  "visual.two.fansign.action": "开始练习",
  "visual.two.school.title": "校园生活基础",
  "visual.two.school.prompt": "准备好第一天了吗？",
  "visual.two.school.action": "开始课程",
  "visual.three.demo": "今天真的非常感谢",
  "visual.three.inputLabel": "要练习的意思",
  "visual.three.placeholder": "输入你想说的话",
  "visual.three.submitLabel": "按关系查看韩语表达",
  "visual.three.friend.label": "朋友",
  "visual.three.friend.tone": "随意的非敬语",
  "visual.three.elder.label": "年长教授",
  "visual.three.elder.tone": "正式敬语",
  "visual.three.boss.label": "职场上司",
  "visual.three.boss.tone": "礼貌且专业",
  "pricing.kicker": "选择你的节奏",
  "pricing.title": "从你现在需要的韩语开始。",
  "pricing.subtitle": "重播真实视频，为日常场景做好准备，并练习适合每个人的韩语表达。",
  "pricing.unit": "/月",
  "pricing.billing.monthly": "月付",
  "pricing.billing.annual": "年付",
  "pricing.billing.save": "节省 20%",
  "pricing.badge.popular": "最受欢迎",
  "pricing.free.name": "免费",
  "pricing.free.description": "用少量视频和日常短语体验核心功能。",
  "pricing.free.cta": "免费开始",
  "pricing.free.feature.clips": "精选双语字幕视频",
  "pricing.free.feature.phrases": "最多保存 20 个短语",
  "pricing.free.feature.register": "基础语体练习",
  "pricing.plus.name": "Plus",
  "pricing.plus.description": "通过视频、真实生活场景和关系型韩语养成每日习惯。",
  "pricing.plus.cta": "开始 Plus",
  "pricing.plus.feature.unlimited": "不限量视频课程",
  "pricing.plus.feature.situations": "完整真实生活场景库",
  "pricing.plus.feature.drills": "不限量语体训练",
  "pricing.plus.feature.review": "个人短语复习",
  "pricing.premium.name": "Premium",
  "pricing.premium.description": "通过更深入的练习和新工具抢先体验，获得完整学习体验。",
  "pricing.premium.cta": "选择 Premium",
  "pricing.premium.feature.everything": "Plus 的全部功能",
  "pricing.premium.feature.pronunciation": "发音反馈",
  "pricing.premium.feature.practice": "个性化练习集",
  "pricing.premium.feature.early-access": "抢先体验新功能",
  "pricing.footer": "订阅将自动续订，可随时取消。",
  "cta.badge": "为你的 K-life 打造",
  "cta.title": "理解当下，说出合适的话。",
  "cta.description": "从你已经热爱的文化中学习，再练习适用于视频、日常生活和各种关系的韩语。",
  "cta.action": "申请抢先体验",
  "cta.note.clips": "真实视频，可逐句重播",
  "cta.note.practice": "基于真实生活和关系的练习",
  "footer.label": "K-zip 页脚",
  "footer.policy.label": "政策链接",
  "footer.faq.label": "常见问题",
  "footer.faq.heading": "常见问题",
  "footer.faq.clips.question": "我能从视频中学到什么？",
  "footer.faq.clips.answer":
    "你可以并排查看韩语和自己的语言，重播任意字幕，在语境中理解词语，并保存自然短语以便复习。",
  "footer.faq.real-life.question": "这只适用于韩剧和 K-pop 吗？",
  "footer.faq.real-life.answer":
    "不是。你还可以练习医院、政府部门和兼职工作等韩国日常场景所需的韩语。",
  "footer.faq.register.question": "它能帮我对不同的人使用不同说法吗？",
  "footer.faq.register.answer":
    "可以。你可以向上司、好友、长辈或陌生人练习表达相同意思，直到自然切换语体。",
  "footer.privacy": "隐私",
  "footer.terms": "条款",
  "footer.copyright": "© 2026 K-zip。保留所有权利。",
} satisfies Record<keyof typeof enUS, string>;

export const zhTW = {
  ...enUS,
  "nav.menu.open": "開啟選單",
  "nav.menu.close": "關閉選單",
  "nav.menu.label": "行動版選單",
  "document.title": "K-zip — Learn Korean through K-Culture",
  "locale.label": "選擇語言",
  "locale.ko-KR": "韓語",
  "locale.en-US": "英語",
  "locale.ar": "阿拉伯語",
  "locale.ja-JP": "日語",
  "locale.vi-VN": "越南語",
  "locale.th-TH": "泰語",
  "locale.zh-CN": "簡體中文",
  "locale.zh-TW": "繁體中文",
  brand: "K-zip",
  "nav.label": "主導覽",
  "nav.proof": "學習效果",
  "nav.pricing": "價格",
  "nav.cta": "申請搶先體驗",
  "hero.title": "學習文化背後的真實韓語。",
  "hero.description": "聽懂你喜愛影片裡的笑點，應對在韓國的真實生活，並與眼前的任何人自然交流。",
  "hero.cta": "申請搶先體驗",
  "hero.highlight.clips": "用雙語字幕重播真實影片",
  "hero.highlight.real-life": "練習真實生活情境中的韓語",
  "hero.highlight.register": "依照每種關係切換表達",
  "hero.visual.feed": "短影音資訊流正在重播韓語梗片段並附上讀音。",
  "hero.visual.situations": "依序展示日常韓語場景的課程卡片。",
  "proof.title": "一種語言，涵蓋你的 K-life 每一面。",
  "proof.clips.value": "2 種語言",
  "proof.clips.label": "每段影片都提供並排雙語字幕",
  "proof.situations.value": "真實生活",
  "proof.situations.label": "練習你真正會遇到的情境",
  "proof.relationships.value": "4 種語體",
  "proof.relationships.label": "上司、朋友、長輩或陌生人",
  "features.clips.title": "“Lucky Vicky”……？到底是什麼意思？",
  "features.clips.description":
    "從本命的口頭禪到韓劇經典台詞——意思、由來、適用情境，一張卡片全都說清楚。找到喜歡的迷因？播放片段，連語氣都練到位，再像在地人一樣自然地和朋友用起來。",
  "features.real-life.title": "真正需要的，打包給你",
  "features.real-life.description": "不照課本章節走。只精挑細選你現在的興趣真正需要的內容。",
  "features.register.title": "「去吃飯吧」在韓語裡不只有一種說法",
  "features.register.description":
    "朋友、前輩、本命、年長的人——你在跟誰說、處於什麼情境、彼此有多親近：在韓語裡，這些都會改變你的表達。進入 KakaoTalk 風格的模擬聊天，和不同角色對話：語氣用對了，對話自然流暢；用錯了，就看看他們如何反應。儘管在這裡犯錯——這樣到了關鍵時刻，你就能說得自然。",
  "features.earlyAccess": "申請搶先體驗",
  "visual.one.goodFortune": "好運",
  "visual.one.englishName": "元英的英文名",
  "visual.one.definition": "把小小的不便重新看成意外的好運。",
  "visual.one.example": "「店裡賣完了，所以我拿到新鮮出爐的 — 完全是 Lucky Vicky！」",
  "visual.one.confirm": "懂了 — 我真幸運！",
  "visual.one.bannerTitle": "韓國最新鮮的迷因，直送你家門口。",
  "visual.one.bannerDescription": "輕鬆了解含義與來源。",
  "visual.one.likes": "100+ 讚",
  "visual.one.instruction": "點擊跟讀、儲存，或滑動查看下一段短片。",
  "visual.one.shadow": "開始跟讀",
  "visual.two.loading": "正在載入課程",
  "visual.two.food.title": "怎麼點餐？",
  "visual.two.food.prompt": "在韓國怎麼點餐？",
  "visual.two.food.action": "開始課程",
  "visual.two.fansign.title": "練習簽售會對話",
  "visual.two.fansign.prompt": "你想對偶像說什麼？",
  "visual.two.fansign.action": "開始練習",
  "visual.two.school.title": "校園生活基礎",
  "visual.two.school.prompt": "準備好第一天了嗎？",
  "visual.two.school.action": "開始課程",
  "visual.three.demo": "今天真的非常感謝",
  "visual.three.inputLabel": "要練習的意思",
  "visual.three.placeholder": "輸入你想說的話",
  "visual.three.submitLabel": "依關係查看韓語表達",
  "visual.three.friend.label": "朋友",
  "visual.three.friend.tone": "隨意的非敬語",
  "visual.three.elder.label": "年長教授",
  "visual.three.elder.tone": "正式敬語",
  "visual.three.boss.label": "職場上司",
  "visual.three.boss.tone": "禮貌且專業",
  "pricing.kicker": "選擇你的步調",
  "pricing.title": "從你現在需要的韓語開始。",
  "pricing.subtitle": "重播真實影片，為日常情境做好準備，並練習適合每個人的韓語表達。",
  "pricing.unit": "/月",
  "pricing.billing.monthly": "月付",
  "pricing.billing.annual": "年付",
  "pricing.billing.save": "節省 20%",
  "pricing.badge.popular": "最受歡迎",
  "pricing.free.name": "免費",
  "pricing.free.description": "用少量影片和日常短句體驗核心功能。",
  "pricing.free.cta": "免費開始",
  "pricing.free.feature.clips": "精選雙語字幕影片",
  "pricing.free.feature.phrases": "最多儲存 20 個短句",
  "pricing.free.feature.register": "基礎語體練習",
  "pricing.plus.name": "Plus",
  "pricing.plus.description": "透過影片、真實生活情境和關係型韓語養成每日習慣。",
  "pricing.plus.cta": "開始 Plus",
  "pricing.plus.feature.unlimited": "不限量影片課程",
  "pricing.plus.feature.situations": "完整真實生活情境庫",
  "pricing.plus.feature.drills": "不限量語體訓練",
  "pricing.plus.feature.review": "個人短句複習",
  "pricing.premium.name": "Premium",
  "pricing.premium.description": "透過更深入的練習和新工具搶先體驗，獲得完整學習體驗。",
  "pricing.premium.cta": "選擇 Premium",
  "pricing.premium.feature.everything": "Plus 的全部功能",
  "pricing.premium.feature.pronunciation": "發音回饋",
  "pricing.premium.feature.practice": "個人化練習集",
  "pricing.premium.feature.early-access": "搶先體驗新功能",
  "pricing.footer": "訂閱將自動續訂，可隨時取消。",
  "cta.badge": "為你的 K-life 打造",
  "cta.title": "理解當下，說出合適的話。",
  "cta.description": "從你已經熱愛的文化中學習，再練習適用於影片、日常生活和各種關係的韓語。",
  "cta.action": "申請搶先體驗",
  "cta.note.clips": "真實影片，可逐句重播",
  "cta.note.practice": "以真實生活和關係為基礎的練習",
  "footer.label": "K-zip 頁尾",
  "footer.policy.label": "政策連結",
  "footer.faq.label": "常見問題",
  "footer.faq.heading": "常見問題",
  "footer.faq.clips.question": "我能從影片中學到什麼？",
  "footer.faq.clips.answer":
    "你可以並排查看韓語和自己的語言，重播任意字幕，在情境中理解詞語，並儲存自然短句以便複習。",
  "footer.faq.real-life.question": "這只適用於韓劇和 K-pop 嗎？",
  "footer.faq.real-life.answer": "不是。你也可以練習醫院、政府機關和打工等韓國日常情境所需的韓語。",
  "footer.faq.register.question": "它能幫我對不同的人使用不同說法嗎？",
  "footer.faq.register.answer":
    "可以。你可以向上司、好友、長輩或陌生人練習表達相同意思，直到自然切換語體。",
  "footer.privacy": "隱私權",
  "footer.terms": "條款",
  "footer.copyright": "© 2026 K-zip。保留所有權利。",
} satisfies Record<keyof typeof enUS, string>;
