export const koKR = {
  "nav.menu.open": "메뉴 열기",
  "nav.menu.close": "메뉴 닫기",
  "nav.menu.label": "모바일 메뉴",
  "document.title": "Luma 랜딩 실험",
  brand: "Luma",
  "nav.label": "주요 메뉴",
  "nav.product": "제품",
  "nav.proof": "성과",
  "nav.cta": "시작하기",
  "locale.label": "언어 선택",
  "locale.ko-KR": "한국어",
  "locale.en-US": "영어",
  "locale.ar": "아랍어",
  "hero.eyebrow": "자신 있게 출시하세요",
  "hero.title": "하나의 시스템, 무한한 랜딩 실험",
  "hero.description":
    "공통 기반으로 완성도 높은 글로벌 경험을 구성하면서도\n각 아이디어의 개성을 유지하세요.",
  "hero.start": "Get Early Access",
  "hero.method": "방법 보기",
  "hero.preview": "랜딩 경험 미리보기",
  "proof.title": "명확하게 측정된 신뢰할 수 있는 성과",
  "proof.markets.value": "24",
  "proof.markets.label": "출시 준비 시장",
  "proof.reuse.value": "82%",
  "proof.reuse.label": "공통 기반",
  "proof.launch.value": "2배",
  "proof.launch.label": "더 빠른 반복",
  "features.title": "빠른 학습을 위한 설계",
  "features.speed.title": "빠르게\n출시",
  "features.speed.description": "재사용 가능한 기반 덕분에\n아이디어 실험에 집중할 수 있습니다.",
  "features.consistency.title": "일관성 유지",
  "features.consistency.description": "공통 토큰이 모든 시장에서 하나의 시각 언어를 만듭니다.",
  "features.freedom.title": "유연성 유지",
  "features.freedom.description": "실험 전용 UI는 해당 경험 가까이에 유지됩니다.",
  "cta.title": "다음 아이디어를 현실로 만드세요",
  "cta.description": "일관된 기반에서 시작해 실험의 가치를 만드는 일에 에너지를 쓰세요.",
  "cta.action": "실험 만들기",
  "cta.badge": "유튜브 K-드라마 섀도잉",
  "cta.note.card": "카드 불필요",
  "cta.note.access": "얼리 액세스 업데이트",
  "pricing.kicker": "모바일 앱 구독",
  "pricing.title": "K-콘텐츠로 배우는 한국어 요금제",
  "pricing.subtitle": "유튜브·K-드라마·K-팝 클립으로 하는\n짧은 한국어 연습을 위한 간편한 인앱 플랜.",
  "pricing.unit": "/월",
  "pricing.billing.monthly": "월간",
  "pricing.billing.annual": "연간",
  "pricing.billing.save": "20% 절약",
  "pricing.badge.popular": "인기",
  "pricing.free.name": "무료",
  "pricing.free.description": "매일 짧은 클립과 기본 한국어 자막으로 앱에서 시작하세요.",
  "pricing.free.cta": "무료로 시작",
  "pricing.free.feature.clips": "하루 3개 클립",
  "pricing.free.feature.captions": "기본 자막",
  "pricing.free.feature.saved": "5개 클립 저장",
  "pricing.plus.name": "플러스",
  "pricing.plus.description": "무제한 클립·가져오기·리마인더로 매일 모바일 연습.",
  "pricing.plus.cta": "플러스 시작",
  "pricing.plus.feature.unlimited": "무제한 짧은 클립",
  "pricing.plus.feature.import": "유튜브 클립 가져오기",
  "pricing.plus.feature.offline": "오프라인 저장",
  "pricing.plus.feature.reminders": "복습 리마인더",
  "pricing.premium.name": "프리미엄",
  "pricing.premium.description": "진지한 학습자를 위한 발음 피드백과 다국어 도움말.",
  "pricing.premium.cta": "프리미엄으로",
  "pricing.premium.feature.pronunciation": "AI 발음 피드백",
  "pricing.premium.feature.subtitles": "다국어 자막",
  "pricing.premium.feature.collections": "맞춤 클립 컬렉션",
  "pricing.premium.feature.priority": "우선 앱 기능",
  "pricing.footer": "구독은 자동 갱신됩니다. App Store 또는 Google Play 설정에서 언제든 취소할 수 있습니다.",
  "footer.availability": "전 세계에서 이용 가능",
  "footer.top": "맨 위로",
  "footer.label": "Luma 드라마 푸터",
  "footer.links.label": "서비스 링크",
  "footer.policy.label": "정책 링크",
  "footer.faq.label": "자주 묻는 질문",
  "footer.faq.heading": "자주 묻는 질문",
  "footer.faq.availability.question": "어디에서 이용할 수 있나요?",
  "footer.faq.availability.answer": "Luma 드라마는 전 세계 시청자를 위한 경험을 제공합니다.",
  "footer.faq.workflow.question": "새로운 이야기는 어떻게 발견하나요?",
  "footer.faq.workflow.answer":
    "엄선된 컬렉션과 추천 기능에서 새로운 드라마와 이야기를 탐색할 수 있습니다.",
  "footer.privacy": "개인정보 처리방침",
  "footer.terms": "이용약관",
  "footer.copyright": "© 2026 Luma 드라마. 모든 권리 보유.",
} as const;

export const enUS: Record<keyof typeof koKR, string> = {
  "nav.menu.open": "Open menu",
  "nav.menu.close": "Close menu",
  "nav.menu.label": "Mobile menu",
  "document.title": "Luma Landing Experiments",
  "locale.label": "Choose language",
  "locale.ko-KR": "Korean",
  "locale.en-US": "English",
  "locale.ar": "Arabic",
  brand: "Luma",
  "nav.label": "Primary",
  "nav.product": "Product",
  "nav.proof": "Proof",
  "nav.cta": "Try",
  "hero.eyebrow": "Launch with confidence",
  "hero.title": "One system, endless landing experiments",
  "hero.description":
    "Compose polished global experiences from shared foundations\nwhile keeping each idea free to stand apart.",
  "hero.start": "Get Early Access",
  "hero.method": "See the method",
  "hero.preview": "Landing experience preview",
  "proof.title": "Trusted outcomes, clearly measured",
  "proof.markets.value": "24",
  "proof.markets.label": "Markets ready",
  "proof.reuse.value": "82%",
  "proof.reuse.label": "Shared foundation",
  "proof.launch.value": "2×",
  "proof.launch.label": "Faster iteration",
  "features.title": "Built for learning at speed",
  "features.speed.title": "Ship\nquickly",
  "features.speed.description": "Reusable foundations\nkeep experimentation focused on the idea.",
  "features.consistency.title": "Stay coherent",
  "features.consistency.description":
    "Shared tokens create one visual language across every market.",
  "features.freedom.title": "Keep flexibility",
  "features.freedom.description":
    "Experiment-specific UI remains close to the experience it serves.",
  "cta.title": "Make the next idea tangible",
  "cta.description":
    "Start from a consistent base and spend your energy on what makes the experiment matter.",
  "cta.action": "Create an experiment",
  "cta.badge": "YouTube K-drama shadowing",
  "cta.note.card": "No card required",
  "cta.note.access": "Early access updates",
  "pricing.kicker": "Mobile app subscriptions",
  "pricing.title": "Pricing for Korean with K-contents",
  "pricing.subtitle": "Simple in-app plans for short-form Korean practice\nwith YouTube, K-drama, and K-pop clips.",
  "pricing.unit": "/mo",
  "pricing.billing.monthly": "Monthly",
  "pricing.billing.annual": "Annual",
  "pricing.billing.save": "Save 20%",
  "pricing.badge.popular": "Popular",
  "pricing.free.name": "Free",
  "pricing.free.description": "Start with daily short clips and basic Korean captions in the app.",
  "pricing.free.cta": "Install free",
  "pricing.free.feature.clips": "3 clips per day",
  "pricing.free.feature.captions": "Basic captions",
  "pricing.free.feature.saved": "5 saved clips",
  "pricing.plus.name": "Plus",
  "pricing.plus.description": "Daily mobile practice with unlimited clips, imports, and reminders.",
  "pricing.plus.cta": "Start Plus",
  "pricing.plus.feature.unlimited": "Unlimited short clips",
  "pricing.plus.feature.import": "YouTube clip import",
  "pricing.plus.feature.offline": "Offline saved clips",
  "pricing.plus.feature.reminders": "Review reminders",
  "pricing.premium.name": "Premium",
  "pricing.premium.description": "Pronunciation feedback and multilingual help for serious learners.",
  "pricing.premium.cta": "Go Premium",
  "pricing.premium.feature.pronunciation": "AI pronunciation feedback",
  "pricing.premium.feature.subtitles": "Multilingual subtitles",
  "pricing.premium.feature.collections": "Custom clip collections",
  "pricing.premium.feature.priority": "Priority app features",
  "pricing.footer": "Subscriptions renew automatically. Cancel anytime in your App Store or Google Play settings.",
  "footer.availability": "Available worldwide",
  "footer.top": "Back to top",
  "footer.label": "Luma Drama footer",
  "footer.links.label": "Service links",
  "footer.policy.label": "Policy links",
  "footer.faq.label": "Frequently asked questions",
  "footer.faq.heading": "Frequently asked questions",
  "footer.faq.availability.question": "Where is Luma Drama available?",
  "footer.faq.availability.answer":
    "Luma Drama offers an experience designed for audiences around the world.",
  "footer.faq.workflow.question": "How can I discover new stories?",
  "footer.faq.workflow.answer":
    "Explore curated collections and recommendations to find new dramas and stories.",
  "footer.privacy": "Privacy",
  "footer.terms": "Terms",
  "footer.copyright": "© 2026 Luma Drama. All rights reserved.",
};

export const ar: Record<keyof typeof koKR, string> = {
  "nav.menu.open": "افتح القائمة",
  "nav.menu.close": "أغلق القائمة",
  "nav.menu.label": "قائمة الجوال",
  "document.title": "تجارب صفحات لوما",
  "locale.label": "اختر اللغة",
  "locale.ko-KR": "الكورية",
  "locale.en-US": "الإنجليزية",
  "locale.ar": "العربية",
  brand: "لوما",
  "nav.label": "التنقل الرئيسي",
  "nav.product": "المنتج",
  "nav.proof": "النتائج",
  "nav.cta": "ابدأ الآن",
  "hero.eyebrow": "أطلق بثقة",
  "hero.title": "نظام واحد وتجارب صفحات بلا حدود",
  "hero.description": "أنشئ تجارب عالمية متقنة من أسس مشتركة\nمع الحفاظ على تميز كل فكرة.",
  "hero.start": "احصل على وصول مبكر",
  "hero.method": "شاهد المنهج",
  "hero.preview": "معاينة تجربة الصفحة",
  "proof.title": "نتائج موثوقة بقياس واضح",
  "proof.markets.value": "٢٤",
  "proof.markets.label": "سوقاً جاهزاً",
  "proof.reuse.value": "٪٨٢",
  "proof.reuse.label": "أساس مشترك",
  "proof.launch.value": "ضعفان",
  "proof.launch.label": "تكرار أسرع",
  "features.title": "مصمم للتعلم بسرعة",
  "features.speed.title": "أطلق\nبسرعة",
  "features.speed.description": "تُبقي الأسس القابلة لإعادة الاستخدام\nالتجربة مركزة على الفكرة.",
  "features.consistency.title": "حافظ على الاتساق",
  "features.consistency.description": "تصنع الرموز المشتركة لغة بصرية واحدة في كل سوق.",
  "features.freedom.title": "حافظ على المرونة",
  "features.freedom.description": "تبقى واجهة كل تجربة قريبة من التجربة التي تخدمها.",
  "cta.title": "حوّل الفكرة التالية إلى واقع",
  "cta.description": "ابدأ من قاعدة متسقة ووجّه طاقتك إلى ما يجعل التجربة مهمة.",
  "cta.action": "أنشئ تجربة",
  "cta.badge": "تظليل دراما كورية على يوتيوب",
  "cta.note.card": "بدون بطاقة",
  "cta.note.access": "تحديثات الوصول المبكر",
  "pricing.kicker": "اشتراكات تطبيق الجوال",
  "pricing.title": "أسعار تعلّم الكورية مع محتوى K",
  "pricing.subtitle": "خطط بسيطة داخل التطبيق لممارسة الكورية القصيرة\nمع مقاطع يوتيوب والدراما و‑K‑pop.",
  "pricing.unit": "/شهر",
  "pricing.billing.monthly": "شهري",
  "pricing.billing.annual": "سنوي",
  "pricing.billing.save": "وفّر 20%",
  "pricing.badge.popular": "الأكثر رواجًا",
  "pricing.free.name": "مجاني",
  "pricing.free.description": "ابدأ بمقاطع قصيرة يومية وترجمات كورية أساسية في التطبيق.",
  "pricing.free.cta": "ثبّت مجانًا",
  "pricing.free.feature.clips": "3 مقاطع يوميًا",
  "pricing.free.feature.captions": "ترجمات أساسية",
  "pricing.free.feature.saved": "حفظ 5 مقاطع",
  "pricing.plus.name": "بلس",
  "pricing.plus.description": "ممارسة يومية عبر الجوال بمقاطع واستيراد وتذكيرات غير محدودة.",
  "pricing.plus.cta": "ابدأ بلس",
  "pricing.plus.feature.unlimited": "مقاطع قصيرة غير محدودة",
  "pricing.plus.feature.import": "استيراد مقاطع يوتيوب",
  "pricing.plus.feature.offline": "حفظ دون اتصال",
  "pricing.plus.feature.reminders": "تذكيرات المراجعة",
  "pricing.premium.name": "بريميوم",
  "pricing.premium.description": "ملاحظات نطق ومساعدة متعددة اللغات للمتعلمين الجادين.",
  "pricing.premium.cta": "اذهب لبريميوم",
  "pricing.premium.feature.pronunciation": "ملاحظات نطق بالذكاء الاصطناعي",
  "pricing.premium.feature.subtitles": "ترجمات متعددة اللغات",
  "pricing.premium.feature.collections": "مجموعات مقاطع مخصصة",
  "pricing.premium.feature.priority": "ميزات تطبيق ذات أولوية",
  "pricing.footer": "تتجدد الاشتراكات تلقائيًا. يمكنك الإلغاء في أي وقت من إعدادات App Store أو Google Play.",
  "footer.availability": "متاح حول العالم",
  "footer.top": "العودة إلى الأعلى",
  "footer.label": "تذييل لوما للدراما",
  "footer.links.label": "روابط الخدمة",
  "footer.policy.label": "روابط السياسات",
  "footer.faq.label": "الأسئلة الشائعة",
  "footer.faq.heading": "الأسئلة الشائعة",
  "footer.faq.availability.question": "أين تتوفر لوما للدراما؟",
  "footer.faq.availability.answer": "تقدم لوما للدراما تجربة مصممة للجمهور حول العالم.",
  "footer.faq.workflow.question": "كيف أكتشف قصصاً جديدة؟",
  "footer.faq.workflow.answer": "استكشف المجموعات والتوصيات المنتقاة للعثور على أعمال وقصص جديدة.",
  "footer.privacy": "الخصوصية",
  "footer.terms": "الشروط",
  "footer.copyright": "© 2026 لوما للدراما. جميع الحقوق محفوظة.",
};
