export const koKR = {
  "nav.menu.open": "메뉴 열기",
  "nav.menu.close": "메뉴 닫기",
  "nav.menu.label": "모바일 메뉴",
  "document.title": "Luma 접근 방식 비교",
  brand: "Luma 비교",
  "nav.label": "주요 메뉴",
  "nav.comparison": "비교",
  "nav.benefits": "장점",
  "nav.cta": "Luma 선택",
  "locale.label": "언어 선택",
  "locale.ko-KR": "한국어",
  "locale.en-US": "영어",
  "locale.ar": "아랍어",
  "hero.eyebrow": "더 나은 의사결정",
  "hero.title": "Practice real Korean Conversations - out loud, anytime",
  "hero.description":
    "You've learned the words. Now actually say them. Role-play real situations, get corrected on the spot, and even chat with your favorite idol - with an AI that's always on.",
  "hero.action": "Get Early Access",
  "hero.preview": "접근 방식 미리보기",
  "comparison.title": "더 명확한 경로를 선택하세요",
  "comparison.region": "스크롤 가능한 접근 방식 비교",
  "comparison.table": "접근 방식 비교",
  "comparison.criterion": "기준",
  "comparison.product": "Luma",
  "comparison.alternative": "임시 방식",
  "comparison.setup.criterion": "설정",
  "comparison.setup.product": "공유되고 준비됨",
  "comparison.setup.alternative": "매번 다시 구축",
  "comparison.brand.criterion": "브랜드 일관성",
  "comparison.brand.product": "토큰 기반",
  "comparison.brand.alternative": "수동 검토",
  "comparison.extension.criterion": "실험 UI",
  "comparison.extension.product": "로컬 조합 가능",
  "comparison.extension.alternative": "전역 결합",
  "nav.proof": "성과",
  "proof.title": "명확하게 측정된 신뢰할 수 있는 성과",
  "proof.markets.value": "24",
  "proof.markets.label": "출시 준비 시장",
  "proof.reuse.value": "82%",
  "proof.reuse.label": "공통 기반",
  "proof.launch.value": "2배",
  "proof.launch.label": "더 빠른 반복",
  "features.title": "트레이드오프를 보여주는 시스템",
  "features.clarity.title": "명확한\n경계",
  "features.clarity.description": "공통 책임과 로컬 책임을\n쉽게 구분할 수 있습니다.",
  "features.access.title": "접근 가능한 기본값",
  "features.access.description": "시맨틱 구조와 보이는 포커스가 기반부터 적용됩니다.",
  "features.global.title": "글로벌 도달",
  "features.global.description": "유연한 레이아웃이 다양한 기기와 긴 번역문을 수용합니다.",
  "cta.title": "변화에 발맞추는 기반을 선택하세요",
  "cta.description": "비교에서 실제 실험까지 하나의 일관된 작업 공간에서 진행하세요.",
  "cta.action": "시스템 선택",
  "cta.badge": "AI 기반 커뮤니케이션",
  "cta.note.card": "카드 불필요",
  "cta.note.access": "얼리 액세스 업데이트",
  "pricing.kicker": "AI 메시지 플랜",
  "pricing.title": "더 명확한 소통을 위한 요금제",
  "pricing.subtitle": "AI 초안 작성, 어조 조절, 다국어 답장을\n팀 전체에서 사용하는 간편한 플랜.",
  "pricing.unit": "/월",
  "pricing.billing.monthly": "월간",
  "pricing.billing.annual": "연간",
  "pricing.billing.save": "20% 절약",
  "pricing.badge.popular": "인기",
  "pricing.free.name": "무료",
  "pricing.free.description": "AI 초안과 기본 어조 검사로 일상 메시지를 시작하세요.",
  "pricing.free.cta": "무료로 시작",
  "pricing.free.feature.clips": "AI 답장 초안",
  "pricing.free.feature.captions": "기본 어조 검사",
  "pricing.free.feature.saved": "저장된 스니펫",
  "pricing.plus.name": "플러스",
  "pricing.plus.description": "무제한 AI 초안과 공유 템플릿으로 매일 팀 메시지를 처리하세요.",
  "pricing.plus.cta": "플러스 시작",
  "pricing.plus.feature.unlimited": "무제한 AI 초안",
  "pricing.plus.feature.import": "템플릿 가져오기",
  "pricing.plus.feature.offline": "오프라인 초안",
  "pricing.plus.feature.reminders": "후속 리마인더",
  "pricing.premium.name": "프리미엄",
  "pricing.premium.description": "전문 팀을 위한 고급 어조 조절, 분석, 우선 지원.",
  "pricing.premium.cta": "프리미엄으로",
  "pricing.premium.feature.pronunciation": "고급 어조 조절",
  "pricing.premium.feature.subtitles": "다국어 답장",
  "pricing.premium.feature.collections": "공유 팀 템플릿",
  "pricing.premium.feature.priority": "우선 지원",
  "pricing.footer": "플랜은 자동 갱신됩니다. 계정 설정에서 언제든 취소할 수 있습니다.",
  "footer.message": "글로벌 팀을 위해 제작",
  "footer.top": "맨 위로",
  "footer.label": "Luma 비교 푸터",
  "footer.links.label": "비교 링크",
  "footer.policy.label": "정책 링크",
  "footer.faq.label": "자주 묻는 질문",
  "footer.faq.heading": "자주 묻는 질문",
  "footer.faq.teams.question": "어떤 팀을 위한 서비스인가요?",
  "footer.faq.teams.answer":
    "일관된 실험과 더 명확한 의사결정이 필요한 글로벌 제품 팀을 위해 설계했습니다.",
  "footer.faq.comparison.question": "접근 방식은 어떻게 비교하나요?",
  "footer.faq.comparison.answer":
    "설정, 브랜드 일관성, 확장성 기준을 한 화면에서 나란히 확인할 수 있습니다.",
  "footer.privacy": "개인정보 처리방침",
  "footer.terms": "이용약관",
  "footer.copyright": "© 2026 Luma 비교. 모든 권리 보유.",
} as const;
export const enUS: Record<keyof typeof koKR, string> = {
  "nav.menu.open": "Open menu",
  "nav.menu.close": "Close menu",
  "nav.menu.label": "Mobile menu",
  "document.title": "Compare approaches with Luma",
  "locale.label": "Choose language",
  "locale.ko-KR": "Korean",
  "locale.en-US": "English",
  "locale.ar": "Arabic",
  brand: "Luma Compare",
  "nav.label": "Primary",
  "nav.comparison": "Comparison",
  "nav.benefits": "Benefits",
  "nav.cta": "Choose Luma",
  "hero.eyebrow": "A better way to decide",
  "hero.title": "Practice real Korean Conversations - out loud, anytime",
  "hero.description":
    "You've learned the words. Now actually say them. Role-play real situations, get corrected on the spot, and even chat with your favorite idol - with an AI that's always on.",
  "hero.action": "Get Early Access",
  "hero.preview": "Approach preview",
  "comparison.title": "Choose the clearer path",
  "comparison.region": "Scrollable approach comparison",
  "comparison.table": "Approach comparison",
  "comparison.criterion": "Criterion",
  "comparison.product": "Luma",
  "comparison.alternative": "Ad hoc",
  "comparison.setup.criterion": "Setup",
  "comparison.setup.product": "Shared and ready",
  "comparison.setup.alternative": "Rebuilt every time",
  "comparison.brand.criterion": "Brand consistency",
  "comparison.brand.product": "Token driven",
  "comparison.brand.alternative": "Manually reviewed",
  "comparison.extension.criterion": "Experiment UI",
  "comparison.extension.product": "Locally composable",
  "comparison.extension.alternative": "Globally coupled",
  "nav.proof": "Proof",
  "proof.title": "Trusted outcomes, clearly measured",
  "proof.markets.value": "24",
  "proof.markets.label": "Markets ready",
  "proof.reuse.value": "82%",
  "proof.reuse.label": "Shared foundation",
  "proof.launch.value": "2×",
  "proof.launch.label": "Faster iteration",
  "features.title": "A system that makes tradeoffs visible",
  "features.clarity.title": "Clear\nboundaries",
  "features.clarity.description": "Shared and local responsibilities\nremain easy to see.",
  "features.access.title": "Accessible defaults",
  "features.access.description": "Semantic structure and visible focus begin at the foundation.",
  "features.global.title": "Global reach",
  "features.global.description": "Flexible layouts accommodate devices and longer translations.",
  "cta.title": "Choose a foundation that keeps up",
  "cta.description": "Move from comparison to a working experiment in one coherent workspace.",
  "cta.action": "Choose the system",
  "cta.badge": "AI-assisted communication",
  "cta.note.card": "No card required",
  "cta.note.access": "Early access updates",
  "pricing.kicker": "AI messaging plans",
  "pricing.title": "Pricing for clearer communication",
  "pricing.subtitle": "Simple plans for AI-assisted drafting, tone control,\nand multi-language replies across your team.",
  "pricing.unit": "/mo",
  "pricing.billing.monthly": "Monthly",
  "pricing.billing.annual": "Annual",
  "pricing.billing.save": "Save 20%",
  "pricing.badge.popular": "Popular",
  "pricing.free.name": "Free",
  "pricing.free.description": "Start with AI drafts and basic tone checks for everyday messages.",
  "pricing.free.cta": "Start free",
  "pricing.free.feature.clips": "AI reply drafts",
  "pricing.free.feature.captions": "Basic tone check",
  "pricing.free.feature.saved": "Saved snippets",
  "pricing.plus.name": "Plus",
  "pricing.plus.description": "Daily and team messaging with unlimited AI drafts and shared templates.",
  "pricing.plus.cta": "Get Plus",
  "pricing.plus.feature.unlimited": "Unlimited AI drafts",
  "pricing.plus.feature.import": "Import templates",
  "pricing.plus.feature.offline": "Offline drafts",
  "pricing.plus.feature.reminders": "Follow-up reminders",
  "pricing.premium.name": "Premium",
  "pricing.premium.description": "Advanced tone control, analytics, and priority support for pro teams.",
  "pricing.premium.cta": "Go Premium",
  "pricing.premium.feature.pronunciation": "Advanced tone control",
  "pricing.premium.feature.subtitles": "Multi-language replies",
  "pricing.premium.feature.collections": "Shared team templates",
  "pricing.premium.feature.priority": "Priority support",
  "pricing.footer": "Plans renew automatically. Cancel anytime from your account settings.",
  "footer.message": "Built for global teams",
  "footer.top": "Back to top",
  "footer.label": "Luma Compare footer",
  "footer.links.label": "Comparison links",
  "footer.policy.label": "Policy links",
  "footer.faq.label": "Frequently asked questions",
  "footer.faq.heading": "Frequently asked questions",
  "footer.faq.teams.question": "Which teams is this for?",
  "footer.faq.teams.answer":
    "It is designed for global product teams that need consistent experiments and clearer decisions.",
  "footer.faq.comparison.question": "How are approaches compared?",
  "footer.faq.comparison.answer":
    "Review setup, brand consistency, and extensibility side by side on one page.",
  "footer.privacy": "Privacy",
  "footer.terms": "Terms",
  "footer.copyright": "© 2026 Luma Compare. All rights reserved.",
};
export const ar: Record<keyof typeof koKR, string> = {
  "nav.menu.open": "افتح القائمة",
  "nav.menu.close": "أغلق القائمة",
  "nav.menu.label": "قائمة الجوال",
  "document.title": "قارن الأساليب مع لوما",
  "locale.label": "اختر اللغة",
  "locale.ko-KR": "الكورية",
  "locale.en-US": "الإنجليزية",
  "locale.ar": "العربية",
  brand: "مقارنة لوما",
  "nav.label": "التنقل الرئيسي",
  "nav.comparison": "المقارنة",
  "nav.benefits": "الفوائد",
  "nav.cta": "اختر لوما",
  "hero.eyebrow": "طريقة أفضل للقرار",
  "hero.title": "Practice real Korean Conversations - out loud, anytime",
  "hero.description":
    "You've learned the words. Now actually say them. Role-play real situations, get corrected on the spot, and even chat with your favorite idol - with an AI that's always on.",
  "hero.action": "احصل على وصول مبكر",
  "hero.preview": "معاينة الأساليب",
  "comparison.title": "اختر المسار الأوضح",
  "comparison.region": "مقارنة أساليب قابلة للتمرير",
  "comparison.table": "مقارنة الأساليب",
  "comparison.criterion": "المعيار",
  "comparison.product": "لوما",
  "comparison.alternative": "حل مؤقت",
  "comparison.setup.criterion": "الإعداد",
  "comparison.setup.product": "مشترك وجاهز",
  "comparison.setup.alternative": "يُعاد بناؤه كل مرة",
  "comparison.brand.criterion": "اتساق العلامة",
  "comparison.brand.product": "مدعوم بالرموز",
  "comparison.brand.alternative": "مراجعة يدوية",
  "comparison.extension.criterion": "واجهة التجربة",
  "comparison.extension.product": "قابلة للتركيب محلياً",
  "comparison.extension.alternative": "مقترنة عالمياً",
  "nav.proof": "النتائج",
  "proof.title": "نتائج موثوقة بقياس واضح",
  "proof.markets.value": "٢٤",
  "proof.markets.label": "سوقاً جاهزاً",
  "proof.reuse.value": "٪٨٢",
  "proof.reuse.label": "أساس مشترك",
  "proof.launch.value": "ضعفان",
  "proof.launch.label": "تكرار أسرع",
  "features.title": "نظام يوضح المفاضلات",
  "features.clarity.title": "حدود\nواضحة",
  "features.clarity.description": "تبقى المسؤوليات المشتركة والمحلية\nسهلة الرؤية.",
  "features.access.title": "إعدادات ميسّرة",
  "features.access.description": "تبدأ البنية الدلالية والتركيز المرئي من الأساس.",
  "features.global.title": "وصول عالمي",
  "features.global.description": "تستوعب التخطيطات المرنة الأجهزة والترجمات الأطول.",
  "cta.title": "اختر أساساً يواكبك",
  "cta.description": "انتقل من المقارنة إلى تجربة عاملة في مساحة عمل مترابطة.",
  "cta.action": "اختر النظام",
  "cta.badge": "تواصل بمساعدة الذكاء الاصطناعي",
  "cta.note.card": "بدون بطاقة",
  "cta.note.access": "تحديثات الوصول المبكر",
  "pricing.kicker": "خطط الرسائل بالذكاء الاصطناعي",
  "pricing.title": "أسعار لتواصل أوضح",
  "pricing.subtitle": "خطط بسيطة لصياغة المسودات بالذكاء الاصطناعي والتحكم في النبرة\nوالردود متعددة اللغات عبر فريقك.",
  "pricing.unit": "/شهر",
  "pricing.billing.monthly": "شهري",
  "pricing.billing.annual": "سنوي",
  "pricing.billing.save": "وفّر 20%",
  "pricing.badge.popular": "الأكثر رواجًا",
  "pricing.free.name": "مجاني",
  "pricing.free.description": "ابدأ بمسودات الذكاء الاصطناعي وفحص النبرة الأساسي للرسائل اليومية.",
  "pricing.free.cta": "ابدأ مجاناً",
  "pricing.free.feature.clips": "مسودات ردود ذكية",
  "pricing.free.feature.captions": "فحص النبرة الأساسي",
  "pricing.free.feature.saved": "مقتطفات محفوظة",
  "pricing.plus.name": "بلس",
  "pricing.plus.description": "رسائل يومية وجماعية مع مسودات ذكية غير محدودة وقوالب مشتركة.",
  "pricing.plus.cta": "احصل على بلس",
  "pricing.plus.feature.unlimited": "مسودات ذكية غير محدودة",
  "pricing.plus.feature.import": "استيراد القوالب",
  "pricing.plus.feature.offline": "مسودات دون اتصال",
  "pricing.plus.feature.reminders": "تذكيرات المتابعة",
  "pricing.premium.name": "بريميوم",
  "pricing.premium.description": "تحكم متقدم في النبرة وتحليلات ودعم بأولوية للفرق المحترفة.",
  "pricing.premium.cta": "انتقل إلى بريميوم",
  "pricing.premium.feature.pronunciation": "تحكم متقدم في النبرة",
  "pricing.premium.feature.subtitles": "ردود متعددة اللغات",
  "pricing.premium.feature.collections": "قوالب فريق مشتركة",
  "pricing.premium.feature.priority": "دعم بأولوية",
  "pricing.footer": "تتجدد الخطط تلقائياً. يمكنك الإلغاء في أي وقت من إعدادات حسابك.",
  "footer.message": "صُمم للفرق العالمية",
  "footer.top": "العودة إلى الأعلى",
  "footer.label": "تذييل مقارنة لوما",
  "footer.links.label": "روابط المقارنة",
  "footer.policy.label": "روابط السياسات",
  "footer.faq.label": "الأسئلة الشائعة",
  "footer.faq.heading": "الأسئلة الشائعة",
  "footer.faq.teams.question": "لأي فرق صُممت هذه الخدمة؟",
  "footer.faq.teams.answer":
    "صُممت لفرق المنتجات العالمية التي تحتاج إلى تجارب متسقة وقرارات أوضح.",
  "footer.faq.comparison.question": "كيف تتم مقارنة الأساليب؟",
  "footer.faq.comparison.answer":
    "راجع الإعداد واتساق العلامة وقابلية التوسع جنباً إلى جنب في صفحة واحدة.",
  "footer.privacy": "الخصوصية",
  "footer.terms": "الشروط",
  "footer.copyright": "© 2026 مقارنة لوما. جميع الحقوق محفوظة.",
};
