const featureCopy = {
  "earlyAccess.back": "Back to Baetter",
  "earlyAccess.close": "Close early-access form",
  "earlyAccess.eyebrow": "Early access reservation",
  "earlyAccess.title": "Be first to practice Korean with Baetter",
  "earlyAccess.description":
    "Leave your email and we will send your invitation when your spot is ready.",
  "earlyAccess.benefit.invite": "Priority invitation and launch updates",
  "earlyAccess.benefit.voice": "Voice, text, role-play, and persona practice",
  "earlyAccess.benefit.feedback": "A chance to shape Baetter with your feedback",
  "earlyAccess.form.title": "Reserve your spot",
  "earlyAccess.form.description": "Enter your email to join the early-access list.",
  "earlyAccess.form.email": "Email",
  "earlyAccess.form.consent": "I agree to receive early-access and launch updates by email.",
  "earlyAccess.form.submit": "Reserve early access",
  "earlyAccess.form.submitting": "Saving…",
  "earlyAccess.form.privacy":
    "We will only use these details for Baetter early access and related updates.",
  "earlyAccess.form.integrationPending":
    "The form UI is ready. Registration will open when the shared Supabase connection is added.",
  "earlyAccess.form.success": "You are on the list. We will be in touch soon.",
  "earlyAccess.form.error": "We could not save your registration. Please try again.",
  "nav.pricing": "Pricing",
  "feature.cta": "Get early access",
  "feature.roleplay.number": "1",
  "feature.roleplay.title": "Role-play the situations you'll actually be in",
  "feature.roleplay.description":
    "Practice useful Korean for real conversations, whenever you are ready.",
  "feature.roleplay.pill.one": "Cafés, taxis, meeting friends, and more",
  "feature.roleplay.pill.two": "Chat about your interests and K-pop",
  "feature.roleplay.pill.three": "Speak or type anytime",
  "feature.roleplay.phone.title": "Practice Idol Fan-Sign",
  "feature.roleplay.phone.badge": "Idol Fan-Sign Roleplay",
  "feature.roleplay.phone.prompt": "이번 새 앨범에 어떤 수록곡이 맘에 들었어?",
  "feature.roleplay.phone.translation": "Which tracks on the new album did you like?",
  "feature.roleplay.tag.roleplay": "Role play",
  "feature.roleplay.tag.travel": "Travel",
  "feature.roleplay.tag.cafe": "Cafe",
  "feature.roleplay.scene.cosmetic": "Buy cosmetics",
  "feature.roleplay.scene.taxi": "Taxi driver",
  "feature.corrections.number": "2",
  "feature.corrections.title": "Build your own sentences,\nGet instant corrections.",
  "feature.corrections.description":
    "Not another flashcard drill.\nSay what you mean, then see how Koreans would naturally say it.",
  "feature.corrections.voice": "“지금 어디야?”",
  "feature.corrections.question": "어디야?",
  "feature.corrections.answer": "나지금 오고 있어",
  "feature.corrections.feedback": "Better phrasing",
  "feature.corrections.improved": "나 지금 가고 있어(요)",
  "feature.corrections.explanation":
    "Add spacing after 나 and use 가고 있어(요) for natural polite roleplay speech.",
  "feature.bias.number": "3",
  "feature.bias.title": "Chat with your bias\n- in Korean.",
  "feature.bias.description":
    "Turn fandom into daily practice. Have immersive conversations with idol- and character-style personas, and keep coming back because it's actually fun.",
  "feature.bias.benefit.one": "Choose a persona with the vibe you love",
  "feature.bias.benefit.two": "Keep natural Korean conversations going without pressure",
  "feature.bias.benefit.three": "Turn fandom into a daily speaking routine",
  "feature.bias.chat.midnight": "오늘은 뭐 배울래?",
  "feature.bias.chat.offrecord": "지금 뭐해?",
  "feature.bias.persona.midnight.name": "Midnight Whisper",
  "feature.bias.persona.midnight.quote":
    "On the runway I'm the cold, silent muse. But at midnight I only want to hear you speak Korean.",
  "feature.bias.persona.midnight.tags": "#SecretLesson #SweetToYou",
  "feature.bias.persona.midnight.streak": "1000+ Learning",
  "feature.bias.persona.offrecord.name": "Off the Record Lesson",
  "feature.bias.persona.offrecord.quote":
    "I never smile for the cameras, but I can't stop smiling when I hear you practicing Korean.",
  "feature.bias.persona.offrecord.tags": "#SecretLesson #SweetToYou",
  "feature.bias.persona.offrecord.streak": "500+ Learning",
  "feature.bias.persona.order.name": "This is an order",
  "feature.bias.persona.order.quote":
    "Speak Korean with me today. Stay close, follow my lead, and say it in Korean.",
  "feature.bias.persona.order.tags": "#Army #Mission",
  "feature.bias.persona.order.streak": "1000+ Learning",
  "feature.bias.persona.closer.name": "Come Closer",
  "feature.bias.persona.closer.quote":
    "Take your time, my lady. Whatever rests upon your heart, speak it in Korean. I shall remain by your side.",
  "feature.bias.persona.closer.tags": "#JoseonDynasty #SweetToYou",
  "feature.bias.persona.closer.streak": "500+ Learning",
} as const;

const koFeatureCopy: Record<keyof typeof featureCopy, string> = {
  "earlyAccess.back": "Baetter로 돌아가기",
  "earlyAccess.close": "사전등록 폼 닫기",
  "earlyAccess.eyebrow": "얼리 액세스 사전 등록",
  "earlyAccess.title": "Baetter와 가장 먼저 한국어로 말해 보세요",
  "earlyAccess.description": "이메일만 남겨주세요. 초대 순서가 되면 가장 먼저 알려드릴게요.",
  "earlyAccess.benefit.invite": "우선 초대와 출시 소식 안내",
  "earlyAccess.benefit.voice": "음성·텍스트·역할극·페르소나 연습",
  "earlyAccess.benefit.feedback": "피드백으로 Baetter를 함께 만드는 기회",
  "earlyAccess.form.title": "사전 등록하기",
  "earlyAccess.form.description": "이메일을 입력하면 얼리 액세스 명단에 등록됩니다.",
  "earlyAccess.form.email": "이메일",
  "earlyAccess.form.consent": "얼리 액세스 및 출시 소식을 이메일로 받는 데 동의합니다.",
  "earlyAccess.form.submit": "얼리 액세스 사전 등록",
  "earlyAccess.form.submitting": "저장 중…",
  "earlyAccess.form.privacy": "입력한 정보는 Baetter 얼리 액세스와 관련 안내에만 사용합니다.",
  "earlyAccess.form.integrationPending":
    "폼 화면이 준비되었습니다. 공통 Supabase 연결이 추가되면 등록이 시작됩니다.",
  "earlyAccess.form.success": "사전 등록이 완료되었습니다. 곧 소식을 전해드릴게요.",
  "earlyAccess.form.error": "등록 정보를 저장하지 못했습니다. 다시 시도해 주세요.",
  "nav.pricing": "요금제",
  "feature.cta": "얼리 액세스 신청",
  "feature.roleplay.number": "1",
  "feature.roleplay.title": "실제로 마주칠 상황을 역할극으로 연습하세요",
  "feature.roleplay.description": "준비될 때마다 실제 대화에 필요한 한국어를 연습하세요.",
  "feature.roleplay.pill.one": "카페, 택시, 친구 만나기 등",
  "feature.roleplay.pill.two": "관심사와 K-pop에 관해 대화하기",
  "feature.roleplay.pill.three": "언제든 말하거나 입력하기",
  "feature.roleplay.phone.title": "아이돌 팬사인회 연습",
  "feature.roleplay.phone.badge": "아이돌 팬사인회 역할극",
  "feature.roleplay.phone.prompt": "이번 새 앨범에 어떤 수록곡이 맘에 들었어?",
  "feature.roleplay.phone.translation": "새 앨범에서 어떤 곡이 마음에 들었나요?",
  "feature.roleplay.tag.roleplay": "역할극",
  "feature.roleplay.tag.travel": "여행",
  "feature.roleplay.tag.cafe": "카페",
  "feature.roleplay.scene.cosmetic": "화장품 사기",
  "feature.roleplay.scene.taxi": "택시 기사",
  "feature.corrections.number": "2",
  "feature.corrections.title": "직접 문장을 만들고\n바로 교정받으세요.",
  "feature.corrections.description":
    "단어 카드 암기가 아닙니다.\n하고 싶은 말을 하면 한국인이 자연스럽게 표현하는 법을 알려드려요.",
  "feature.corrections.voice": "“지금 어디야?”",
  "feature.corrections.question": "어디야?",
  "feature.corrections.answer": "나지금 오고 있어",
  "feature.corrections.feedback": "더 자연스러운 표현",
  "feature.corrections.improved": "나 지금 가고 있어(요)",
  "feature.corrections.explanation":
    "‘나’ 뒤를 띄어 쓰고, 자연스러운 존댓말 역할극에는 ‘가고 있어(요)’를 사용하세요.",
  "feature.bias.number": "3",
  "feature.bias.title": "최애와 한국어로\n대화하세요.",
  "feature.bias.description":
    "팬심을 매일의 연습으로 바꿔 보세요. 아이돌과 캐릭터 같은 페르소나와 몰입감 있게 대화하며 즐겁게 꾸준히 연습할 수 있어요.",
  "feature.bias.benefit.one": "내가 좋아하는 분위기의 페르소나 선택",
  "feature.bias.benefit.two": "부담 없이 이어가는 자연스러운 한국어 대화",
  "feature.bias.benefit.three": "팬심을 매일의 회화 루틴으로",
  "feature.bias.chat.midnight": "오늘은 뭐 배울래?",
  "feature.bias.chat.offrecord": "지금 뭐해?",
  "feature.bias.persona.midnight.name": "한밤의 속삭임",
  "feature.bias.persona.midnight.quote":
    "무대 위에서는 차가운 뮤즈지만, 한밤에는 네가 한국어로 말하는 소리만 듣고 싶어.",
  "feature.bias.persona.midnight.tags": "#비밀수업 #다정한연습",
  "feature.bias.persona.midnight.streak": "학습자 1,000명+",
  "feature.bias.persona.offrecord.name": "비공개 레슨",
  "feature.bias.persona.offrecord.quote":
    "카메라 앞에서는 웃지 않지만, 네가 한국어를 연습하는 걸 들으면 자꾸 미소가 나.",
  "feature.bias.persona.offrecord.tags": "#비밀수업 #다정한연습",
  "feature.bias.persona.offrecord.streak": "학습자 500명+",
  "feature.bias.persona.order.name": "이건 명령이야",
  "feature.bias.persona.order.quote":
    "오늘은 나와 한국어로 말해. 가까이에서 내 말을 따라 한국어로 해 봐.",
  "feature.bias.persona.order.tags": "#군대 #미션",
  "feature.bias.persona.order.streak": "학습자 1,000명+",
  "feature.bias.persona.closer.name": "더 가까이",
  "feature.bias.persona.closer.quote":
    "천천히 해도 괜찮습니다. 마음에 담긴 이야기를 한국어로 들려주세요. 곁에 있겠습니다.",
  "feature.bias.persona.closer.tags": "#조선시대 #다정한연습",
  "feature.bias.persona.closer.streak": "학습자 500명+",
};

const arFeatureCopy: Record<keyof typeof featureCopy, string> = {
  ...featureCopy,
  "nav.pricing": "الأسعار",
  "feature.cta": "اطلب الوصول المبكر",
  "feature.roleplay.number": "١",
  "feature.roleplay.title": "تدرّب بالمحاكاة على المواقف التي ستواجهها فعلاً",
  "feature.roleplay.description": "تدرّب على الكورية المفيدة للمحادثات الحقيقية متى كنت مستعداً.",
  "feature.roleplay.pill.one": "المقاهي وسيارات الأجرة ولقاء الأصدقاء والمزيد",
  "feature.roleplay.pill.two": "تحدّث عن اهتماماتك والكيبوب",
  "feature.roleplay.pill.three": "تكلّم أو اكتب في أي وقت",
  "feature.roleplay.phone.title": "تدرّب على لقاء توقيع مع نجم",
  "feature.roleplay.phone.badge": "محاكاة لقاء توقيع مع نجم",
  "feature.roleplay.phone.prompt": "이번 새 앨범에 어떤 수록곡이 맘에 들었어?",
  "feature.roleplay.phone.translation": "ما الأغاني التي أعجبتك في الألبوم الجديد؟",
  "feature.roleplay.tag.roleplay": "محاكاة",
  "feature.roleplay.tag.travel": "سفر",
  "feature.roleplay.tag.cafe": "مقهى",
  "feature.roleplay.scene.cosmetic": "شراء مستحضرات التجميل",
  "feature.roleplay.scene.taxi": "سائق سيارة أجرة",
  "feature.corrections.number": "٢",
  "feature.corrections.title": "كوّن جملك بنفسك،\nواحصل على تصحيح فوري.",
  "feature.corrections.description":
    "ليست تمارين بطاقات تقليدية.\nقل ما تقصده وشاهد كيف يعبّر عنه الكوريون بصورة طبيعية.",
  "feature.corrections.voice": "«지금 어디야?»",
  "feature.corrections.question": "어디야?",
  "feature.corrections.answer": "나지금 오고 있어",
  "feature.corrections.feedback": "صياغة أفضل",
  "feature.corrections.improved": "나 지금 가고 있어(요)",
  "feature.corrections.explanation":
    "أضف مسافة بعد 나 واستخدم 가고 있어(요) لتعبير طبيعي ومهذب في المحاكاة.",
  "feature.bias.number": "٣",
  "feature.bias.title": "تحدّث مع نجمك المفضل\nبالكورية.",
  "feature.bias.description":
    "حوّل شغفك إلى تدريب يومي. خض محادثات غامرة مع شخصيات مستوحاة من النجوم والقصص، واستمر لأن التعلم ممتع فعلاً.",
  "feature.bias.benefit.one": "اختر شخصية بالأجواء التي تحبها",
  "feature.bias.benefit.two": "واصل محادثات كورية طبيعية بلا ضغط",
  "feature.bias.benefit.three": "حوّل شغفك إلى روتين تحدث يومي",
  "feature.bias.chat.midnight": "오늘은 뭐 배울래?",
  "feature.bias.chat.offrecord": "지금 뭐해?",
  "feature.bias.persona.midnight.name": "همس منتصف الليل",
  "feature.bias.persona.midnight.quote":
    "على المنصة أنا ملهمة باردة وصامتة، لكنني في منتصف الليل أريد فقط سماعك تتحدث بالكورية.",
  "feature.bias.persona.midnight.tags": "#درس_سري #بلطف",
  "feature.bias.persona.midnight.streak": "+١٠٠٠ متعلّم",
  "feature.bias.persona.offrecord.name": "درس بعيداً عن الكاميرا",
  "feature.bias.persona.offrecord.quote":
    "لا أبتسم للكاميرات، لكنني لا أستطيع منع ابتسامتي حين أسمعك تتدرّب على الكورية.",
  "feature.bias.persona.offrecord.tags": "#درس_سري #بلطف",
  "feature.bias.persona.offrecord.streak": "+٥٠٠ متعلّم",
  "feature.bias.persona.order.name": "هذا أمر",
  "feature.bias.persona.order.quote":
    "تحدّث معي بالكورية اليوم. ابق قريباً واتبع إرشادي وقلها بالكورية.",
  "feature.bias.persona.order.tags": "#جيش #مهمة",
  "feature.bias.persona.order.streak": "+١٠٠٠ متعلّم",
  "feature.bias.persona.closer.name": "اقترب أكثر",
  "feature.bias.persona.closer.quote":
    "خذ وقتك يا سيدتي. قل بالكورية ما في قلبك، وسأبقى إلى جانبك.",
  "feature.bias.persona.closer.tags": "#عصر_جوسون #بلطف",
  "feature.bias.persona.closer.streak": "+٥٠٠ متعلّم",
};

export const koKR = {
  ...featureCopy,
  ...koFeatureCopy,
  "nav.menu.open": "메뉴 열기",
  "nav.menu.close": "메뉴 닫기",
  "nav.menu.label": "모바일 메뉴",
  "document.title": "Baetter — AI 한국어 회화 연습",
  brand: "Baetter",
  "nav.label": "주요 메뉴",
  "nav.comparison": "비교",
  "nav.benefits": "장점",
  "nav.cta": "시작하기",
  "locale.label": "언어 선택",
  "locale.ko-KR": "한국어",
  "locale.en-US": "영어",
  "locale.ar": "아랍어",
  "locale.ja-JP": "일본어",
  "locale.vi-VN": "베트남어",
  "locale.th-TH": "태국어",
  "locale.zh-CN": "중국어(간체)",
  "locale.zh-TW": "중국어(번체)",
  "hero.eyebrow": "더 나은 의사결정",
  "hero.title": "언제 어디서나 실제 한국어 대화를 소리 내어 연습하세요",
  "hero.description":
    "배운 단어를 이제 직접 말해 보세요. 실제 상황을 역할극으로 연습하고 즉시 교정받으며, 언제나 함께하는 AI로 최애와도 대화할 수 있어요.",
  "hero.action": "얼리 액세스 신청",
  "hero.preview": "AI 회화 미리보기",
  "hero.highlight.roleplay": "실전 상황 역할극",
  "hero.highlight.corrections": "말하는 즉시 자연스럽게 교정",
  "hero.highlight.personas": "좋아하는 페르소나와 매일 대화",
  "comparison.title": "더 명확한 경로를 선택하세요",
  "comparison.region": "스크롤 가능한 접근 방식 비교",
  "comparison.table": "접근 방식 비교",
  "comparison.criterion": "기준",
  "comparison.product": "Baetter",
  "comparison.alternative": "임시 방식",
  "comparison.setup.criterion": "설정",
  "comparison.setup.product": "공유되고 준비됨",
  "comparison.setup.alternative": "매번 다시 구축",
  "comparison.brand.criterion": "브랜드 일관성",
  "comparison.brand.product": "토큰 기반",
  "comparison.brand.alternative": "수동 검토",
  "comparison.extension.criterion": "실험 UI",
  "comparison.extension.product": "로컬 조합 가능",
  "comparison.extension.alternative": "전역 결합",
  "nav.proof": "Baetter를 선택하는 이유",
  "proof.title": "외우는 공부를, 실제로 말하는 연습으로",
  "proof.markets.value": "3가지",
  "proof.markets.label": "역할극 · 즉시 교정 · 최애 대화",
  "proof.reuse.value": "24/7",
  "proof.reuse.label": "언제든 기다리는 AI 회화 파트너",
  "proof.launch.value": "즉시",
  "proof.launch.label": "말한 문장을 자연스러운 한국어로 교정",
  "features.title": "트레이드오프를 보여주는 시스템",
  "features.clarity.title": "명확한\n경계",
  "features.clarity.description": "공통 책임과 로컬 책임을\n쉽게 구분할 수 있습니다.",
  "features.access.title": "접근 가능한 기본값",
  "features.access.description": "시맨틱 구조와 보이는 포커스가 기반부터 적용됩니다.",
  "features.global.title": "글로벌 도달",
  "features.global.description": "유연한 레이아웃이 다양한 기기와 긴 번역문을 수용합니다.",
  "cta.title": "첫 한국어 대화, 누구보다 먼저 시작하세요",
  "cta.description":
    "이메일 하나면 신청 완료. Baetter 출시와 얼리 액세스 초대를 가장 먼저 보내드릴게요.",
  "cta.action": "내 자리 먼저 예약하기",
  "cta.badge": "선착순 얼리 액세스",
  "cta.note.card": "카드 불필요",
  "cta.note.access": "언제든 플랜 변경 가능",
  "cta.ghost.start": "SPEAK",
  "cta.ghost.end": "KOREAN",
  "pricing.kicker": "내 학습 리듬에 맞는 플랜",
  "pricing.title": "부담 없이 시작하고, 원하는 만큼 말하세요",
  "pricing.subtitle": "가볍게 연습하는 첫 대화부터\n매일 몰입하는 한국어 루틴까지.",
  "pricing.unit": "/월",
  "pricing.billing.monthly": "월간",
  "pricing.billing.annual": "연간",
  "pricing.billing.save": "20% 절약",
  "pricing.badge.popular": "인기",
  "pricing.free.name": "무료",
  "pricing.free.description": "Baetter의 핵심 회화 경험을 가볍게 체험해 보세요.",
  "pricing.free.cta": "무료로 연습하기",
  "pricing.free.feature.clips": "기본 상황별 역할극",
  "pricing.free.feature.captions": "문장 교정과 더 자연스러운 표현",
  "pricing.free.feature.saved": "텍스트로 말하기 연습",
  "pricing.plus.name": "플러스",
  "pricing.plus.description": "매일 말하는 습관을 만들고 싶은 학습자를 위한 플랜.",
  "pricing.plus.cta": "Plus로 계속 말하기",
  "pricing.plus.feature.unlimited": "무제한 상황별 역할극",
  "pricing.plus.feature.import": "음성·텍스트 회화 연습",
  "pricing.plus.feature.offline": "상세한 즉시 교정",
  "pricing.plus.feature.reminders": "연속 학습 기록과 리마인더",
  "pricing.premium.name": "프리미엄",
  "pricing.premium.description": "최애 persona와 더 깊고 다양한 대화를 원하는 학습자를 위한 플랜.",
  "pricing.premium.cta": "Premium 시작하기",
  "pricing.premium.feature.pronunciation": "모든 AI persona 대화",
  "pricing.premium.feature.subtitles": "발음·말하기 피드백",
  "pricing.premium.feature.collections": "표현 저장과 복습 컬렉션",
  "pricing.premium.feature.priority": "새 시나리오 우선 이용",
  "pricing.footer": "플랜은 자동 갱신됩니다. 계정 설정에서 언제든 취소할 수 있습니다.",
  "footer.message": "글로벌 팀을 위해 제작",
  "footer.top": "맨 위로",
  "footer.label": "Baetter 푸터",
  "footer.links.label": "언어 링크",
  "footer.policy.label": "정책 링크",
  "footer.faq.label": "자주 묻는 질문",
  "footer.faq.heading": "자주 묻는 질문",
  "footer.faq.teams.question": "한국어 초보자도 사용할 수 있나요?",
  "footer.faq.teams.answer":
    "네. 짧은 문장과 익숙한 상황부터 시작하고, AI 교정을 보며 내 속도에 맞게 표현을 확장할 수 있어요.",
  "footer.faq.comparison.question": "AI는 제 문장을 어떻게 교정하나요?",
  "footer.faq.comparison.answer":
    "문법만 고치는 것이 아니라 대화 상황에 맞는 띄어쓰기, 높임말, 더 자연스러운 표현을 함께 제안해요.",
  "footer.faq.practice.question": "말하기와 텍스트 연습을 모두 할 수 있나요?",
  "footer.faq.practice.answer":
    "네. 조용한 곳에서는 텍스트로, 실제 말하기를 연습하고 싶을 때는 음성으로 같은 시나리오를 이어갈 수 있어요.",
  "footer.faq.personas.question": "AI persona는 실제 인물인가요?",
  "footer.faq.personas.answer":
    "아니요. Baetter의 persona는 학습 몰입을 돕기 위해 만든 가상의 AI 캐릭터이며 실제 연예인이나 특정 인물을 대변하지 않아요.",
  "footer.faq.plans.question": "플랜은 언제든 변경하거나 취소할 수 있나요?",
  "footer.faq.plans.answer":
    "네. 계정 설정에서 언제든 플랜을 변경하거나 다음 결제 전에 취소할 수 있어요. 무료 플랜으로도 기본 회화 연습은 계속할 수 있습니다.",
  "footer.faq.privacy.question": "내 음성과 대화 내용은 어떻게 처리되나요?",
  "footer.faq.privacy.answer":
    "연습에 필요한 범위에서만 처리하며, 저장·삭제 범위는 계정 설정에서 확인하고 관리할 수 있도록 설계합니다.",
  "footer.privacy": "개인정보 처리방침",
  "footer.terms": "이용약관",
  "footer.copyright": "© 2026 Baetter. 모든 권리 보유.",
} as const;
export const enUS: Record<keyof typeof koKR, string> = {
  ...featureCopy,
  "nav.menu.open": "Open menu",
  "nav.menu.close": "Close menu",
  "nav.menu.label": "Mobile menu",
  "document.title": "Baetter — AI Korean conversation practice",
  "locale.label": "Choose language",
  "locale.ko-KR": "Korean",
  "locale.en-US": "English",
  "locale.ar": "Arabic",
  "locale.ja-JP": "Japanese",
  "locale.vi-VN": "Vietnamese",
  "locale.th-TH": "Thai",
  "locale.zh-CN": "Chinese (Simplified)",
  "locale.zh-TW": "Chinese (Traditional)",
  brand: "Baetter",
  "nav.label": "Primary",
  "nav.comparison": "Comparison",
  "nav.benefits": "Benefits",
  "nav.cta": "Start speaking",
  "hero.eyebrow": "A better way to decide",
  "hero.title": "Practice real Korean Conversations - out loud, anytime",
  "hero.description":
    "You've learned the words. Now actually say them. Role-play real situations, get corrected on the spot, and even chat with your favorite idol - with an AI that's always on.",
  "hero.action": "Get Early Access",
  "hero.preview": "AI conversation preview",
  "hero.highlight.roleplay": "Real-life Korean role-play",
  "hero.highlight.corrections": "Natural corrections as you speak",
  "hero.highlight.personas": "Daily chats with personas you love",
  "comparison.title": "Choose the clearer path",
  "comparison.region": "Scrollable approach comparison",
  "comparison.table": "Approach comparison",
  "comparison.criterion": "Criterion",
  "comparison.product": "Baetter",
  "comparison.alternative": "Ad hoc",
  "comparison.setup.criterion": "Setup",
  "comparison.setup.product": "Shared and ready",
  "comparison.setup.alternative": "Rebuilt every time",
  "comparison.brand.criterion": "Brand consistency",
  "comparison.brand.product": "Token driven",
  "comparison.brand.alternative": "Manually reviewed",
  "comparison.extension.criterion": "Experiment UI",
  "comparison.extension.product": "Locally composable",
  "comparison.extension.alternative": "Globally coupled",
  "nav.proof": "Why Baetter",
  "proof.title": "Turn words you know into conversations you can have",
  "proof.markets.value": "3 ways",
  "proof.markets.label": "Role-play, instant corrections, and persona chat",
  "proof.reuse.value": "24/7",
  "proof.reuse.label": "An AI conversation partner ready whenever you are",
  "proof.launch.value": "Instant",
  "proof.launch.label": "Natural Korean corrections while you speak",
  "features.title": "A system that makes tradeoffs visible",
  "features.clarity.title": "Clear\nboundaries",
  "features.clarity.description": "Shared and local responsibilities\nremain easy to see.",
  "features.access.title": "Accessible defaults",
  "features.access.description": "Semantic structure and visible focus begin at the foundation.",
  "features.global.title": "Global reach",
  "features.global.description": "Flexible layouts accommodate devices and longer translations.",
  "cta.title": "Start your first Korean conversation before anyone else",
  "cta.description":
    "One email is all it takes. Be first to receive your Baetter early-access invitation.",
  "cta.action": "Reserve my spot",
  "cta.badge": "Limited early access",
  "cta.note.card": "No card required",
  "cta.note.access": "Change your plan anytime",
  "cta.ghost.start": "SPEAK",
  "cta.ghost.end": "KOREAN",
  "pricing.kicker": "A plan for your learning rhythm",
  "pricing.title": "Start comfortably. Speak as much as you want.",
  "pricing.subtitle":
    "From your first low-pressure conversation\nto a daily immersive Korean routine.",
  "pricing.unit": "/mo",
  "pricing.billing.monthly": "Monthly",
  "pricing.billing.annual": "Annual",
  "pricing.billing.save": "Save 20%",
  "pricing.badge.popular": "Popular",
  "pricing.free.name": "Free",
  "pricing.free.description": "Try the essential Baetter conversation experience at your own pace.",
  "pricing.free.cta": "Practice for free",
  "pricing.free.feature.clips": "Essential real-life role-plays",
  "pricing.free.feature.captions": "Sentence corrections and natural alternatives",
  "pricing.free.feature.saved": "Text conversation practice",
  "pricing.plus.name": "Plus",
  "pricing.plus.description": "For learners who want to build a daily speaking habit.",
  "pricing.plus.cta": "Keep speaking with Plus",
  "pricing.plus.feature.unlimited": "Unlimited situational role-plays",
  "pricing.plus.feature.import": "Voice and text conversation practice",
  "pricing.plus.feature.offline": "Detailed instant corrections",
  "pricing.plus.feature.reminders": "Learning streaks and reminders",
  "pricing.premium.name": "Premium",
  "pricing.premium.description":
    "For learners who want deeper, more varied conversations with favorite personas.",
  "pricing.premium.cta": "Start Premium",
  "pricing.premium.feature.pronunciation": "Every AI persona conversation",
  "pricing.premium.feature.subtitles": "Pronunciation and speaking feedback",
  "pricing.premium.feature.collections": "Saved expression review collections",
  "pricing.premium.feature.priority": "Early access to new scenarios",
  "pricing.footer": "Plans renew automatically. Cancel anytime from your account settings.",
  "footer.message": "Built for global teams",
  "footer.top": "Back to top",
  "footer.label": "Baetter footer",
  "footer.links.label": "Language links",
  "footer.policy.label": "Policy links",
  "footer.faq.label": "Frequently asked questions",
  "footer.faq.heading": "Frequently asked questions",
  "footer.faq.teams.question": "Can complete beginners use Baetter?",
  "footer.faq.teams.answer":
    "Yes. Start with short phrases and familiar situations, then expand at your pace with clear AI corrections.",
  "footer.faq.comparison.question": "How does the AI correct my Korean?",
  "footer.faq.comparison.answer":
    "It goes beyond grammar to suggest spacing, politeness, and more natural expressions for the conversation you're having.",
  "footer.faq.practice.question": "Can I practice with both voice and text?",
  "footer.faq.practice.answer":
    "Yes. Use text when you need quiet practice, then continue the same scenarios with voice when you want to train real speaking.",
  "footer.faq.personas.question": "Are the AI personas real people?",
  "footer.faq.personas.answer":
    "No. Baetter personas are fictional AI characters designed for immersive practice and do not represent real celebrities or individuals.",
  "footer.faq.plans.question": "Can I change or cancel my plan anytime?",
  "footer.faq.plans.answer":
    "Yes. Change your plan or cancel before the next billing date from account settings. Essential conversation practice remains available on Free.",
  "footer.faq.privacy.question": "How are my voice and conversations handled?",
  "footer.faq.privacy.answer":
    "They are processed only as needed for practice, with clear account controls for reviewing retention and managing deletion.",
  "footer.privacy": "Privacy",
  "footer.terms": "Terms",
  "footer.copyright": "© 2026 Baetter. All rights reserved.",
};
export const ar: Record<keyof typeof koKR, string> = {
  ...featureCopy,
  ...arFeatureCopy,
  "nav.menu.open": "افتح القائمة",
  "nav.menu.close": "أغلق القائمة",
  "nav.menu.label": "قائمة الجوال",
  "document.title": "Baetter — تدريب محادثة كورية بالذكاء الاصطناعي",
  "locale.label": "اختر اللغة",
  "locale.ko-KR": "الكورية",
  "locale.en-US": "الإنجليزية",
  "locale.ar": "العربية",
  "locale.ja-JP": "اليابانية",
  "locale.vi-VN": "الفيتنامية",
  "locale.th-TH": "التايلاندية",
  "locale.zh-CN": "الصينية المبسطة",
  "locale.zh-TW": "الصينية التقليدية",
  brand: "Baetter",
  "nav.label": "التنقل الرئيسي",
  "nav.comparison": "المقارنة",
  "nav.benefits": "الفوائد",
  "nav.cta": "ابدأ التحدث",
  "hero.eyebrow": "طريقة أفضل للقرار",
  "hero.title": "تدرّب بصوت عالٍ على محادثات كورية حقيقية في أي وقت",
  "hero.description":
    "لقد تعلمت الكلمات، والآن حان وقت نطقها. حاكِ مواقف حقيقية واحصل على تصحيح فوري، وتحدّث حتى مع نجمك المفضل بمساعدة ذكاء اصطناعي متاح دائماً.",
  "hero.action": "احصل على وصول مبكر",
  "hero.preview": "معاينة محادثة بالذكاء الاصطناعي",
  "hero.highlight.roleplay": "تمثيل أدوار لمواقف كورية حقيقية",
  "hero.highlight.corrections": "تصحيح طبيعي أثناء التحدث",
  "hero.highlight.personas": "محادثات يومية مع شخصيات تحبها",
  "comparison.title": "اختر المسار الأوضح",
  "comparison.region": "مقارنة أساليب قابلة للتمرير",
  "comparison.table": "مقارنة الأساليب",
  "comparison.criterion": "المعيار",
  "comparison.product": "لوما",
  "comparison.alternative": "حل مؤقت",
  "comparison.setup.criterion": "الإعداد",
  "comparison.setup.product": "مشترك وجاهز",
  "comparison.setup.alternative": "يُعاد بناؤه كل مرة",
  "comparison.brand.criterion": "اتساق العلامة",
  "comparison.brand.product": "مدعوم بالرموز",
  "comparison.brand.alternative": "مراجعة يدوية",
  "comparison.extension.criterion": "واجهة التجربة",
  "comparison.extension.product": "قابلة للتركيب محلياً",
  "comparison.extension.alternative": "مقترنة عالمياً",
  "nav.proof": "لماذا Baetter",
  "proof.title": "حوّل الكلمات التي تعرفها إلى محادثات تستطيع خوضها",
  "proof.markets.value": "٣ طرق",
  "proof.markets.label": "تمثيل أدوار وتصحيح فوري ودردشة مع الشخصيات",
  "proof.reuse.value": "٢٤/٧",
  "proof.reuse.label": "شريك محادثة ذكي جاهز متى أردت",
  "proof.launch.value": "فوري",
  "proof.launch.label": "تصحيح كوري طبيعي أثناء حديثك",
  "features.title": "نظام يوضح المفاضلات",
  "features.clarity.title": "حدود\nواضحة",
  "features.clarity.description": "تبقى المسؤوليات المشتركة والمحلية\nسهلة الرؤية.",
  "features.access.title": "إعدادات ميسّرة",
  "features.access.description": "تبدأ البنية الدلالية والتركيز المرئي من الأساس.",
  "features.global.title": "وصول عالمي",
  "features.global.description": "تستوعب التخطيطات المرنة الأجهزة والترجمات الأطول.",
  "cta.title": "ابدأ أول محادثة كورية قبل الجميع",
  "cta.description": "بريد إلكتروني واحد يكفي. كن أول من يتلقى دعوة الوصول المبكر إلى Baetter.",
  "cta.action": "احجز مكاني",
  "cta.badge": "وصول مبكر محدود",
  "cta.note.card": "بدون بطاقة",
  "cta.note.access": "غيّر خطتك في أي وقت",
  "cta.ghost.start": "تحدث",
  "cta.ghost.end": "بالكورية",
  "pricing.kicker": "خطة تناسب إيقاع تعلمك",
  "pricing.title": "ابدأ براحة وتحدث بقدر ما تريد",
  "pricing.subtitle": "من أول محادثة بلا ضغط\nإلى روتين كوري يومي غامر.",
  "pricing.unit": "/شهر",
  "pricing.billing.monthly": "شهري",
  "pricing.billing.annual": "سنوي",
  "pricing.billing.save": "وفّر 20%",
  "pricing.badge.popular": "الأكثر رواجًا",
  "pricing.free.name": "مجاني",
  "pricing.free.description": "جرّب تجربة المحادثة الأساسية في Baetter وفق سرعتك.",
  "pricing.free.cta": "تدرّب مجاناً",
  "pricing.free.feature.clips": "تمثيل أدوار في مواقف أساسية",
  "pricing.free.feature.captions": "تصحيح الجمل وبدائل طبيعية",
  "pricing.free.feature.saved": "تدريب محادثة نصية",
  "pricing.plus.name": "بلس",
  "pricing.plus.description": "للمتعلمين الذين يريدون بناء عادة تحدث يومية.",
  "pricing.plus.cta": "واصل الحديث مع Plus",
  "pricing.plus.feature.unlimited": "تمثيل أدوار غير محدود",
  "pricing.plus.feature.import": "محادثات صوتية ونصية",
  "pricing.plus.feature.offline": "تصحيحات فورية مفصلة",
  "pricing.plus.feature.reminders": "سلسلة تعلم وتذكيرات",
  "pricing.premium.name": "بريميوم",
  "pricing.premium.description": "لمن يريد محادثات أعمق وأكثر تنوعاً مع الشخصيات المفضلة.",
  "pricing.premium.cta": "ابدأ Premium",
  "pricing.premium.feature.pronunciation": "جميع محادثات الشخصيات الذكية",
  "pricing.premium.feature.subtitles": "ملاحظات على النطق والتحدث",
  "pricing.premium.feature.collections": "مجموعات لحفظ التعبيرات ومراجعتها",
  "pricing.premium.feature.priority": "وصول مبكر إلى السيناريوهات الجديدة",
  "pricing.footer": "تتجدد الخطط تلقائياً. يمكنك الإلغاء في أي وقت من إعدادات حسابك.",
  "footer.message": "صُمم للفرق العالمية",
  "footer.top": "العودة إلى الأعلى",
  "footer.label": "تذييل Baetter",
  "footer.links.label": "روابط اللغة",
  "footer.policy.label": "روابط السياسات",
  "footer.faq.label": "الأسئلة الشائعة",
  "footer.faq.heading": "الأسئلة الشائعة",
  "footer.faq.teams.question": "هل يستطيع المبتدئون تماماً استخدام Baetter؟",
  "footer.faq.teams.answer":
    "نعم. ابدأ بعبارات قصيرة ومواقف مألوفة، ثم توسع وفق سرعتك مع تصحيحات واضحة من الذكاء الاصطناعي.",
  "footer.faq.comparison.question": "كيف يصحح الذكاء الاصطناعي لغتي الكورية؟",
  "footer.faq.comparison.answer":
    "يتجاوز القواعد ليقترح المسافات ودرجات الاحترام وتعبيرات أكثر طبيعية تناسب سياق محادثتك.",
  "footer.faq.practice.question": "هل يمكنني التدرب بالصوت والنص معاً؟",
  "footer.faq.practice.answer":
    "نعم. استخدم النص عندما تحتاج إلى تدريب هادئ، ثم تابع السيناريو نفسه بالصوت عندما تريد ممارسة التحدث الحقيقي.",
  "footer.faq.personas.question": "هل شخصيات الذكاء الاصطناعي أشخاص حقيقيون؟",
  "footer.faq.personas.answer":
    "لا. شخصيات Baetter خيالية ومصممة لتدريب غامر، ولا تمثل مشاهير أو أفراداً حقيقيين.",
  "footer.faq.plans.question": "هل يمكنني تغيير خطتي أو إلغاؤها في أي وقت؟",
  "footer.faq.plans.answer":
    "نعم. يمكنك تغيير الخطة أو الإلغاء قبل موعد الفوترة التالي من إعدادات الحساب، مع بقاء التدريب الأساسي متاحاً في الخطة المجانية.",
  "footer.faq.privacy.question": "كيف يتم التعامل مع صوتي ومحادثاتي؟",
  "footer.faq.privacy.answer":
    "تُعالج بالقدر اللازم للتدريب فقط، مع أدوات واضحة في الحساب لمراجعة مدة الاحتفاظ وإدارة الحذف.",
  "footer.privacy": "الخصوصية",
  "footer.terms": "الشروط",
  "footer.copyright": "© 2026 Baetter. جميع الحقوق محفوظة.",
};

export const jaJP: Record<keyof typeof koKR, string> = {
  ...enUS,
  "nav.pricing": "料金プラン",
  "feature.cta": "早期アクセスに登録",
  "nav.menu.open": "メニューを開く",
  "nav.menu.close": "メニューを閉じる",
  "nav.menu.label": "モバイルメニュー",
  "document.title": "Baetter — AI韓国語会話練習",
  "locale.label": "言語を選択",
  "locale.ko-KR": "韓国語",
  "locale.en-US": "英語",
  "locale.ar": "アラビア語",
  "locale.ja-JP": "日本語",
  "locale.vi-VN": "ベトナム語",
  "locale.th-TH": "タイ語",
  "locale.zh-CN": "中国語（簡体字）",
  "locale.zh-TW": "中国語（繁体字）",
  "nav.label": "メインナビゲーション",
  "nav.cta": "話してみる",
  "nav.proof": "Baetterが選ばれる理由",
  "hero.title": "いつでも、声に出してリアルな韓国語会話を練習",
  "hero.description":
    "覚えた単語を、実際に話してみましょう。リアルな場面をロールプレイし、その場で添削を受け、好きなペルソナとも会話できます。",
  "hero.action": "早期アクセスに登録",
  "hero.preview": "AI会話プレビュー",
  "hero.highlight.roleplay": "実際の場面でロールプレイ",
  "hero.highlight.corrections": "話しながら自然な表現に添削",
  "hero.highlight.personas": "好きなペルソナと毎日会話",
  "proof.title": "知っている単語を、話せる会話へ",
  "proof.markets.value": "3つ",
  "proof.markets.label": "ロールプレイ・即時添削・ペルソナ会話",
  "proof.reuse.label": "いつでも待っているAI会話パートナー",
  "proof.launch.value": "即時",
  "proof.launch.label": "話した韓国語を自然な表現に添削",
  "feature.roleplay.title": "本当に出会う場面を\nロールプレイで練習",
  "feature.roleplay.description": "実際の会話で使える韓国語を、いつでも練習できます。",
  "feature.roleplay.pill.one": "カフェ、タクシー、友達との会話など",
  "feature.roleplay.pill.two": "趣味やK-POPについて会話",
  "feature.roleplay.pill.three": "音声でもテキストでも練習",
  "feature.roleplay.phone.title": "アイドルのサイン会を練習",
  "feature.roleplay.phone.badge": "アイドルサイン会ロールプレイ",
  "feature.roleplay.phone.translation": "新しいアルバムで、どの曲が気に入りましたか？",
  "feature.roleplay.tag.roleplay": "ロールプレイ",
  "feature.roleplay.tag.travel": "旅行",
  "feature.roleplay.tag.cafe": "カフェ",
  "feature.roleplay.scene.cosmetic": "コスメを買う",
  "feature.roleplay.scene.taxi": "タクシー運転手",
  "feature.corrections.title": "自分の文を作って\nすぐに添削。",
  "feature.corrections.description":
    "単語カードの暗記ではありません。\n伝えたいことを話すと、自然な韓国語を提案します。",
  "feature.corrections.feedback": "より自然な表現",
  "feature.corrections.explanation":
    "「나」の後に空白を入れ、自然で丁寧な会話には「가고 있어(요)」を使います。",
  "feature.bias.title": "推しと韓国語で\n話そう。",
  "feature.bias.description":
    "好きな気持ちを毎日の練習に。魅力的なAIペルソナとの没入会話で、楽しく続けられます。",
  "feature.bias.benefit.one": "好きな雰囲気のペルソナを選択",
  "feature.bias.benefit.two": "プレッシャーなく自然な会話を継続",
  "feature.bias.benefit.three": "毎日のスピーキング習慣に",
  "feature.bias.persona.midnight.name": "真夜中のささやき",
  "feature.bias.persona.midnight.quote":
    "ステージではクールなミューズ。でも真夜中は、あなたが韓国語を話す声だけを聞きたい。",
  "feature.bias.persona.midnight.tags": "#秘密のレッスン #やさしく",
  "feature.bias.persona.midnight.streak": "学習者1,000人+",
  "feature.bias.persona.offrecord.name": "オフレコレッスン",
  "feature.bias.persona.offrecord.quote":
    "カメラには笑わないけど、あなたの韓国語練習を聞くと笑顔になる。",
  "feature.bias.persona.offrecord.tags": "#秘密のレッスン #やさしく",
  "feature.bias.persona.offrecord.streak": "学習者500人+",
  "feature.bias.persona.order.name": "これは命令だ",
  "feature.bias.persona.order.quote":
    "今日は私と韓国語で話そう。そばで私についてきて、韓国語で言ってみて。",
  "feature.bias.persona.order.tags": "#軍隊 #ミッション",
  "feature.bias.persona.order.streak": "学習者1,000人+",
  "feature.bias.persona.closer.name": "もっと近くへ",
  "feature.bias.persona.closer.quote":
    "ゆっくりで大丈夫。心にあることを韓国語で話してください。そばにいます。",
  "feature.bias.persona.closer.tags": "#朝鮮時代 #やさしく",
  "feature.bias.persona.closer.streak": "学習者500人+",
  "cta.title": "最初の韓国語会話を、誰よりも早く",
  "cta.description":
    "メールアドレスだけで登録完了。Baetterの早期アクセス招待を優先してお届けします。",
  "cta.action": "先に席を予約する",
  "cta.badge": "人数限定・早期アクセス",
  "cta.note.card": "カード不要",
  "cta.note.access": "いつでもプラン変更可能",
  "pricing.kicker": "学習ペースに合うプラン",
  "pricing.title": "気軽に始めて、好きなだけ話そう",
  "pricing.subtitle": "最初の会話から\n毎日の没入型韓国語ルーティンまで。",
  "pricing.unit": "/月",
  "pricing.billing.monthly": "月払い",
  "pricing.billing.annual": "年払い",
  "pricing.billing.save": "20%お得",
  "pricing.badge.popular": "人気",
  "pricing.free.name": "無料",
  "pricing.free.description": "Baetterの基本会話を気軽に体験。",
  "pricing.free.cta": "無料で練習",
  "pricing.plus.description": "毎日話す習慣を作りたい学習者向け。",
  "pricing.plus.cta": "Plusで続ける",
  "pricing.premium.description": "好きなペルソナともっと深く多彩に話したい学習者向け。",
  "pricing.premium.cta": "Premiumを始める",
  "pricing.footer": "プランは自動更新されます。アカウント設定からいつでも解約できます。",
  "footer.label": "Baetterフッター",
  "footer.policy.label": "ポリシーリンク",
  "footer.faq.label": "よくある質問",
  "footer.faq.heading": "よくある質問",
  "footer.faq.teams.question": "初心者でも使えますか？",
  "footer.faq.teams.answer":
    "はい。短いフレーズと身近な場面から始め、AIの添削を見ながら自分のペースで広げられます。",
  "footer.faq.comparison.question": "AIはどのように韓国語を添削しますか？",
  "footer.faq.comparison.answer":
    "文法だけでなく、分かち書き、敬語、会話に合う自然な表現も提案します。",
  "footer.faq.practice.question": "音声とテキストの両方で練習できますか？",
  "footer.faq.practice.answer": "はい。同じシナリオをテキストでも音声でも続けられます。",
  "footer.faq.personas.question": "AIペルソナは実在の人物ですか？",
  "footer.faq.personas.answer": "いいえ。学習の没入感を高める架空のAIキャラクターです。",
  "footer.faq.plans.question": "いつでも変更・解約できますか？",
  "footer.faq.plans.answer": "はい。アカウント設定から次回請求前に変更または解約できます。",
  "footer.faq.privacy.question": "音声と会話はどう扱われますか？",
  "footer.faq.privacy.answer":
    "練習に必要な範囲だけで処理し、保存と削除をアカウントで管理できます。",
  "footer.privacy": "プライバシー",
  "footer.terms": "利用規約",
  "footer.copyright": "© 2026 Baetter. All rights reserved.",
};

export const viVN: Record<keyof typeof koKR, string> = {
  ...enUS,
  "nav.pricing": "Bảng giá",
  "feature.cta": "Đăng ký truy cập sớm",
  "nav.menu.open": "Mở menu",
  "nav.menu.close": "Đóng menu",
  "nav.menu.label": "Menu di động",
  "document.title": "Baetter — Luyện hội thoại tiếng Hàn với AI",
  "locale.label": "Chọn ngôn ngữ",
  "locale.ko-KR": "Tiếng Hàn",
  "locale.en-US": "Tiếng Anh",
  "locale.ar": "Tiếng Ả Rập",
  "locale.ja-JP": "Tiếng Nhật",
  "locale.vi-VN": "Tiếng Việt",
  "locale.th-TH": "Tiếng Thái",
  "locale.zh-CN": "Tiếng Trung (Giản thể)",
  "locale.zh-TW": "Tiếng Trung (Phồn thể)",
  "nav.label": "Điều hướng chính",
  "nav.cta": "Bắt đầu nói",
  "nav.proof": "Vì sao chọn Baetter",
  "hero.title": "Luyện hội thoại tiếng Hàn thực tế bằng giọng nói, mọi lúc",
  "hero.description":
    "Bạn đã học từ vựng. Giờ hãy thật sự nói: nhập vai tình huống thực tế, được sửa ngay và trò chuyện với persona yêu thích.",
  "hero.action": "Đăng ký truy cập sớm",
  "hero.preview": "Xem trước hội thoại AI",
  "hero.highlight.roleplay": "Nhập vai tình huống thực tế",
  "hero.highlight.corrections": "Sửa câu tự nhiên ngay khi nói",
  "hero.highlight.personas": "Trò chuyện hằng ngày với persona yêu thích",
  "proof.title": "Biến từ đã biết thành cuộc hội thoại thật",
  "proof.markets.value": "3 cách",
  "proof.markets.label": "Nhập vai · sửa tức thì · trò chuyện persona",
  "proof.reuse.label": "Bạn đồng hành hội thoại AI luôn sẵn sàng",
  "proof.launch.value": "Tức thì",
  "proof.launch.label": "Sửa tiếng Hàn tự nhiên khi bạn nói",
  "feature.roleplay.title": "Nhập vai những tình huống\nbạn thực sự gặp",
  "feature.roleplay.description": "Luyện tiếng Hàn hữu ích cho hội thoại thực tế bất cứ lúc nào.",
  "feature.roleplay.pill.one": "Quán cà phê, taxi, gặp bạn bè và hơn thế",
  "feature.roleplay.pill.two": "Trò chuyện về sở thích và K-pop",
  "feature.roleplay.pill.three": "Nói hoặc nhập văn bản bất cứ lúc nào",
  "feature.corrections.title": "Tự tạo câu,\nđược sửa ngay.",
  "feature.corrections.description":
    "Không phải học thẻ từ.\nHãy nói điều bạn muốn và xem cách diễn đạt tự nhiên.",
  "feature.corrections.feedback": "Cách nói tự nhiên hơn",
  "feature.bias.title": "Trò chuyện với bias\nbằng tiếng Hàn.",
  "feature.bias.description":
    "Biến tình yêu thần tượng thành thói quen luyện tập mỗi ngày với các persona AI cuốn hút.",
  "feature.bias.benefit.one": "Chọn persona có phong cách bạn thích",
  "feature.bias.benefit.two": "Duy trì hội thoại tự nhiên không áp lực",
  "feature.bias.benefit.three": "Tạo thói quen nói mỗi ngày",
  "feature.roleplay.phone.title": "Luyện buổi ký tặng idol",
  "feature.roleplay.phone.badge": "Nhập vai buổi ký tặng idol",
  "feature.roleplay.phone.translation": "Bạn thích bài nào trong album mới?",
  "feature.roleplay.tag.roleplay": "Nhập vai",
  "feature.roleplay.tag.travel": "Du lịch",
  "feature.roleplay.tag.cafe": "Cà phê",
  "feature.roleplay.scene.cosmetic": "Mua mỹ phẩm",
  "feature.roleplay.scene.taxi": "Tài xế taxi",
  "feature.corrections.explanation":
    "Thêm khoảng trắng sau 나 và dùng 가고 있어(요) để câu nói tự nhiên, lịch sự hơn.",
  "feature.bias.persona.midnight.name": "Lời thì thầm nửa đêm",
  "feature.bias.persona.midnight.quote":
    "Trên sân khấu tôi là nàng thơ lạnh lùng, nhưng nửa đêm tôi chỉ muốn nghe bạn nói tiếng Hàn.",
  "feature.bias.persona.midnight.tags": "#BàiHọcBíMật #DịuDàng",
  "feature.bias.persona.midnight.streak": "1.000+ người học",
  "feature.bias.persona.offrecord.name": "Buổi học ngoài ống kính",
  "feature.bias.persona.offrecord.quote":
    "Tôi không cười trước máy quay, nhưng luôn mỉm cười khi nghe bạn luyện tiếng Hàn.",
  "feature.bias.persona.offrecord.tags": "#BàiHọcBíMật #DịuDàng",
  "feature.bias.persona.offrecord.streak": "500+ người học",
  "feature.bias.persona.order.name": "Đây là mệnh lệnh",
  "feature.bias.persona.order.quote":
    "Hôm nay hãy nói tiếng Hàn cùng tôi. Ở gần và nói theo tôi nhé.",
  "feature.bias.persona.order.tags": "#QuânĐội #NhiệmVụ",
  "feature.bias.persona.order.streak": "1.000+ người học",
  "feature.bias.persona.closer.name": "Lại gần hơn",
  "feature.bias.persona.closer.quote":
    "Cứ từ từ. Hãy nói điều trong lòng bằng tiếng Hàn, tôi sẽ ở bên bạn.",
  "feature.bias.persona.closer.tags": "#ThờiJoseon #DịuDàng",
  "feature.bias.persona.closer.streak": "500+ người học",
  "cta.title": "Bắt đầu cuộc trò chuyện tiếng Hàn trước mọi người",
  "cta.description":
    "Chỉ cần một email. Bạn sẽ là người đầu tiên nhận lời mời truy cập sớm Baetter.",
  "cta.action": "Giữ chỗ cho tôi",
  "cta.badge": "Quyền truy cập sớm có hạn",
  "cta.note.card": "Không cần thẻ",
  "cta.note.access": "Đổi gói bất cứ lúc nào",
  "pricing.kicker": "Gói phù hợp nhịp học của bạn",
  "pricing.title": "Bắt đầu nhẹ nhàng, nói bao nhiêu tùy thích",
  "pricing.subtitle": "Từ cuộc hội thoại đầu tiên\nđến thói quen tiếng Hàn mỗi ngày.",
  "pricing.unit": "/tháng",
  "pricing.billing.monthly": "Hàng tháng",
  "pricing.billing.annual": "Hàng năm",
  "pricing.billing.save": "Tiết kiệm 20%",
  "pricing.badge.popular": "Phổ biến",
  "pricing.free.name": "Miễn phí",
  "pricing.free.description": "Thử trải nghiệm hội thoại cốt lõi của Baetter.",
  "pricing.free.cta": "Luyện miễn phí",
  "pricing.plus.description": "Dành cho người muốn tạo thói quen nói hằng ngày.",
  "pricing.plus.cta": "Tiếp tục với Plus",
  "pricing.premium.description":
    "Dành cho người muốn trò chuyện sâu và đa dạng hơn với persona yêu thích.",
  "pricing.premium.cta": "Bắt đầu Premium",
  "pricing.footer": "Gói tự động gia hạn. Hủy bất cứ lúc nào trong cài đặt tài khoản.",
  "footer.label": "Chân trang Baetter",
  "footer.policy.label": "Liên kết chính sách",
  "footer.faq.label": "Câu hỏi thường gặp",
  "footer.faq.heading": "Câu hỏi thường gặp",
  "footer.faq.teams.question": "Người mới hoàn toàn có dùng được không?",
  "footer.faq.teams.answer":
    "Có. Bắt đầu với câu ngắn và tình huống quen thuộc, rồi tiến bộ theo tốc độ của bạn với sửa lỗi AI.",
  "footer.faq.comparison.question": "AI sửa tiếng Hàn như thế nào?",
  "footer.faq.comparison.answer":
    "Ngoài ngữ pháp, AI còn gợi ý khoảng cách, kính ngữ và cách nói tự nhiên theo ngữ cảnh.",
  "footer.faq.practice.question": "Có thể luyện cả giọng nói và văn bản không?",
  "footer.faq.practice.answer":
    "Có. Bạn có thể tiếp tục cùng tình huống bằng văn bản hoặc giọng nói.",
  "footer.faq.personas.question": "Persona AI có phải người thật không?",
  "footer.faq.personas.answer": "Không. Đây là nhân vật AI hư cấu dành cho việc học nhập vai.",
  "footer.faq.plans.question": "Có thể đổi hoặc hủy gói bất cứ lúc nào?",
  "footer.faq.plans.answer":
    "Có. Đổi hoặc hủy trước kỳ thanh toán tiếp theo trong cài đặt tài khoản.",
  "footer.faq.privacy.question": "Giọng nói và hội thoại được xử lý thế nào?",
  "footer.faq.privacy.answer":
    "Chỉ được xử lý khi cần cho luyện tập, với quyền kiểm soát lưu giữ và xóa trong tài khoản.",
  "footer.privacy": "Quyền riêng tư",
  "footer.terms": "Điều khoản",
  "footer.copyright": "© 2026 Baetter. Bảo lưu mọi quyền.",
};

export const thTH: Record<keyof typeof koKR, string> = {
  ...enUS,
  "nav.pricing": "ราคา",
  "feature.cta": "ลงทะเบียน Early Access",
  "nav.menu.open": "เปิดเมนู",
  "nav.menu.close": "ปิดเมนู",
  "nav.menu.label": "เมนูมือถือ",
  "document.title": "Baetter — ฝึกสนทนาภาษาเกาหลีด้วย AI",
  "locale.label": "เลือกภาษา",
  "locale.ko-KR": "เกาหลี",
  "locale.en-US": "อังกฤษ",
  "locale.ar": "อาหรับ",
  "locale.ja-JP": "ญี่ปุ่น",
  "locale.vi-VN": "เวียดนาม",
  "locale.th-TH": "ไทย",
  "locale.zh-CN": "จีนตัวย่อ",
  "locale.zh-TW": "จีนตัวเต็ม",
  "nav.label": "เมนูหลัก",
  "nav.cta": "เริ่มพูด",
  "nav.proof": "ทำไมต้อง Baetter",
  "hero.title": "ฝึกบทสนทนาภาษาเกาหลีจริงด้วยเสียงได้ทุกเวลา",
  "hero.description":
    "เปลี่ยนคำศัพท์ที่เรียนมาให้เป็นคำพูดจริง ฝึกสถานการณ์ รับคำแก้ไขทันที และคุยกับเพอร์โซนาที่คุณชอบ",
  "hero.action": "ลงทะเบียน Early Access",
  "hero.preview": "ตัวอย่างบทสนทนา AI",
  "hero.highlight.roleplay": "สวมบทบาทสถานการณ์จริง",
  "hero.highlight.corrections": "แก้ประโยคให้เป็นธรรมชาติขณะพูด",
  "hero.highlight.personas": "คุยกับเพอร์โซนาที่ชอบทุกวัน",
  "proof.title": "เปลี่ยนคำที่รู้ให้เป็นบทสนทนาที่พูดได้",
  "proof.markets.value": "3 แบบ",
  "proof.markets.label": "สวมบทบาท · แก้ไขทันที · คุยกับเพอร์โซนา",
  "proof.reuse.label": "คู่สนทนา AI พร้อมเสมอ",
  "proof.launch.value": "ทันที",
  "proof.launch.label": "แก้ภาษาเกาหลีให้เป็นธรรมชาติขณะพูด",
  "feature.roleplay.title": "ฝึกสถานการณ์ที่คุณ\nจะได้เจอจริง",
  "feature.roleplay.description": "ฝึกภาษาเกาหลีที่ใช้ได้จริงเมื่อไรก็ได้",
  "feature.roleplay.pill.one": "คาเฟ่ แท็กซี่ พบเพื่อน และอื่น ๆ",
  "feature.roleplay.pill.two": "คุยเรื่องความสนใจและ K-pop",
  "feature.roleplay.pill.three": "พูดหรือพิมพ์ได้ทุกเวลา",
  "feature.roleplay.phone.title": "ฝึกงานแจกลายเซ็นไอดอล",
  "feature.roleplay.phone.badge": "สวมบทบาทงานแจกลายเซ็น",
  "feature.roleplay.phone.translation": "คุณชอบเพลงไหนในอัลบั้มใหม่?",
  "feature.roleplay.tag.roleplay": "สวมบทบาท",
  "feature.roleplay.tag.travel": "ท่องเที่ยว",
  "feature.roleplay.tag.cafe": "คาเฟ่",
  "feature.roleplay.scene.cosmetic": "ซื้อเครื่องสำอาง",
  "feature.roleplay.scene.taxi": "คนขับแท็กซี่",
  "feature.corrections.title": "สร้างประโยคเอง\nรับคำแก้ไขทันที",
  "feature.corrections.description":
    "ไม่ใช่การท่องแฟลชการ์ด\nพูดสิ่งที่ต้องการ แล้วดูสำนวนที่เป็นธรรมชาติ",
  "feature.corrections.feedback": "สำนวนที่เป็นธรรมชาติกว่า",
  "feature.corrections.explanation":
    "เว้นวรรคหลัง 나 และใช้ 가고 있어(요) เพื่อให้สุภาพและเป็นธรรมชาติ",
  "feature.bias.title": "คุยกับเมนของคุณ\nเป็นภาษาเกาหลี",
  "feature.bias.description":
    "เปลี่ยนความชอบให้เป็นการฝึกทุกวัน ผ่านบทสนทนากับเพอร์โซนา AI ที่น่าติดตาม",
  "feature.bias.benefit.one": "เลือกเพอร์โซนาที่ตรงกับสไตล์คุณ",
  "feature.bias.benefit.two": "สนทนาอย่างเป็นธรรมชาติโดยไม่กดดัน",
  "feature.bias.benefit.three": "สร้างนิสัยการพูดทุกวัน",
  "feature.bias.persona.midnight.name": "เสียงกระซิบยามเที่ยงคืน",
  "feature.bias.persona.midnight.quote":
    "บนเวทีฉันคือมิวส์ผู้เย็นชา แต่ยามเที่ยงคืนฉันอยากฟังคุณพูดเกาหลีเท่านั้น",
  "feature.bias.persona.midnight.tags": "#บทเรียนลับ #อ่อนโยน",
  "feature.bias.persona.midnight.streak": "ผู้เรียน 1,000+",
  "feature.bias.persona.offrecord.name": "บทเรียนนอกกล้อง",
  "feature.bias.persona.offrecord.quote": "ฉันไม่ยิ้มให้กล้อง แต่จะยิ้มเมื่อได้ยินคุณฝึกภาษาเกาหลี",
  "feature.bias.persona.offrecord.tags": "#บทเรียนลับ #อ่อนโยน",
  "feature.bias.persona.offrecord.streak": "ผู้เรียน 500+",
  "feature.bias.persona.order.name": "นี่คือคำสั่ง",
  "feature.bias.persona.order.quote": "วันนี้พูดภาษาเกาหลีกับฉัน อยู่ใกล้ ๆ และพูดตามฉันนะ",
  "feature.bias.persona.order.tags": "#ทหาร #ภารกิจ",
  "feature.bias.persona.order.streak": "ผู้เรียน 1,000+",
  "feature.bias.persona.closer.name": "เข้ามาใกล้อีก",
  "feature.bias.persona.closer.quote": "ค่อย ๆ พูดสิ่งที่อยู่ในใจเป็นภาษาเกาหลี ฉันจะอยู่ข้างคุณ",
  "feature.bias.persona.closer.tags": "#ยุคโชซอน #อ่อนโยน",
  "feature.bias.persona.closer.streak": "ผู้เรียน 500+",
  "cta.title": "เริ่มบทสนทนาภาษาเกาหลีก่อนใคร",
  "cta.description": "ใช้อีเมลเดียวก็สมัครเสร็จ รับคำเชิญ Early Access ของ Baetter ก่อนใคร",
  "cta.action": "จองที่ของฉัน",
  "cta.badge": "Early Access จำนวนจำกัด",
  "cta.note.card": "ไม่ต้องใช้บัตร",
  "cta.note.access": "เปลี่ยนแพ็กเกจได้ทุกเมื่อ",
  "pricing.kicker": "แพ็กเกจที่เข้ากับจังหวะการเรียน",
  "pricing.title": "เริ่มง่าย ๆ และพูดได้เท่าที่ต้องการ",
  "pricing.subtitle": "จากบทสนทนาแรก\nสู่กิจวัตรภาษาเกาหลีทุกวัน",
  "pricing.unit": "/เดือน",
  "pricing.billing.monthly": "รายเดือน",
  "pricing.billing.annual": "รายปี",
  "pricing.billing.save": "ประหยัด 20%",
  "pricing.badge.popular": "ยอดนิยม",
  "pricing.free.name": "ฟรี",
  "pricing.free.description": "ทดลองประสบการณ์สนทนาหลักของ Baetter",
  "pricing.free.cta": "ฝึกฟรี",
  "pricing.plus.description": "สำหรับผู้เรียนที่อยากสร้างนิสัยการพูดทุกวัน",
  "pricing.plus.cta": "พูดต่อด้วย Plus",
  "pricing.premium.description": "สำหรับผู้ที่ต้องการบทสนทนาที่ลึกและหลากหลายกับเพอร์โซนาที่ชอบ",
  "pricing.premium.cta": "เริ่ม Premium",
  "pricing.footer": "แพ็กเกจต่ออายุอัตโนมัติ ยกเลิกได้ทุกเมื่อในการตั้งค่าบัญชี",
  "footer.label": "ส่วนท้าย Baetter",
  "footer.policy.label": "ลิงก์นโยบาย",
  "footer.faq.label": "คำถามที่พบบ่อย",
  "footer.faq.heading": "คำถามที่พบบ่อย",
  "footer.faq.teams.question": "ผู้เริ่มต้นใช้ได้ไหม?",
  "footer.faq.teams.answer":
    "ได้ เริ่มจากวลีสั้น ๆ และสถานการณ์คุ้นเคย แล้วค่อยพัฒนาด้วยคำแก้ไขจาก AI",
  "footer.faq.comparison.question": "AI แก้ภาษาเกาหลีอย่างไร?",
  "footer.faq.comparison.answer":
    "นอกจากไวยากรณ์แล้ว ยังแนะนำการเว้นวรรค ระดับความสุภาพ และสำนวนธรรมชาติตามบริบท",
  "footer.faq.practice.question": "ฝึกทั้งเสียงและข้อความได้ไหม?",
  "footer.faq.practice.answer": "ได้ คุณสามารถฝึกสถานการณ์เดียวกันต่อด้วยข้อความหรือเสียง",
  "footer.faq.personas.question": "เพอร์โซนา AI เป็นคนจริงไหม?",
  "footer.faq.personas.answer": "ไม่ใช่ เป็นตัวละคร AI สมมติที่ออกแบบเพื่อการฝึก",
  "footer.faq.plans.question": "เปลี่ยนหรือยกเลิกแพ็กเกจได้ทุกเมื่อไหม?",
  "footer.faq.plans.answer": "ได้ เปลี่ยนหรือยกเลิกก่อนรอบชำระถัดไปในการตั้งค่าบัญชี",
  "footer.faq.privacy.question": "เสียงและบทสนทนาถูกจัดการอย่างไร?",
  "footer.faq.privacy.answer": "ประมวลผลเท่าที่จำเป็นต่อการฝึก และควบคุมการเก็บหรือลบได้ในบัญชี",
  "footer.privacy": "ความเป็นส่วนตัว",
  "footer.terms": "ข้อกำหนด",
  "footer.copyright": "© 2026 Baetter สงวนลิขสิทธิ์",
};

export const zhTW: Record<keyof typeof koKR, string> = {
  ...enUS,
  "nav.pricing": "價格",
  "feature.cta": "申請搶先體驗",
  "nav.menu.open": "開啟選單",
  "nav.menu.close": "關閉選單",
  "nav.menu.label": "行動版選單",
  "document.title": "Baetter — AI 韓語會話練習",
  "locale.label": "選擇語言",
  "locale.ko-KR": "韓語",
  "locale.en-US": "英語",
  "locale.ar": "阿拉伯語",
  "locale.ja-JP": "日語",
  "locale.vi-VN": "越南語",
  "locale.th-TH": "泰語",
  "locale.zh-CN": "簡體中文",
  "locale.zh-TW": "繁體中文",
  "nav.label": "主導覽",
  "nav.cta": "開始對話",
  "nav.proof": "為什麼選擇 Baetter",
  "hero.title": "隨時開口練習真實的韓語會話",
  "hero.description":
    "把學過的單字真正說出來。角色扮演真實情境、獲得即時修正，還能與喜歡的 AI 角色聊天。",
  "hero.action": "申請搶先體驗",
  "hero.preview": "AI 會話預覽",
  "hero.highlight.roleplay": "真實情境角色扮演",
  "hero.highlight.corrections": "邊說邊獲得自然表達修正",
  "hero.highlight.personas": "每天與喜歡的角色聊天",
  "proof.title": "把認識的單字變成真正能說的會話",
  "proof.markets.value": "3 種",
  "proof.markets.label": "角色扮演 · 即時修正 · 角色聊天",
  "proof.reuse.label": "隨時在線的 AI 會話夥伴",
  "proof.launch.value": "即時",
  "proof.launch.label": "說話時修正為自然韓語",
  "feature.roleplay.title": "角色扮演你真正\n會遇到的情境",
  "feature.roleplay.description": "隨時練習真實會話中用得到的韓語。",
  "feature.roleplay.pill.one": "咖啡廳、計程車、朋友見面等",
  "feature.roleplay.pill.two": "聊興趣和 K-pop",
  "feature.roleplay.pill.three": "隨時語音或文字練習",
  "feature.roleplay.phone.title": "練習偶像簽名會",
  "feature.roleplay.phone.badge": "偶像簽名會角色扮演",
  "feature.roleplay.phone.translation": "新專輯裡你喜歡哪首歌？",
  "feature.roleplay.tag.roleplay": "角色扮演",
  "feature.roleplay.tag.travel": "旅行",
  "feature.roleplay.tag.cafe": "咖啡廳",
  "feature.roleplay.scene.cosmetic": "購買化妝品",
  "feature.roleplay.scene.taxi": "計程車司機",
  "feature.corrections.title": "自己造句，\n立即獲得修正。",
  "feature.corrections.description": "不是又一套單字卡。\n說出你的想法，看看韓國人會如何自然表達。",
  "feature.corrections.feedback": "更自然的表達",
  "feature.corrections.explanation": "在 나 後加入空格，並使用 가고 있어(요)，讓表達更自然有禮。",
  "feature.bias.title": "用韓語和你的本命\n聊天。",
  "feature.bias.description": "把熱愛變成每日練習，透過沉浸式 AI 角色會話輕鬆堅持。",
  "feature.bias.benefit.one": "選擇你喜歡風格的角色",
  "feature.bias.benefit.two": "無壓力地延續自然會話",
  "feature.bias.benefit.three": "養成每日開口習慣",
  "feature.bias.persona.midnight.name": "午夜低語",
  "feature.bias.persona.midnight.quote": "舞台上的我是冷酷沉默的繆斯，但午夜時我只想聽你說韓語。",
  "feature.bias.persona.midnight.tags": "#秘密課程 #溫柔陪練",
  "feature.bias.persona.midnight.streak": "1,000+ 位學習者",
  "feature.bias.persona.offrecord.name": "鏡頭外課程",
  "feature.bias.persona.offrecord.quote": "我從不對鏡頭笑，但聽到你練習韓語時總會微笑。",
  "feature.bias.persona.offrecord.tags": "#秘密課程 #溫柔陪練",
  "feature.bias.persona.offrecord.streak": "500+ 位學習者",
  "feature.bias.persona.order.name": "這是命令",
  "feature.bias.persona.order.quote": "今天和我說韓語。靠近一點，跟著我用韓語說。",
  "feature.bias.persona.order.tags": "#軍隊 #任務",
  "feature.bias.persona.order.streak": "1,000+ 位學習者",
  "feature.bias.persona.closer.name": "再靠近一點",
  "feature.bias.persona.closer.quote": "慢慢來。把心裡的話用韓語告訴我，我會陪在你身邊。",
  "feature.bias.persona.closer.tags": "#朝鮮時代 #溫柔陪練",
  "feature.bias.persona.closer.streak": "500+ 位學習者",
  "cta.title": "搶先開始你的第一次韓語對話",
  "cta.description": "只需一個電子郵件即可完成申請，優先收到 Baetter 搶先體驗邀請。",
  "cta.action": "先為我保留名額",
  "cta.badge": "限量搶先體驗",
  "cta.note.card": "無需信用卡",
  "cta.note.access": "可隨時更換方案",
  "pricing.kicker": "適合你學習節奏的方案",
  "pricing.title": "輕鬆開始，想說多少就說多少",
  "pricing.subtitle": "從第一次輕鬆會話\n到每天沉浸式韓語練習。",
  "pricing.unit": "/月",
  "pricing.billing.monthly": "月付",
  "pricing.billing.annual": "年付",
  "pricing.billing.save": "節省 20%",
  "pricing.badge.popular": "熱門",
  "pricing.free.name": "免費",
  "pricing.free.description": "輕鬆體驗 Baetter 的核心會話功能。",
  "pricing.free.cta": "免費練習",
  "pricing.plus.description": "適合希望養成每日開口習慣的學習者。",
  "pricing.plus.cta": "使用 Plus 繼續練習",
  "pricing.premium.description": "適合希望與喜歡的角色進行更深入、多樣會話的學習者。",
  "pricing.premium.cta": "開始 Premium",
  "pricing.footer": "方案會自動續訂，可隨時在帳戶設定中取消。",
  "footer.label": "Baetter 頁尾",
  "footer.policy.label": "政策連結",
  "footer.faq.label": "常見問題",
  "footer.faq.heading": "常見問題",
  "footer.faq.teams.question": "零基礎也能使用嗎？",
  "footer.faq.teams.answer": "可以。從短句和熟悉情境開始，根據 AI 的清楚修正按自己的節奏進步。",
  "footer.faq.comparison.question": "AI 如何修正我的韓語？",
  "footer.faq.comparison.answer": "除了文法，還會根據對話情境建議空格、敬語和更自然的表達。",
  "footer.faq.practice.question": "可以同時練習語音和文字嗎？",
  "footer.faq.practice.answer": "可以。同一情境可用文字練習，也可切換到語音繼續。",
  "footer.faq.personas.question": "AI 角色是真人嗎？",
  "footer.faq.personas.answer": "不是。它們是為沉浸式學習設計的虛構 AI 角色。",
  "footer.faq.plans.question": "可以隨時更換或取消方案嗎？",
  "footer.faq.plans.answer": "可以。在下次扣款前透過帳戶設定更換或取消。",
  "footer.faq.privacy.question": "我的語音和對話如何處理？",
  "footer.faq.privacy.answer": "僅在練習所需範圍內處理，並可在帳戶中管理保留與刪除。",
  "footer.privacy": "隱私權",
  "footer.terms": "條款",
  "footer.copyright": "© 2026 Baetter。保留所有權利。",
};

export const zhCN: Record<keyof typeof koKR, string> = {
  ...zhTW,
  "nav.pricing": "价格",
  "feature.cta": "申请抢先体验",
  "nav.menu.open": "打开菜单",
  "nav.menu.close": "关闭菜单",
  "nav.menu.label": "移动菜单",
  "document.title": "Baetter — AI 韩语会话练习",
  "locale.label": "选择语言",
  "locale.ko-KR": "韩语",
  "locale.en-US": "英语",
  "locale.ar": "阿拉伯语",
  "locale.ja-JP": "日语",
  "locale.vi-VN": "越南语",
  "locale.th-TH": "泰语",
  "locale.zh-CN": "简体中文",
  "locale.zh-TW": "繁体中文",
  "nav.label": "主导航",
  "nav.cta": "开始对话",
  "nav.proof": "为什么选择 Baetter",
  "hero.title": "随时开口练习真实的韩语会话",
  "hero.description":
    "把学过的单词真正说出来。角色扮演真实场景，获得即时纠正，还能与喜欢的 AI 角色聊天。",
  "hero.action": "申请抢先体验",
  "hero.preview": "AI 会话预览",
  "hero.highlight.roleplay": "真实场景角色扮演",
  "hero.highlight.corrections": "边说边获得自然表达纠正",
  "hero.highlight.personas": "每天与喜欢的角色聊天",
  "proof.title": "把认识的单词变成真正能说的会话",
  "proof.markets.value": "3 种",
  "proof.markets.label": "角色扮演 · 即时纠正 · 角色聊天",
  "proof.reuse.label": "随时在线的 AI 会话伙伴",
  "proof.launch.value": "即时",
  "proof.launch.label": "说话时纠正为自然韩语",
  "feature.roleplay.title": "角色扮演你真正\n会遇到的场景",
  "feature.roleplay.description": "随时练习真实会话中用得到的韩语。",
  "feature.roleplay.pill.one": "咖啡馆、出租车、朋友见面等",
  "feature.roleplay.pill.two": "聊兴趣和 K-pop",
  "feature.roleplay.pill.three": "随时语音或文字练习",
  "feature.roleplay.phone.title": "练习偶像签售会",
  "feature.roleplay.phone.badge": "偶像签售会角色扮演",
  "feature.roleplay.phone.translation": "新专辑里你喜欢哪首歌？",
  "feature.roleplay.tag.roleplay": "角色扮演",
  "feature.roleplay.tag.travel": "旅行",
  "feature.roleplay.tag.cafe": "咖啡馆",
  "feature.roleplay.scene.cosmetic": "购买化妆品",
  "feature.roleplay.scene.taxi": "出租车司机",
  "feature.corrections.title": "自己造句，\n立即获得纠正。",
  "feature.corrections.description": "不是又一套单词卡。\n说出你的想法，看看韩国人会如何自然表达。",
  "feature.corrections.feedback": "更自然的表达",
  "feature.corrections.explanation": "在 나 后添加空格，并使用 가고 있어(요)，让表达更自然礼貌。",
  "feature.bias.title": "用韩语和你的本命\n聊天。",
  "feature.bias.description": "把热爱变成每日练习，通过沉浸式 AI 角色会话轻松坚持。",
  "feature.bias.benefit.one": "选择你喜欢风格的角色",
  "feature.bias.benefit.two": "无压力地延续自然会话",
  "feature.bias.benefit.three": "养成每日开口习惯",
  "feature.bias.persona.midnight.name": "午夜低语",
  "feature.bias.persona.midnight.quote": "舞台上的我是冷酷缄默的缪斯，但午夜时我只想听你说韩语。",
  "feature.bias.persona.midnight.tags": "#秘密课程 #温柔陪练",
  "feature.bias.persona.midnight.streak": "1,000+ 学习者",
  "feature.bias.persona.offrecord.name": "镜头外课程",
  "feature.bias.persona.offrecord.quote": "我从不对镜头笑，但听到你练习韩语时总会微笑。",
  "feature.bias.persona.offrecord.tags": "#秘密课程 #温柔陪练",
  "feature.bias.persona.offrecord.streak": "500+ 学习者",
  "feature.bias.persona.order.name": "这是命令",
  "feature.bias.persona.order.quote": "今天和我说韩语。靠近一点，跟着我用韩语说。",
  "feature.bias.persona.order.tags": "#军队 #任务",
  "feature.bias.persona.order.streak": "1,000+ 学习者",
  "feature.bias.persona.closer.name": "再靠近一点",
  "feature.bias.persona.closer.quote": "慢慢来。把心里的话用韩语告诉我，我会陪在你身边。",
  "feature.bias.persona.closer.tags": "#朝鲜时代 #温柔陪练",
  "feature.bias.persona.closer.streak": "500+ 学习者",
  "cta.title": "抢先开始你的第一次韩语对话",
  "cta.description": "只需一个电子邮箱即可完成申请，优先收到 Baetter 抢先体验邀请。",
  "cta.action": "先为我保留名额",
  "cta.badge": "限量抢先体验",
  "cta.note.card": "无需银行卡",
  "cta.note.access": "可随时更换方案",
  "pricing.kicker": "适合你学习节奏的方案",
  "pricing.title": "轻松开始，想说多少就说多少",
  "pricing.subtitle": "从第一次轻松会话\n到每天沉浸式韩语练习。",
  "pricing.unit": "/月",
  "pricing.billing.monthly": "月付",
  "pricing.billing.annual": "年付",
  "pricing.billing.save": "节省 20%",
  "pricing.badge.popular": "热门",
  "pricing.free.name": "免费",
  "pricing.free.description": "轻松体验 Baetter 的核心会话功能。",
  "pricing.free.cta": "免费练习",
  "pricing.plus.description": "适合希望养成每日开口习惯的学习者。",
  "pricing.plus.cta": "使用 Plus 继续练习",
  "pricing.premium.description": "适合希望与喜欢的角色进行更深入、多样会话的学习者。",
  "pricing.premium.cta": "开始 Premium",
  "pricing.footer": "方案会自动续订，可随时在账户设置中取消。",
  "footer.label": "Baetter 页脚",
  "footer.policy.label": "政策链接",
  "footer.faq.label": "常见问题",
  "footer.faq.heading": "常见问题",
  "footer.faq.teams.question": "零基础也能使用吗？",
  "footer.faq.teams.answer": "可以。从短句和熟悉场景开始，根据 AI 的清晰纠正按自己的节奏进步。",
  "footer.faq.comparison.question": "AI 如何纠正我的韩语？",
  "footer.faq.comparison.answer": "除了语法，还会根据对话情境建议空格、敬语和更自然的表达。",
  "footer.faq.practice.question": "可以同时练习语音和文字吗？",
  "footer.faq.practice.answer": "可以。同一场景可用文字练习，也可切换到语音继续。",
  "footer.faq.personas.question": "AI 角色是真人吗？",
  "footer.faq.personas.answer": "不是。它们是为沉浸式学习设计的虚构 AI 角色。",
  "footer.faq.plans.question": "可以随时更换或取消方案吗？",
  "footer.faq.plans.answer": "可以。在下次扣费前通过账户设置更换或取消。",
  "footer.faq.privacy.question": "我的语音和对话如何处理？",
  "footer.faq.privacy.answer": "仅在练习所需范围内处理，并可在账户中管理保留与删除。",
  "footer.privacy": "隐私",
  "footer.terms": "条款",
  "footer.copyright": "© 2026 Baetter。保留所有权利。",
};
