export const koKR = {
  "nav.menu.open": "메뉴 열기",
  "nav.menu.close": "메뉴 닫기",
  "nav.menu.label": "모바일 메뉴",
  "document.title": "Luma 접근 방식 비교",
  brand: "Luma 비교",
  "nav.label": "주요 메뉴",
  "nav.comparison": "비교",
  "nav.benefits": "장점",
  "nav.cta": "Luma 선택",
  "locale.label": "언어 선택",
  "locale.ko-KR": "한국어",
  "locale.en-US": "영어",
  "locale.ar": "아랍어",
  "hero.eyebrow": "더 나은 의사결정",
  "hero.title": "결정하기 전에 경로를 비교하세요",
  "hero.description":
    "공통 시스템이 단절된 출시를\n반복 가능한 학습 과정으로 바꾸는 방법을 확인하세요.",
  "hero.action": "Get Early Access",
  "hero.preview": "접근 방식 미리보기",
  "comparison.title": "더 명확한 경로를 선택하세요",
  "comparison.region": "스크롤 가능한 접근 방식 비교",
  "comparison.table": "접근 방식 비교",
  "comparison.criterion": "기준",
  "comparison.product": "Luma",
  "comparison.alternative": "임시 방식",
  "comparison.setup.criterion": "설정",
  "comparison.setup.product": "공유되고 준비됨",
  "comparison.setup.alternative": "매번 다시 구축",
  "comparison.brand.criterion": "브랜드 일관성",
  "comparison.brand.product": "토큰 기반",
  "comparison.brand.alternative": "수동 검토",
  "comparison.extension.criterion": "실험 UI",
  "comparison.extension.product": "로컬 조합 가능",
  "comparison.extension.alternative": "전역 결합",
  "features.title": "트레이드오프를 보여주는 시스템",
  "features.clarity.title": "명확한\n경계",
  "features.clarity.description": "공통 책임과 로컬 책임을\n쉽게 구분할 수 있습니다.",
  "features.access.title": "접근 가능한 기본값",
  "features.access.description": "시맨틱 구조와 보이는 포커스가 기반부터 적용됩니다.",
  "features.global.title": "글로벌 도달",
  "features.global.description": "유연한 레이아웃이 다양한 기기와 긴 번역문을 수용합니다.",
  "cta.title": "변화에 발맞추는 기반을 선택하세요",
  "cta.description": "비교에서 실제 실험까지 하나의 일관된 작업 공간에서 진행하세요.",
  "cta.action": "시스템 선택",
  "footer.message": "글로벌 팀을 위해 제작",
  "footer.top": "맨 위로",
  "footer.label": "Luma 비교 푸터",
  "footer.links.label": "비교 링크",
  "footer.policy.label": "정책 링크",
  "footer.faq.label": "자주 묻는 질문",
  "footer.faq.heading": "자주 묻는 질문",
  "footer.faq.teams.question": "어떤 팀을 위한 서비스인가요?",
  "footer.faq.teams.answer":
    "일관된 실험과 더 명확한 의사결정이 필요한 글로벌 제품 팀을 위해 설계했습니다.",
  "footer.faq.comparison.question": "접근 방식은 어떻게 비교하나요?",
  "footer.faq.comparison.answer":
    "설정, 브랜드 일관성, 확장성 기준을 한 화면에서 나란히 확인할 수 있습니다.",
  "footer.privacy": "개인정보 처리방침",
  "footer.terms": "이용약관",
  "footer.copyright": "© 2026 Luma 비교. 모든 권리 보유.",
} as const;
export const enUS: Record<keyof typeof koKR, string> = {
  "nav.menu.open": "Open menu",
  "nav.menu.close": "Close menu",
  "nav.menu.label": "Mobile menu",
  "document.title": "Compare approaches with Luma",
  "locale.label": "Choose language",
  "locale.ko-KR": "Korean",
  "locale.en-US": "English",
  "locale.ar": "Arabic",
  brand: "Luma Compare",
  "nav.label": "Primary",
  "nav.comparison": "Comparison",
  "nav.benefits": "Benefits",
  "nav.cta": "Choose Luma",
  "hero.eyebrow": "A better way to decide",
  "hero.title": "Compare the paths before you commit",
  "hero.description":
    "See how a shared system turns disconnected launches\ninto a repeatable learning practice.",
  "hero.action": "Get Early Access",
  "hero.preview": "Approach preview",
  "comparison.title": "Choose the clearer path",
  "comparison.region": "Scrollable approach comparison",
  "comparison.table": "Approach comparison",
  "comparison.criterion": "Criterion",
  "comparison.product": "Luma",
  "comparison.alternative": "Ad hoc",
  "comparison.setup.criterion": "Setup",
  "comparison.setup.product": "Shared and ready",
  "comparison.setup.alternative": "Rebuilt every time",
  "comparison.brand.criterion": "Brand consistency",
  "comparison.brand.product": "Token driven",
  "comparison.brand.alternative": "Manually reviewed",
  "comparison.extension.criterion": "Experiment UI",
  "comparison.extension.product": "Locally composable",
  "comparison.extension.alternative": "Globally coupled",
  "features.title": "A system that makes tradeoffs visible",
  "features.clarity.title": "Clear\nboundaries",
  "features.clarity.description": "Shared and local responsibilities\nremain easy to see.",
  "features.access.title": "Accessible defaults",
  "features.access.description": "Semantic structure and visible focus begin at the foundation.",
  "features.global.title": "Global reach",
  "features.global.description": "Flexible layouts accommodate devices and longer translations.",
  "cta.title": "Choose a foundation that keeps up",
  "cta.description": "Move from comparison to a working experiment in one coherent workspace.",
  "cta.action": "Choose the system",
  "footer.message": "Built for global teams",
  "footer.top": "Back to top",
  "footer.label": "Luma Compare footer",
  "footer.links.label": "Comparison links",
  "footer.policy.label": "Policy links",
  "footer.faq.label": "Frequently asked questions",
  "footer.faq.heading": "Frequently asked questions",
  "footer.faq.teams.question": "Which teams is this for?",
  "footer.faq.teams.answer":
    "It is designed for global product teams that need consistent experiments and clearer decisions.",
  "footer.faq.comparison.question": "How are approaches compared?",
  "footer.faq.comparison.answer":
    "Review setup, brand consistency, and extensibility side by side on one page.",
  "footer.privacy": "Privacy",
  "footer.terms": "Terms",
  "footer.copyright": "© 2026 Luma Compare. All rights reserved.",
};
export const ar: Record<keyof typeof koKR, string> = {
  "nav.menu.open": "افتح القائمة",
  "nav.menu.close": "أغلق القائمة",
  "nav.menu.label": "قائمة الجوال",
  "document.title": "قارن الأساليب مع لوما",
  "locale.label": "اختر اللغة",
  "locale.ko-KR": "الكورية",
  "locale.en-US": "الإنجليزية",
  "locale.ar": "العربية",
  brand: "مقارنة لوما",
  "nav.label": "التنقل الرئيسي",
  "nav.comparison": "المقارنة",
  "nav.benefits": "الفوائد",
  "nav.cta": "اختر لوما",
  "hero.eyebrow": "طريقة أفضل للقرار",
  "hero.title": "قارن المسارات قبل الالتزام",
  "hero.description":
    "اكتشف كيف يحول النظام المشترك عمليات الإطلاق المنفصلة\nإلى ممارسة تعلم قابلة للتكرار.",
  "hero.action": "احصل على وصول مبكر",
  "hero.preview": "معاينة الأساليب",
  "comparison.title": "اختر المسار الأوضح",
  "comparison.region": "مقارنة أساليب قابلة للتمرير",
  "comparison.table": "مقارنة الأساليب",
  "comparison.criterion": "المعيار",
  "comparison.product": "لوما",
  "comparison.alternative": "حل مؤقت",
  "comparison.setup.criterion": "الإعداد",
  "comparison.setup.product": "مشترك وجاهز",
  "comparison.setup.alternative": "يُعاد بناؤه كل مرة",
  "comparison.brand.criterion": "اتساق العلامة",
  "comparison.brand.product": "مدعوم بالرموز",
  "comparison.brand.alternative": "مراجعة يدوية",
  "comparison.extension.criterion": "واجهة التجربة",
  "comparison.extension.product": "قابلة للتركيب محلياً",
  "comparison.extension.alternative": "مقترنة عالمياً",
  "features.title": "نظام يوضح المفاضلات",
  "features.clarity.title": "حدود\nواضحة",
  "features.clarity.description": "تبقى المسؤوليات المشتركة والمحلية\nسهلة الرؤية.",
  "features.access.title": "إعدادات ميسّرة",
  "features.access.description": "تبدأ البنية الدلالية والتركيز المرئي من الأساس.",
  "features.global.title": "وصول عالمي",
  "features.global.description": "تستوعب التخطيطات المرنة الأجهزة والترجمات الأطول.",
  "cta.title": "اختر أساساً يواكبك",
  "cta.description": "انتقل من المقارنة إلى تجربة عاملة في مساحة عمل مترابطة.",
  "cta.action": "اختر النظام",
  "footer.message": "صُمم للفرق العالمية",
  "footer.top": "العودة إلى الأعلى",
  "footer.label": "تذييل مقارنة لوما",
  "footer.links.label": "روابط المقارنة",
  "footer.policy.label": "روابط السياسات",
  "footer.faq.label": "الأسئلة الشائعة",
  "footer.faq.heading": "الأسئلة الشائعة",
  "footer.faq.teams.question": "لأي فرق صُممت هذه الخدمة؟",
  "footer.faq.teams.answer":
    "صُممت لفرق المنتجات العالمية التي تحتاج إلى تجارب متسقة وقرارات أوضح.",
  "footer.faq.comparison.question": "كيف تتم مقارنة الأساليب؟",
  "footer.faq.comparison.answer":
    "راجع الإعداد واتساق العلامة وقابلية التوسع جنباً إلى جنب في صفحة واحدة.",
  "footer.privacy": "الخصوصية",
  "footer.terms": "الشروط",
  "footer.copyright": "© 2026 مقارنة لوما. جميع الحقوق محفوظة.",
};
