import type { ComparisonRow, CtaContent, FeatureItem, HeroContent } from "@landing/contracts";
import { landingTestIds } from "@landing/contracts";
import { ButtonLink, CtaSection, FeatureGrid, Hero, LandingShell } from "@landing/ui";
import { BetaComparison } from "../features/beta/BetaComparison";

const hero = { eyebrow: "A better way to decide", title: "Compare the paths before you commit", description: "See how a shared system turns disconnected launches into a repeatable learning practice.", actions: [{ id: "compare", label: "Compare approaches", href: "#comparison", variant: "primary" }] } satisfies HeroContent;
const rows = [{ id: "setup", criterion: "Setup", productValue: "Shared and ready", alternativeValue: "Rebuilt every time" }, { id: "brand", criterion: "Brand consistency", productValue: "Token driven", alternativeValue: "Manually reviewed" }, { id: "extension", criterion: "Experiment UI", productValue: "Locally composable", alternativeValue: "Globally coupled" }] satisfies readonly ComparisonRow[];
const features = [{ id: "clarity", title: "Clear boundaries", description: "Shared and local responsibilities remain easy to see." }, { id: "access", title: "Accessible defaults", description: "Semantic structure and visible focus begin at the foundation." }, { id: "global", title: "Global reach", description: "Flexible layouts accommodate devices and longer translations." }] satisfies readonly FeatureItem[];
const cta = { title: "Choose a foundation that keeps up", description: "Move from comparison to a working experiment in one coherent workspace.", actions: [{ id: "choose", label: "Choose the system", href: "#top", variant: "primary" }] } satisfies CtaContent;

export function App() {
  return <div id="top" data-testid={landingTestIds.betaRoot}><LandingShell header={<LandingShell.Header><div className="container header-inner"><a className="brand" href="#top">Luma Compare</a><nav className="nav" aria-label="Primary"><a href="#comparison">Comparison</a><a href="#features">Benefits</a></nav><ButtonLink href="#cta">Choose Luma</ButtonLink></div></LandingShell.Header>} footer={<LandingShell.Footer><div className="container footer-inner"><span>Built for global teams</span><a href="#top">Back to top</a></div></LandingShell.Footer>}><LandingShell.Main><Hero content={hero} /><div id="comparison"><BetaComparison rows={rows} productLabel="Luma" alternativeLabel="Ad hoc" /></div><div id="features"><FeatureGrid title="A system that makes tradeoffs visible" items={features} /></div><div id="cta"><CtaSection content={cta} /></div></LandingShell.Main></LandingShell></div>;
}
